/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

/// DependentInsuredIndicator : Indicates the status of the insured. For the dependent, this is always `N`.
/// Indicates the status of the insured. For the dependent, this is always `N`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DependentInsuredIndicator {
    #[serde(rename = "N")]
    N,

}

impl std::fmt::Display for DependentInsuredIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::N => write!(f, "N"),
        }
    }
}

impl Default for DependentInsuredIndicator {
    fn default() -> DependentInsuredIndicator {
        Self::N
    }
}

