/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

/// DependentRelationshipCode : For the dependent, this can be `01` - Spouse, `19` - Child, `20` Employee, `21` - Unknown, `39` - Organ Donor, `40` - Cadaver Donor, `53` - Life Partner, or `G8` - Other Relationship.
/// For the dependent, this can be `01` - Spouse, `19` - Child, `20` Employee, `21` - Unknown, `39` - Organ Donor, `40` - Cadaver Donor, `53` - Life Partner, or `G8` - Other Relationship.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DependentRelationshipCode {
    #[serde(rename = "01")]
    Variant01,
    #[serde(rename = "19")]
    Variant19,
    #[serde(rename = "20")]
    Variant20,
    #[serde(rename = "21")]
    Variant21,
    #[serde(rename = "39")]
    Variant39,
    #[serde(rename = "40")]
    Variant40,
    #[serde(rename = "53")]
    Variant53,
    #[serde(rename = "G8")]
    G8,
    #[serde(rename = "Unknown")]
    Unknown,

}

impl std::fmt::Display for DependentRelationshipCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant01 => write!(f, "01"),
            Self::Variant19 => write!(f, "19"),
            Self::Variant20 => write!(f, "20"),
            Self::Variant21 => write!(f, "21"),
            Self::Variant39 => write!(f, "39"),
            Self::Variant40 => write!(f, "40"),
            Self::Variant53 => write!(f, "53"),
            Self::G8 => write!(f, "G8"),
            Self::Unknown => write!(f, "Unknown"),
        }
    }
}

impl Default for DependentRelationshipCode {
    fn default() -> DependentRelationshipCode {
        Self::Variant01
    }
}

