/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

/// EmploymentStatusCode : Payers may sometimes return other non-compliant values.
/// Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EmploymentStatusCode {
    #[serde(rename = "AE")]
    Ae,
    #[serde(rename = "AO")]
    Ao,
    #[serde(rename = "AS")]
    As,
    #[serde(rename = "AT")]
    At,
    #[serde(rename = "AU")]
    Au,
    #[serde(rename = "CC")]
    Cc,
    #[serde(rename = "DD")]
    Dd,
    #[serde(rename = "HD")]
    Hd,
    #[serde(rename = "IR")]
    Ir,
    #[serde(rename = "LX")]
    Lx,
    #[serde(rename = "PE")]
    Pe,
    #[serde(rename = "RE")]
    Re,
    #[serde(rename = "RM")]
    Rm,
    #[serde(rename = "RR")]
    Rr,
    #[serde(rename = "RU")]
    Ru,

}

impl std::fmt::Display for EmploymentStatusCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ae => write!(f, "AE"),
            Self::Ao => write!(f, "AO"),
            Self::As => write!(f, "AS"),
            Self::At => write!(f, "AT"),
            Self::Au => write!(f, "AU"),
            Self::Cc => write!(f, "CC"),
            Self::Dd => write!(f, "DD"),
            Self::Hd => write!(f, "HD"),
            Self::Ir => write!(f, "IR"),
            Self::Lx => write!(f, "LX"),
            Self::Pe => write!(f, "PE"),
            Self::Re => write!(f, "RE"),
            Self::Rm => write!(f, "RM"),
            Self::Rr => write!(f, "RR"),
            Self::Ru => write!(f, "RU"),
        }
    }
}

impl Default for EmploymentStatusCode {
    fn default() -> EmploymentStatusCode {
        Self::Ae
    }
}

