/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InformationReceiverName {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::RequestProviderAddress>>,
    #[serde(rename = "contactNumber", skip_serializing_if = "Option::is_none")]
    pub contact_number: Option<String>,
    #[serde(rename = "contractNumber", skip_serializing_if = "Option::is_none")]
    pub contract_number: Option<String>,
    #[serde(rename = "devicePinNumber", skip_serializing_if = "Option::is_none")]
    pub device_pin_number: Option<String>,
    #[serde(rename = "facilityIdNumber", skip_serializing_if = "Option::is_none")]
    pub facility_id_number: Option<String>,
    #[serde(rename = "facilityNetworkIdNumber", skip_serializing_if = "Option::is_none")]
    pub facility_network_id_number: Option<String>,
    #[serde(rename = "federalTaxpayerIdentificationNumber", skip_serializing_if = "Option::is_none")]
    pub federal_taxpayer_identification_number: Option<String>,
    #[serde(rename = "informationReceiverAdditionalIdentifierState", skip_serializing_if = "Option::is_none")]
    pub information_receiver_additional_identifier_state: Option<String>,
    /// The provider's Medicaid provider number.
    #[serde(rename = "medicaidProviderNumber", skip_serializing_if = "Option::is_none")]
    pub medicaid_provider_number: Option<String>,
    #[serde(rename = "medicareProviderNumber", skip_serializing_if = "Option::is_none")]
    pub medicare_provider_number: Option<String>,
    #[serde(rename = "nationalProviderIdentifier", skip_serializing_if = "Option::is_none")]
    pub national_provider_identifier: Option<String>,
    #[serde(rename = "priorIdentifierNumber", skip_serializing_if = "Option::is_none")]
    pub prior_identifier_number: Option<String>,
    #[serde(rename = "providerPlanNetworkIdNumber", skip_serializing_if = "Option::is_none")]
    pub provider_plan_network_id_number: Option<String>,
    #[serde(rename = "socialSecurityNumber", skip_serializing_if = "Option::is_none")]
    pub social_security_number: Option<String>,
    #[serde(rename = "stateLicenceNumber", skip_serializing_if = "Option::is_none")]
    pub state_licence_number: Option<String>,
    #[serde(rename = "submitterIdNumber", skip_serializing_if = "Option::is_none")]
    pub submitter_id_number: Option<String>,
}

impl InformationReceiverName {
    pub fn new() -> InformationReceiverName {
        InformationReceiverName {
            address: None,
            contact_number: None,
            contract_number: None,
            device_pin_number: None,
            facility_id_number: None,
            facility_network_id_number: None,
            federal_taxpayer_identification_number: None,
            information_receiver_additional_identifier_state: None,
            medicaid_provider_number: None,
            medicare_provider_number: None,
            national_provider_identifier: None,
            prior_identifier_number: None,
            provider_plan_network_id_number: None,
            social_security_number: None,
            state_licence_number: None,
            submitter_id_number: None,
        }
    }
}

