/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

/// InsuranceTypeName : The full name of the insurance type code.  Payers may sometimes return other non-compliant values.
/// The full name of the insurance type code.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InsuranceTypeName {
    #[serde(rename = "Medicare Secondary Working Aged Beneficiary or Spouse with Employer Group Health Plan")]
    MedicareSecondaryWorkingAgedBeneficiaryOrSpouseWithEmployerGroupHealthPlan,
    #[serde(rename = "Medicare Secondary End-Stage Renal Disease Beneficiary in the Mandated Coordination Period with an Employer's Group Health Plan")]
    MedicareSecondaryEndStageRenalDiseaseBeneficiaryInTheMandatedCoordinationPeriodWithAnEmployerQuoteSGroupHealthPlan,
    #[serde(rename = "Medicare Secondary, No-fault Insurance including Auto is Primary")]
    MedicareSecondaryCommaNoFaultInsuranceIncludingAutoIsPrimary,
    #[serde(rename = "Medicare Secondary Worker's Compensation")]
    MedicareSecondaryWorkerQuoteSCompensation,
    #[serde(rename = "Medicare Secondary Public Health Service (PHS)or Other Federal Agency")]
    MedicareSecondaryPublicHealthServiceLeftParenthesisPhsRightParenthesisOrOtherFederalAgency,
    #[serde(rename = "Medicare Secondary Black Lung")]
    MedicareSecondaryBlackLung,
    #[serde(rename = "Medicare Secondary Veteran's Administration")]
    MedicareSecondaryVeteranQuoteSAdministration,
    #[serde(rename = "Medicare Secondary Disabled Beneficiary Under Age 65 with Large Group Health Plan (LGHP)")]
    MedicareSecondaryDisabledBeneficiaryUnderAge65WithLargeGroupHealthPlanLeftParenthesisLghpRightParenthesis,
    #[serde(rename = "Medicare Secondary, Other Liability Insurance is Primary")]
    MedicareSecondaryCommaOtherLiabilityInsuranceIsPrimary,
    #[serde(rename = "Auto Insurance Policy")]
    AutoInsurancePolicy,
    #[serde(rename = "Commercial")]
    Commercial,
    #[serde(rename = "Consolidated Omnibus Budget Reconciliation Act (COBRA)")]
    ConsolidatedOmnibusBudgetReconciliationActLeftParenthesisCobraRightParenthesis,
    #[serde(rename = "Medicare Conditionally Primary")]
    MedicareConditionallyPrimary,
    #[serde(rename = "Disability")]
    Disability,
    #[serde(rename = "Disability Benefits")]
    DisabilityBenefits,
    #[serde(rename = "Exclusive Provider Organization")]
    ExclusiveProviderOrganization,
    #[serde(rename = "Family or Friends")]
    FamilyOrFriends,
    #[serde(rename = "Group Policy")]
    GroupPolicy,
    #[serde(rename = "Health Maintenance Organization (HMO)")]
    HealthMaintenanceOrganizationLeftParenthesisHmoRightParenthesis,
    #[serde(rename = "Health Maintenance Organization (HMO) - Medicare Risk")]
    HealthMaintenanceOrganizationLeftParenthesisHmoRightParenthesisMedicareRisk,
    #[serde(rename = "Special Low Income Medicare Beneficiary")]
    SpecialLowIncomeMedicareBeneficiary,
    #[serde(rename = "Indemnity")]
    Indemnity,
    #[serde(rename = "Individual Policy")]
    IndividualPolicy,
    #[serde(rename = "Long Term Care")]
    LongTermCare,
    #[serde(rename = "Long Term Policy")]
    LongTermPolicy,
    #[serde(rename = "Life Insurance")]
    LifeInsurance,
    #[serde(rename = "Litigation")]
    Litigation,
    #[serde(rename = "Medicare Part A")]
    MedicarePartA,
    #[serde(rename = "Medicare Part B")]
    MedicarePartB,
    #[serde(rename = "Medicaid")]
    Medicaid,
    #[serde(rename = "Medigap Part A")]
    MedigapPartA,
    #[serde(rename = "Medigap Part B")]
    MedigapPartB,
    #[serde(rename = "Medicare Primary")]
    MedicarePrimary,
    #[serde(rename = "Other")]
    Other,
    #[serde(rename = "Property Insurance - Personal")]
    PropertyInsurancePersonal,
    #[serde(rename = "Personal")]
    Personal,
    #[serde(rename = "Personal Payment (Cash - No Insurance)")]
    PersonalPaymentLeftParenthesisCashNoInsuranceRightParenthesis,
    #[serde(rename = "Preferred Provider Organization (PPO)")]
    PreferredProviderOrganizationLeftParenthesisPpoRightParenthesis,
    #[serde(rename = "Point of Service (POS)")]
    PointOfServiceLeftParenthesisPosRightParenthesis,
    #[serde(rename = "Qualified Medicare Beneficiary")]
    QualifiedMedicareBeneficiary,
    #[serde(rename = "Property Insurance - Real")]
    PropertyInsuranceReal,
    #[serde(rename = "Supplemental Policy")]
    SupplementalPolicy,
    #[serde(rename = "Tax Equity Fiscal Responsibility Act (TEFRA)")]
    TaxEquityFiscalResponsibilityActLeftParenthesisTefraRightParenthesis,
    #[serde(rename = "Workers Compensation")]
    WorkersCompensation,
    #[serde(rename = "Wrap Up Policy")]
    WrapUpPolicy,

}

impl std::fmt::Display for InsuranceTypeName {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MedicareSecondaryWorkingAgedBeneficiaryOrSpouseWithEmployerGroupHealthPlan => write!(f, "Medicare Secondary Working Aged Beneficiary or Spouse with Employer Group Health Plan"),
            Self::MedicareSecondaryEndStageRenalDiseaseBeneficiaryInTheMandatedCoordinationPeriodWithAnEmployerQuoteSGroupHealthPlan => write!(f, "Medicare Secondary End-Stage Renal Disease Beneficiary in the Mandated Coordination Period with an Employer's Group Health Plan"),
            Self::MedicareSecondaryCommaNoFaultInsuranceIncludingAutoIsPrimary => write!(f, "Medicare Secondary, No-fault Insurance including Auto is Primary"),
            Self::MedicareSecondaryWorkerQuoteSCompensation => write!(f, "Medicare Secondary Worker's Compensation"),
            Self::MedicareSecondaryPublicHealthServiceLeftParenthesisPhsRightParenthesisOrOtherFederalAgency => write!(f, "Medicare Secondary Public Health Service (PHS)or Other Federal Agency"),
            Self::MedicareSecondaryBlackLung => write!(f, "Medicare Secondary Black Lung"),
            Self::MedicareSecondaryVeteranQuoteSAdministration => write!(f, "Medicare Secondary Veteran's Administration"),
            Self::MedicareSecondaryDisabledBeneficiaryUnderAge65WithLargeGroupHealthPlanLeftParenthesisLghpRightParenthesis => write!(f, "Medicare Secondary Disabled Beneficiary Under Age 65 with Large Group Health Plan (LGHP)"),
            Self::MedicareSecondaryCommaOtherLiabilityInsuranceIsPrimary => write!(f, "Medicare Secondary, Other Liability Insurance is Primary"),
            Self::AutoInsurancePolicy => write!(f, "Auto Insurance Policy"),
            Self::Commercial => write!(f, "Commercial"),
            Self::ConsolidatedOmnibusBudgetReconciliationActLeftParenthesisCobraRightParenthesis => write!(f, "Consolidated Omnibus Budget Reconciliation Act (COBRA)"),
            Self::MedicareConditionallyPrimary => write!(f, "Medicare Conditionally Primary"),
            Self::Disability => write!(f, "Disability"),
            Self::DisabilityBenefits => write!(f, "Disability Benefits"),
            Self::ExclusiveProviderOrganization => write!(f, "Exclusive Provider Organization"),
            Self::FamilyOrFriends => write!(f, "Family or Friends"),
            Self::GroupPolicy => write!(f, "Group Policy"),
            Self::HealthMaintenanceOrganizationLeftParenthesisHmoRightParenthesis => write!(f, "Health Maintenance Organization (HMO)"),
            Self::HealthMaintenanceOrganizationLeftParenthesisHmoRightParenthesisMedicareRisk => write!(f, "Health Maintenance Organization (HMO) - Medicare Risk"),
            Self::SpecialLowIncomeMedicareBeneficiary => write!(f, "Special Low Income Medicare Beneficiary"),
            Self::Indemnity => write!(f, "Indemnity"),
            Self::IndividualPolicy => write!(f, "Individual Policy"),
            Self::LongTermCare => write!(f, "Long Term Care"),
            Self::LongTermPolicy => write!(f, "Long Term Policy"),
            Self::LifeInsurance => write!(f, "Life Insurance"),
            Self::Litigation => write!(f, "Litigation"),
            Self::MedicarePartA => write!(f, "Medicare Part A"),
            Self::MedicarePartB => write!(f, "Medicare Part B"),
            Self::Medicaid => write!(f, "Medicaid"),
            Self::MedigapPartA => write!(f, "Medigap Part A"),
            Self::MedigapPartB => write!(f, "Medigap Part B"),
            Self::MedicarePrimary => write!(f, "Medicare Primary"),
            Self::Other => write!(f, "Other"),
            Self::PropertyInsurancePersonal => write!(f, "Property Insurance - Personal"),
            Self::Personal => write!(f, "Personal"),
            Self::PersonalPaymentLeftParenthesisCashNoInsuranceRightParenthesis => write!(f, "Personal Payment (Cash - No Insurance)"),
            Self::PreferredProviderOrganizationLeftParenthesisPpoRightParenthesis => write!(f, "Preferred Provider Organization (PPO)"),
            Self::PointOfServiceLeftParenthesisPosRightParenthesis => write!(f, "Point of Service (POS)"),
            Self::QualifiedMedicareBeneficiary => write!(f, "Qualified Medicare Beneficiary"),
            Self::PropertyInsuranceReal => write!(f, "Property Insurance - Real"),
            Self::SupplementalPolicy => write!(f, "Supplemental Policy"),
            Self::TaxEquityFiscalResponsibilityActLeftParenthesisTefraRightParenthesis => write!(f, "Tax Equity Fiscal Responsibility Act (TEFRA)"),
            Self::WorkersCompensation => write!(f, "Workers Compensation"),
            Self::WrapUpPolicy => write!(f, "Wrap Up Policy"),
        }
    }
}

impl Default for InsuranceTypeName {
    fn default() -> InsuranceTypeName {
        Self::MedicareSecondaryWorkingAgedBeneficiaryOrSpouseWithEmployerGroupHealthPlan
    }
}

