/*
 * Stedi Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::manager::models;
use serde::{Deserialize, Serialize};

/// ResponseEligibilityServiceTypeCode : A code identifying a type of service. Visit [Service Type Codes](https://www.stedi.com/docs/healthcare/send-eligibility-checks#service-type-codes) for a complete list.  This list is specific to X12 version 005010, which is the mandated version for eligibility checks. It differs from the current [X12 Service Type Codes](https://x12.org/codes/service-type-codes) list, which applies to X12 versions later than 005010.  Payers may sometimes return other non-compliant values.
/// A code identifying a type of service. Visit [Service Type Codes](https://www.stedi.com/docs/healthcare/send-eligibility-checks#service-type-codes) for a complete list.  This list is specific to X12 version 005010, which is the mandated version for eligibility checks. It differs from the current [X12 Service Type Codes](https://x12.org/codes/service-type-codes) list, which applies to X12 versions later than 005010.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseEligibilityServiceTypeCode {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "7")]
    Variant7,
    #[serde(rename = "8")]
    Variant8,
    #[serde(rename = "9")]
    Variant9,
    #[serde(rename = "10")]
    Variant10,
    #[serde(rename = "11")]
    Variant11,
    #[serde(rename = "12")]
    Variant12,
    #[serde(rename = "13")]
    Variant13,
    #[serde(rename = "14")]
    Variant14,
    #[serde(rename = "15")]
    Variant15,
    #[serde(rename = "16")]
    Variant16,
    #[serde(rename = "17")]
    Variant17,
    #[serde(rename = "18")]
    Variant18,
    #[serde(rename = "19")]
    Variant19,
    #[serde(rename = "20")]
    Variant20,
    #[serde(rename = "21")]
    Variant21,
    #[serde(rename = "22")]
    Variant22,
    #[serde(rename = "23")]
    Variant23,
    #[serde(rename = "24")]
    Variant24,
    #[serde(rename = "25")]
    Variant25,
    #[serde(rename = "26")]
    Variant26,
    #[serde(rename = "27")]
    Variant27,
    #[serde(rename = "28")]
    Variant28,
    #[serde(rename = "30")]
    Variant30,
    #[serde(rename = "32")]
    Variant32,
    #[serde(rename = "33")]
    Variant33,
    #[serde(rename = "34")]
    Variant34,
    #[serde(rename = "35")]
    Variant35,
    #[serde(rename = "36")]
    Variant36,
    #[serde(rename = "37")]
    Variant37,
    #[serde(rename = "38")]
    Variant38,
    #[serde(rename = "39")]
    Variant39,
    #[serde(rename = "40")]
    Variant40,
    #[serde(rename = "41")]
    Variant41,
    #[serde(rename = "42")]
    Variant42,
    #[serde(rename = "43")]
    Variant43,
    #[serde(rename = "44")]
    Variant44,
    #[serde(rename = "45")]
    Variant45,
    #[serde(rename = "46")]
    Variant46,
    #[serde(rename = "47")]
    Variant47,
    #[serde(rename = "48")]
    Variant48,
    #[serde(rename = "49")]
    Variant49,
    #[serde(rename = "50")]
    Variant50,
    #[serde(rename = "51")]
    Variant51,
    #[serde(rename = "52")]
    Variant52,
    #[serde(rename = "53")]
    Variant53,
    #[serde(rename = "54")]
    Variant54,
    #[serde(rename = "55")]
    Variant55,
    #[serde(rename = "56")]
    Variant56,
    #[serde(rename = "57")]
    Variant57,
    #[serde(rename = "58")]
    Variant58,
    #[serde(rename = "59")]
    Variant59,
    #[serde(rename = "60")]
    Variant60,
    #[serde(rename = "61")]
    Variant61,
    #[serde(rename = "62")]
    Variant62,
    #[serde(rename = "63")]
    Variant63,
    #[serde(rename = "64")]
    Variant64,
    #[serde(rename = "65")]
    Variant65,
    #[serde(rename = "66")]
    Variant66,
    #[serde(rename = "67")]
    Variant67,
    #[serde(rename = "68")]
    Variant68,
    #[serde(rename = "69")]
    Variant69,
    #[serde(rename = "70")]
    Variant70,
    #[serde(rename = "71")]
    Variant71,
    #[serde(rename = "72")]
    Variant72,
    #[serde(rename = "73")]
    Variant73,
    #[serde(rename = "74")]
    Variant74,
    #[serde(rename = "75")]
    Variant75,
    #[serde(rename = "76")]
    Variant76,
    #[serde(rename = "77")]
    Variant77,
    #[serde(rename = "78")]
    Variant78,
    #[serde(rename = "79")]
    Variant79,
    #[serde(rename = "80")]
    Variant80,
    #[serde(rename = "81")]
    Variant81,
    #[serde(rename = "82")]
    Variant82,
    #[serde(rename = "83")]
    Variant83,
    #[serde(rename = "84")]
    Variant84,
    #[serde(rename = "85")]
    Variant85,
    #[serde(rename = "86")]
    Variant86,
    #[serde(rename = "87")]
    Variant87,
    #[serde(rename = "88")]
    Variant88,
    #[serde(rename = "89")]
    Variant89,
    #[serde(rename = "90")]
    Variant90,
    #[serde(rename = "91")]
    Variant91,
    #[serde(rename = "92")]
    Variant92,
    #[serde(rename = "93")]
    Variant93,
    #[serde(rename = "94")]
    Variant94,
    #[serde(rename = "95")]
    Variant95,
    #[serde(rename = "96")]
    Variant96,
    #[serde(rename = "97")]
    Variant97,
    #[serde(rename = "98")]
    Variant98,
    #[serde(rename = "99")]
    Variant99,
    #[serde(rename = "A0")]
    A0,
    #[serde(rename = "A1")]
    A1,
    #[serde(rename = "A2")]
    A2,
    #[serde(rename = "A3")]
    A3,
    #[serde(rename = "A4")]
    A4,
    #[serde(rename = "A5")]
    A5,
    #[serde(rename = "A6")]
    A6,
    #[serde(rename = "A7")]
    A7,
    #[serde(rename = "A8")]
    A8,
    #[serde(rename = "A9")]
    A9,
    #[serde(rename = "AA")]
    Aa,
    #[serde(rename = "AB")]
    Ab,
    #[serde(rename = "AC")]
    Ac,
    #[serde(rename = "AD")]
    Ad,
    #[serde(rename = "AE")]
    Ae,
    #[serde(rename = "AF")]
    Af,
    #[serde(rename = "AG")]
    Ag,
    #[serde(rename = "AH")]
    Ah,
    #[serde(rename = "AI")]
    Ai,
    #[serde(rename = "AJ")]
    Aj,
    #[serde(rename = "AK")]
    Ak,
    #[serde(rename = "AL")]
    Al,
    #[serde(rename = "AM")]
    Am,
    #[serde(rename = "AN")]
    An,
    #[serde(rename = "AO")]
    Ao,
    #[serde(rename = "AQ")]
    Aq,
    #[serde(rename = "AR")]
    Ar,
    #[serde(rename = "B1")]
    B1,
    #[serde(rename = "B2")]
    B2,
    #[serde(rename = "B3")]
    B3,
    #[serde(rename = "BA")]
    Ba,
    #[serde(rename = "BB")]
    Bb,
    #[serde(rename = "BC")]
    Bc,
    #[serde(rename = "BD")]
    Bd,
    #[serde(rename = "BE")]
    Be,
    #[serde(rename = "BF")]
    Bf,
    #[serde(rename = "BG")]
    Bg,
    #[serde(rename = "BH")]
    Bh,
    #[serde(rename = "BI")]
    Bi,
    #[serde(rename = "BJ")]
    Bj,
    #[serde(rename = "BK")]
    Bk,
    #[serde(rename = "BL")]
    Bl,
    #[serde(rename = "BM")]
    Bm,
    #[serde(rename = "BN")]
    Bn,
    #[serde(rename = "BP")]
    Bp,
    #[serde(rename = "BQ")]
    Bq,
    #[serde(rename = "BR")]
    Br,
    #[serde(rename = "BS")]
    Bs,
    #[serde(rename = "BT")]
    Bt,
    #[serde(rename = "BU")]
    Bu,
    #[serde(rename = "BV")]
    Bv,
    #[serde(rename = "BW")]
    Bw,
    #[serde(rename = "BX")]
    Bx,
    #[serde(rename = "BY")]
    By,
    #[serde(rename = "BZ")]
    Bz,
    #[serde(rename = "C1")]
    C1,
    #[serde(rename = "CA")]
    Ca,
    #[serde(rename = "CB")]
    Cb,
    #[serde(rename = "CC")]
    Cc,
    #[serde(rename = "CD")]
    Cd,
    #[serde(rename = "CE")]
    Ce,
    #[serde(rename = "CF")]
    Cf,
    #[serde(rename = "CG")]
    Cg,
    #[serde(rename = "CH")]
    Ch,
    #[serde(rename = "CI")]
    Ci,
    #[serde(rename = "CJ")]
    Cj,
    #[serde(rename = "CK")]
    Ck,
    #[serde(rename = "CL")]
    Cl,
    #[serde(rename = "CM")]
    Cm,
    #[serde(rename = "CN")]
    Cn,
    #[serde(rename = "CO")]
    Co,
    #[serde(rename = "CP")]
    Cp,
    #[serde(rename = "CQ")]
    Cq,
    #[serde(rename = "DG")]
    Dg,
    #[serde(rename = "DM")]
    Dm,
    #[serde(rename = "DS")]
    Ds,
    #[serde(rename = "GF")]
    Gf,
    #[serde(rename = "GN")]
    Gn,
    #[serde(rename = "GY")]
    Gy,
    #[serde(rename = "IC")]
    Ic,
    #[serde(rename = "MH")]
    Mh,
    #[serde(rename = "NI")]
    Ni,
    #[serde(rename = "ON")]
    On,
    #[serde(rename = "PT")]
    Pt,
    #[serde(rename = "PU")]
    Pu,
    #[serde(rename = "RN")]
    Rn,
    #[serde(rename = "RT")]
    Rt,
    #[serde(rename = "TC")]
    Tc,
    #[serde(rename = "TN")]
    Tn,
    #[serde(rename = "UC")]
    Uc,
    #[serde(rename = "EA")]
    Ea,
    #[serde(rename = "EB")]
    Eb,
    #[serde(rename = "EC")]
    Ec,
    #[serde(rename = "ED")]
    Ed,
    #[serde(rename = "EE")]
    Ee,
    #[serde(rename = "EF")]
    Ef,
    #[serde(rename = "EG")]
    Eg,
    #[serde(rename = "EH")]
    Eh,
    #[serde(rename = "EI")]
    Ei,
    #[serde(rename = "EJ")]
    Ej,
    #[serde(rename = "EK")]
    Ek,
    #[serde(rename = "FA")]
    Fa,
    #[serde(rename = "FB")]
    Fb,
    #[serde(rename = "V3")]
    V3,
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V5")]
    V5,
    #[serde(rename = "V6")]
    V6,
    #[serde(rename = "V7")]
    V7,
    #[serde(rename = "V8")]
    V8,
    #[serde(rename = "V9")]
    V9,
    #[serde(rename = "V10")]
    V10,
    #[serde(rename = "V11")]
    V11,
    #[serde(rename = "V12")]
    V12,
    #[serde(rename = "V13")]
    V13,
    #[serde(rename = "V14")]
    V14,
    #[serde(rename = "V15")]
    V15,
    #[serde(rename = "V16")]
    V16,
    #[serde(rename = "V17")]
    V17,
    #[serde(rename = "V18")]
    V18,
    #[serde(rename = "V19")]
    V19,
    #[serde(rename = "V20")]
    V20,
    #[serde(rename = "V21")]
    V21,
    #[serde(rename = "V22")]
    V22,
    #[serde(rename = "V23")]
    V23,
    #[serde(rename = "V24")]
    V24,
    #[serde(rename = "V25")]
    V25,
    #[serde(rename = "V26")]
    V26,
    #[serde(rename = "V27")]
    V27,
    #[serde(rename = "V28")]
    V28,
    #[serde(rename = "V29")]
    V29,
    #[serde(rename = "V30")]
    V30,
    #[serde(rename = "V31")]
    V31,
    #[serde(rename = "V32")]
    V32,
    #[serde(rename = "V33")]
    V33,
    #[serde(rename = "V34")]
    V34,
    #[serde(rename = "V35")]
    V35,
    #[serde(rename = "V36")]
    V36,
    #[serde(rename = "V37")]
    V37,
    #[serde(rename = "V38")]
    V38,
    #[serde(rename = "V39")]
    V39,
    #[serde(rename = "V40")]
    V40,
    #[serde(rename = "V41")]
    V41,
    #[serde(rename = "V42")]
    V42,
    #[serde(rename = "V43")]
    V43,
    #[serde(rename = "V44")]
    V44,
    #[serde(rename = "V45")]
    V45,

}

impl std::fmt::Display for ResponseEligibilityServiceTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1 => write!(f, "1"),
            Self::Variant2 => write!(f, "2"),
            Self::Variant3 => write!(f, "3"),
            Self::Variant4 => write!(f, "4"),
            Self::Variant5 => write!(f, "5"),
            Self::Variant6 => write!(f, "6"),
            Self::Variant7 => write!(f, "7"),
            Self::Variant8 => write!(f, "8"),
            Self::Variant9 => write!(f, "9"),
            Self::Variant10 => write!(f, "10"),
            Self::Variant11 => write!(f, "11"),
            Self::Variant12 => write!(f, "12"),
            Self::Variant13 => write!(f, "13"),
            Self::Variant14 => write!(f, "14"),
            Self::Variant15 => write!(f, "15"),
            Self::Variant16 => write!(f, "16"),
            Self::Variant17 => write!(f, "17"),
            Self::Variant18 => write!(f, "18"),
            Self::Variant19 => write!(f, "19"),
            Self::Variant20 => write!(f, "20"),
            Self::Variant21 => write!(f, "21"),
            Self::Variant22 => write!(f, "22"),
            Self::Variant23 => write!(f, "23"),
            Self::Variant24 => write!(f, "24"),
            Self::Variant25 => write!(f, "25"),
            Self::Variant26 => write!(f, "26"),
            Self::Variant27 => write!(f, "27"),
            Self::Variant28 => write!(f, "28"),
            Self::Variant30 => write!(f, "30"),
            Self::Variant32 => write!(f, "32"),
            Self::Variant33 => write!(f, "33"),
            Self::Variant34 => write!(f, "34"),
            Self::Variant35 => write!(f, "35"),
            Self::Variant36 => write!(f, "36"),
            Self::Variant37 => write!(f, "37"),
            Self::Variant38 => write!(f, "38"),
            Self::Variant39 => write!(f, "39"),
            Self::Variant40 => write!(f, "40"),
            Self::Variant41 => write!(f, "41"),
            Self::Variant42 => write!(f, "42"),
            Self::Variant43 => write!(f, "43"),
            Self::Variant44 => write!(f, "44"),
            Self::Variant45 => write!(f, "45"),
            Self::Variant46 => write!(f, "46"),
            Self::Variant47 => write!(f, "47"),
            Self::Variant48 => write!(f, "48"),
            Self::Variant49 => write!(f, "49"),
            Self::Variant50 => write!(f, "50"),
            Self::Variant51 => write!(f, "51"),
            Self::Variant52 => write!(f, "52"),
            Self::Variant53 => write!(f, "53"),
            Self::Variant54 => write!(f, "54"),
            Self::Variant55 => write!(f, "55"),
            Self::Variant56 => write!(f, "56"),
            Self::Variant57 => write!(f, "57"),
            Self::Variant58 => write!(f, "58"),
            Self::Variant59 => write!(f, "59"),
            Self::Variant60 => write!(f, "60"),
            Self::Variant61 => write!(f, "61"),
            Self::Variant62 => write!(f, "62"),
            Self::Variant63 => write!(f, "63"),
            Self::Variant64 => write!(f, "64"),
            Self::Variant65 => write!(f, "65"),
            Self::Variant66 => write!(f, "66"),
            Self::Variant67 => write!(f, "67"),
            Self::Variant68 => write!(f, "68"),
            Self::Variant69 => write!(f, "69"),
            Self::Variant70 => write!(f, "70"),
            Self::Variant71 => write!(f, "71"),
            Self::Variant72 => write!(f, "72"),
            Self::Variant73 => write!(f, "73"),
            Self::Variant74 => write!(f, "74"),
            Self::Variant75 => write!(f, "75"),
            Self::Variant76 => write!(f, "76"),
            Self::Variant77 => write!(f, "77"),
            Self::Variant78 => write!(f, "78"),
            Self::Variant79 => write!(f, "79"),
            Self::Variant80 => write!(f, "80"),
            Self::Variant81 => write!(f, "81"),
            Self::Variant82 => write!(f, "82"),
            Self::Variant83 => write!(f, "83"),
            Self::Variant84 => write!(f, "84"),
            Self::Variant85 => write!(f, "85"),
            Self::Variant86 => write!(f, "86"),
            Self::Variant87 => write!(f, "87"),
            Self::Variant88 => write!(f, "88"),
            Self::Variant89 => write!(f, "89"),
            Self::Variant90 => write!(f, "90"),
            Self::Variant91 => write!(f, "91"),
            Self::Variant92 => write!(f, "92"),
            Self::Variant93 => write!(f, "93"),
            Self::Variant94 => write!(f, "94"),
            Self::Variant95 => write!(f, "95"),
            Self::Variant96 => write!(f, "96"),
            Self::Variant97 => write!(f, "97"),
            Self::Variant98 => write!(f, "98"),
            Self::Variant99 => write!(f, "99"),
            Self::A0 => write!(f, "A0"),
            Self::A1 => write!(f, "A1"),
            Self::A2 => write!(f, "A2"),
            Self::A3 => write!(f, "A3"),
            Self::A4 => write!(f, "A4"),
            Self::A5 => write!(f, "A5"),
            Self::A6 => write!(f, "A6"),
            Self::A7 => write!(f, "A7"),
            Self::A8 => write!(f, "A8"),
            Self::A9 => write!(f, "A9"),
            Self::Aa => write!(f, "AA"),
            Self::Ab => write!(f, "AB"),
            Self::Ac => write!(f, "AC"),
            Self::Ad => write!(f, "AD"),
            Self::Ae => write!(f, "AE"),
            Self::Af => write!(f, "AF"),
            Self::Ag => write!(f, "AG"),
            Self::Ah => write!(f, "AH"),
            Self::Ai => write!(f, "AI"),
            Self::Aj => write!(f, "AJ"),
            Self::Ak => write!(f, "AK"),
            Self::Al => write!(f, "AL"),
            Self::Am => write!(f, "AM"),
            Self::An => write!(f, "AN"),
            Self::Ao => write!(f, "AO"),
            Self::Aq => write!(f, "AQ"),
            Self::Ar => write!(f, "AR"),
            Self::B1 => write!(f, "B1"),
            Self::B2 => write!(f, "B2"),
            Self::B3 => write!(f, "B3"),
            Self::Ba => write!(f, "BA"),
            Self::Bb => write!(f, "BB"),
            Self::Bc => write!(f, "BC"),
            Self::Bd => write!(f, "BD"),
            Self::Be => write!(f, "BE"),
            Self::Bf => write!(f, "BF"),
            Self::Bg => write!(f, "BG"),
            Self::Bh => write!(f, "BH"),
            Self::Bi => write!(f, "BI"),
            Self::Bj => write!(f, "BJ"),
            Self::Bk => write!(f, "BK"),
            Self::Bl => write!(f, "BL"),
            Self::Bm => write!(f, "BM"),
            Self::Bn => write!(f, "BN"),
            Self::Bp => write!(f, "BP"),
            Self::Bq => write!(f, "BQ"),
            Self::Br => write!(f, "BR"),
            Self::Bs => write!(f, "BS"),
            Self::Bt => write!(f, "BT"),
            Self::Bu => write!(f, "BU"),
            Self::Bv => write!(f, "BV"),
            Self::Bw => write!(f, "BW"),
            Self::Bx => write!(f, "BX"),
            Self::By => write!(f, "BY"),
            Self::Bz => write!(f, "BZ"),
            Self::C1 => write!(f, "C1"),
            Self::Ca => write!(f, "CA"),
            Self::Cb => write!(f, "CB"),
            Self::Cc => write!(f, "CC"),
            Self::Cd => write!(f, "CD"),
            Self::Ce => write!(f, "CE"),
            Self::Cf => write!(f, "CF"),
            Self::Cg => write!(f, "CG"),
            Self::Ch => write!(f, "CH"),
            Self::Ci => write!(f, "CI"),
            Self::Cj => write!(f, "CJ"),
            Self::Ck => write!(f, "CK"),
            Self::Cl => write!(f, "CL"),
            Self::Cm => write!(f, "CM"),
            Self::Cn => write!(f, "CN"),
            Self::Co => write!(f, "CO"),
            Self::Cp => write!(f, "CP"),
            Self::Cq => write!(f, "CQ"),
            Self::Dg => write!(f, "DG"),
            Self::Dm => write!(f, "DM"),
            Self::Ds => write!(f, "DS"),
            Self::Gf => write!(f, "GF"),
            Self::Gn => write!(f, "GN"),
            Self::Gy => write!(f, "GY"),
            Self::Ic => write!(f, "IC"),
            Self::Mh => write!(f, "MH"),
            Self::Ni => write!(f, "NI"),
            Self::On => write!(f, "ON"),
            Self::Pt => write!(f, "PT"),
            Self::Pu => write!(f, "PU"),
            Self::Rn => write!(f, "RN"),
            Self::Rt => write!(f, "RT"),
            Self::Tc => write!(f, "TC"),
            Self::Tn => write!(f, "TN"),
            Self::Uc => write!(f, "UC"),
            Self::Ea => write!(f, "EA"),
            Self::Eb => write!(f, "EB"),
            Self::Ec => write!(f, "EC"),
            Self::Ed => write!(f, "ED"),
            Self::Ee => write!(f, "EE"),
            Self::Ef => write!(f, "EF"),
            Self::Eg => write!(f, "EG"),
            Self::Eh => write!(f, "EH"),
            Self::Ei => write!(f, "EI"),
            Self::Ej => write!(f, "EJ"),
            Self::Ek => write!(f, "EK"),
            Self::Fa => write!(f, "FA"),
            Self::Fb => write!(f, "FB"),
            Self::V3 => write!(f, "V3"),
            Self::V4 => write!(f, "V4"),
            Self::V5 => write!(f, "V5"),
            Self::V6 => write!(f, "V6"),
            Self::V7 => write!(f, "V7"),
            Self::V8 => write!(f, "V8"),
            Self::V9 => write!(f, "V9"),
            Self::V10 => write!(f, "V10"),
            Self::V11 => write!(f, "V11"),
            Self::V12 => write!(f, "V12"),
            Self::V13 => write!(f, "V13"),
            Self::V14 => write!(f, "V14"),
            Self::V15 => write!(f, "V15"),
            Self::V16 => write!(f, "V16"),
            Self::V17 => write!(f, "V17"),
            Self::V18 => write!(f, "V18"),
            Self::V19 => write!(f, "V19"),
            Self::V20 => write!(f, "V20"),
            Self::V21 => write!(f, "V21"),
            Self::V22 => write!(f, "V22"),
            Self::V23 => write!(f, "V23"),
            Self::V24 => write!(f, "V24"),
            Self::V25 => write!(f, "V25"),
            Self::V26 => write!(f, "V26"),
            Self::V27 => write!(f, "V27"),
            Self::V28 => write!(f, "V28"),
            Self::V29 => write!(f, "V29"),
            Self::V30 => write!(f, "V30"),
            Self::V31 => write!(f, "V31"),
            Self::V32 => write!(f, "V32"),
            Self::V33 => write!(f, "V33"),
            Self::V34 => write!(f, "V34"),
            Self::V35 => write!(f, "V35"),
            Self::V36 => write!(f, "V36"),
            Self::V37 => write!(f, "V37"),
            Self::V38 => write!(f, "V38"),
            Self::V39 => write!(f, "V39"),
            Self::V40 => write!(f, "V40"),
            Self::V41 => write!(f, "V41"),
            Self::V42 => write!(f, "V42"),
            Self::V43 => write!(f, "V43"),
            Self::V44 => write!(f, "V44"),
            Self::V45 => write!(f, "V45"),
        }
    }
}

impl Default for ResponseEligibilityServiceTypeCode {
    fn default() -> ResponseEligibilityServiceTypeCode {
        Self::Variant1
    }
}

