/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::healthcare::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`claim_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClaimStatusError {
    Status400(models::ValidationExceptionResponseContent),
    Status403(models::AccessDeniedExceptionResponseContent),
    Status404(models::ResourceNotFoundExceptionResponseContent),
    Status429(models::ThrottlingExceptionResponseContent),
    Status500(models::InternalFailureExceptionResponseContent),
    Status503(models::ServiceUnavailableExceptionResponseContent),
    Status504(models::GatewayTimeoutExceptionResponseContent),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`claim_status_raw_x12`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ClaimStatusRawX12Error {
    Status400(models::ValidationExceptionResponseContent),
    Status403(models::AccessDeniedExceptionResponseContent),
    Status404(models::ResourceNotFoundExceptionResponseContent),
    Status429(models::ThrottlingExceptionResponseContent),
    Status500(models::InternalFailureExceptionResponseContent),
    Status503(models::ServiceUnavailableExceptionResponseContent),
    Status504(models::GatewayTimeoutExceptionResponseContent),
    UnknownValue(serde_json::Value),
}


/// Submit a 276/277 real-time claim status check in JSON format
pub async fn claim_status(configuration: &configuration::Configuration, claim_status_request_content: models::ClaimStatusRequestContent) -> Result<models::ClaimStatusResponseContent, Error<ClaimStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_claim_status_request_content = claim_status_request_content;

    let uri_str = format!("{}/change/medicalnetwork/claimstatus/v2", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_claim_status_request_content);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClaimStatusResponseContent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClaimStatusResponseContent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClaimStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Submit a 276/277 real-time claim status check in raw X12 EDI format
pub async fn claim_status_raw_x12(configuration: &configuration::Configuration, claim_status_raw_x12_request_content: models::ClaimStatusRawX12RequestContent) -> Result<models::ClaimStatusRawX12ResponseContent, Error<ClaimStatusRawX12Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_claim_status_raw_x12_request_content = claim_status_raw_x12_request_content;

    let uri_str = format!("{}/change/medicalnetwork/claimstatus/v2/raw-x12", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };
    req_builder = req_builder.json(&p_body_claim_status_raw_x12_request_content);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ClaimStatusRawX12ResponseContent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ClaimStatusRawX12ResponseContent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ClaimStatusRawX12Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

