/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::healthcare::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`convert_report835`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConvertReport835Error {
    Status400(models::ValidationExceptionResponseContent),
    Status403(models::AccessDeniedExceptionResponseContent),
    Status404(models::ResourceNotFoundExceptionResponseContent),
    Status429(models::ThrottlingExceptionResponseContent),
    Status500(models::InternalFailureExceptionResponseContent),
    Status503(models::ServiceUnavailableExceptionResponseContent),
    Status504(models::GatewayTimeoutExceptionResponseContent),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_electronic_remittance_advice_pdf`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetElectronicRemittanceAdvicePdfError {
    Status400(models::ValidationExceptionResponseContent),
    Status403(models::AccessDeniedExceptionResponseContent),
    Status404(models::ResourceNotFoundExceptionResponseContent),
    Status429(models::ThrottlingExceptionResponseContent),
    Status500(models::InternalFailureExceptionResponseContent),
    Status503(models::ServiceUnavailableExceptionResponseContent),
    Status504(models::GatewayTimeoutExceptionResponseContent),
    UnknownValue(serde_json::Value),
}


/// Retrieve an 835 Electronic Remittance Advice (ERA) in JSON format
pub async fn convert_report835(configuration: &configuration::Configuration, transaction_id: &str) -> Result<models::ConvertReport835ResponseContent, Error<ConvertReport835Error>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_transaction_id = transaction_id;

    let uri_str = format!("{}/change/medicalnetwork/reports/v2/{transactionId}/835", configuration.base_path, transactionId=crate::healthcare::apis::urlencode(p_transaction_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConvertReport835ResponseContent`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ConvertReport835ResponseContent`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ConvertReport835Error> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Retrieve the generated PDF of an 835 Electronic Remittance Advice (ERA).
pub async fn get_electronic_remittance_advice_pdf(configuration: &configuration::Configuration, transaction_id: &str, logo: Option<bool>) -> Result<String, Error<GetElectronicRemittanceAdvicePdfError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_transaction_id = transaction_id;
    let p_logo = logo;

    let uri_str = format!("{}/electronic-remittance-advice/{transactionId}/pdf", configuration.base_path, transactionId=crate::healthcare::apis::urlencode(p_transaction_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_logo {
        req_builder = req_builder.query(&[("logo", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    if let Some(ref apikey) = configuration.api_key {
        let key = apikey.key.clone();
        let value = match apikey.prefix {
            Some(ref prefix) => format!("{} {}", prefix, key),
            None => key,
        };
        req_builder = req_builder.header("Authorization", value);
    };

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `String`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `String`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<GetElectronicRemittanceAdvicePdfError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

