/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// CreateEnrollmentDocumentUploadRequestContent : Input for CreateDocumentUpload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEnrollmentDocumentUploadRequestContent {
    /// The file name of the PDF document you want to upload. The name should include the file extension, such as `provider-license.pdf`. This name will be displayed in the Stedi portal.
    #[serde(rename = "name")]
    pub name: String,
    /// The ID for the task associated with this document upload.
    #[serde(rename = "taskId")]
    pub task_id: String,
}

impl CreateEnrollmentDocumentUploadRequestContent {
    /// Input for CreateDocumentUpload.
    pub fn new(name: String, task_id: String) -> CreateEnrollmentDocumentUploadRequestContent {
        CreateEnrollmentDocumentUploadRequestContent {
            name,
            task_id,
        }
    }
}

