/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// CreateEnrollmentDocumentDownloadResponseContent : Response containing the document ID and pre-signed URL for download.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEnrollmentDocumentDownloadResponseContent {
    /// The document ID for the PDF document associated with the `downloadUrl`.
    #[serde(rename = "documentId")]
    pub document_id: String,
    /// The pre-signed URL to download the document.
    #[serde(rename = "downloadUrl")]
    pub download_url: String,
}

impl CreateEnrollmentDocumentDownloadResponseContent {
    /// Response containing the document ID and pre-signed URL for download.
    pub fn new(document_id: String, download_url: String) -> CreateEnrollmentDocumentDownloadResponseContent {
        CreateEnrollmentDocumentDownloadResponseContent {
            document_id,
            download_url,
        }
    }
}

