/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// DocumentStatus : Indicates whether the document file has been successfully uploaded to Stedi.
/// Indicates whether the document file has been successfully uploaded to Stedi.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DocumentStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "UPLOADED")]
    Uploaded,
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "DELETED")]
    Deleted,

}

impl std::fmt::Display for DocumentStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "PENDING"),
            Self::Uploaded => write!(f, "UPLOADED"),
            Self::Failed => write!(f, "FAILED"),
            Self::Deleted => write!(f, "DELETED"),
        }
    }
}

impl Default for DocumentStatus {
    fn default() -> DocumentStatus {
        Self::Pending
    }
}

