/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// EnrolledPayerOutput : Output structure containing payer information in enrollment responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrolledPayerOutput {
    /// The payer's name, such as `Cigna` or `UnitedHealthcare`.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The unique Stedi assigned identifier for the payer.
    #[serde(rename = "stediPayerId")]
    pub stedi_payer_id: String,
    /// The payer ID or alias used when creating the enrollment request. For example, `62308` and `CIGNA` are both supported for Cigna. You can find a list of all supported payer IDs and aliases in the [Payer Network](https://www.stedi.com/healthcare/network).
    #[serde(rename = "submittedPayerIdOrAlias", skip_serializing_if = "Option::is_none")]
    pub submitted_payer_id_or_alias: Option<String>,
}

impl EnrolledPayerOutput {
    /// Output structure containing payer information in enrollment responses.
    pub fn new(stedi_payer_id: String) -> EnrolledPayerOutput {
        EnrolledPayerOutput {
            name: None,
            stedi_payer_id,
            submitted_payer_id_or_alias: None,
        }
    }
}

