/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// EnrollmentDocument : A collection of metadata about an enrollment document, including its name, status, last updated date, and the associated enrollment Id.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnrollmentDocument {
    /// The content type of the document.
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// The date and time when the document was created.
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// The enrollment ID this document is associated with.
    #[serde(rename = "enrollmentId")]
    pub enrollment_id: String,
    /// The unique identifier for the document.
    #[serde(rename = "id")]
    pub id: String,
    /// The name of the document.
    #[serde(rename = "name")]
    pub name: String,
    /// The size of the document in bytes.
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<f64>,
    /// Indicates whether the document file has been successfully uploaded to Stedi.
    #[serde(rename = "status")]
    pub status: models::DocumentStatus,
    /// The task ID associated with this document, if it was created or processed as part of a task.
    #[serde(rename = "taskId", skip_serializing_if = "Option::is_none")]
    pub task_id: Option<String>,
    /// The date and time when the document was last updated.
    #[serde(rename = "updatedAt")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl EnrollmentDocument {
    /// A collection of metadata about an enrollment document, including its name, status, last updated date, and the associated enrollment Id.
    pub fn new(created_at: chrono::DateTime<chrono::FixedOffset>, enrollment_id: String, id: String, name: String, status: models::DocumentStatus, updated_at: chrono::DateTime<chrono::FixedOffset>) -> EnrollmentDocument {
        EnrollmentDocument {
            content_type: None,
            created_at,
            enrollment_id,
            id,
            name,
            size: None,
            status,
            task_id: None,
            updated_at,
        }
    }
}

