/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowInstructions {
    /// This task type will be deprecated on July 20, 2026 and later removed. Use `manualTask` instead.  A task that requires the responsible party to follow specific instructions.
    #[serde(rename = "followInstructions")]
    pub follow_instructions: Box<models::FollowInstructionsTask>,
}

impl FollowInstructions {
    pub fn new(follow_instructions: models::FollowInstructionsTask) -> FollowInstructions {
        FollowInstructions {
            follow_instructions: Box::new(follow_instructions),
        }
    }
}

