/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// ListEnrollmentsResponseContent : Output containing a paginated list of enrollments.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListEnrollmentsResponseContent {
    /// Details about the enrollments matching the search criteria.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::EnrollmentSummary>>,
    /// Token that you can supply in subsequent requests to retrieve the next page of results. If not returned, there are no more results.
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    /// The total count of enrollments matching the filter criteria, regardless of pagination.
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<f64>,
}

impl ListEnrollmentsResponseContent {
    /// Output containing a paginated list of enrollments.
    pub fn new() -> ListEnrollmentsResponseContent {
        ListEnrollmentsResponseContent {
            items: None,
            next_page_token: None,
            total_count: None,
        }
    }
}

