/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// ManualTaskResponseKeyValue : A single key/value pair collected for a `ManualTaskField`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualTaskResponseKeyValue {
    /// Identifier that matches a field `key` in the task definition.
    #[serde(rename = "key")]
    pub key: String,
    /// Information to complete the field. It must match the field's `fieldType`. For example, this might be the provider's Medicaid ID when the `fieldType` is `TEXT`.
    #[serde(rename = "value")]
    pub value: Box<models::ManualTaskResponseValue>,
}

impl ManualTaskResponseKeyValue {
    /// A single key/value pair collected for a `ManualTaskField`.
    pub fn new(key: String, value: models::ManualTaskResponseValue) -> ManualTaskResponseKeyValue {
        ManualTaskResponseKeyValue {
            key,
            value: Box::new(value),
        }
    }
}

