/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// ManualTaskResponse : Values provided to complete a manual task. Visit [Manage enrollment tasks](https://www.stedi.com/docs/healthcare/transaction-enrollment-tasks-documents#api) for details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualTaskResponse {
    /// Values for each field in the task definition. Each value's `key` must have a corresponding field `key`. The response must include one value for every field.
    #[serde(rename = "values")]
    pub values: Vec<models::ManualTaskResponseKeyValue>,
}

impl ManualTaskResponse {
    /// Values provided to complete a manual task. Visit [Manage enrollment tasks](https://www.stedi.com/docs/healthcare/transaction-enrollment-tasks-documents#api) for details.
    pub fn new(values: Vec<models::ManualTaskResponseKeyValue>) -> ManualTaskResponse {
        ManualTaskResponse {
            values,
        }
    }
}

