/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualTask1 {
    /// Values provided to complete a manual task. Visit [Manage enrollment tasks](https://www.stedi.com/docs/healthcare/transaction-enrollment-tasks-documents#api) for details.
    #[serde(rename = "manualTask")]
    pub manual_task: Box<models::ManualTaskResponse>,
}

impl ManualTask1 {
    pub fn new(manual_task: models::ManualTaskResponse) -> ManualTask1 {
        ManualTask1 {
            manual_task: Box::new(manual_task),
        }
    }
}

