/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PdfUpload {
    /// Add details from a PDF that has been uploaded to complete a `provideFilledPdf` task. Required when completing a task where `task.definition.provideFilledPdf` is present.
    #[serde(rename = "pdfUpload")]
    pub pdf_upload: Box<models::PdfUploadResponse>,
}

impl PdfUpload {
    pub fn new(pdf_upload: models::PdfUploadResponse) -> PdfUpload {
        PdfUpload {
            pdf_upload: Box::new(pdf_upload),
        }
    }
}

