/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// TransactionType : Types of healthcare transactions supported for enrollment.
/// Types of healthcare transactions supported for enrollment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransactionType {
    #[serde(rename = "claimStatus")]
    ClaimStatus,
    #[serde(rename = "eligibilityCheck")]
    EligibilityCheck,
    #[serde(rename = "institutionalClaimSubmission")]
    InstitutionalClaimSubmission,
    #[serde(rename = "professionalClaimSubmission")]
    ProfessionalClaimSubmission,
    #[serde(rename = "dentalClaimSubmission")]
    DentalClaimSubmission,
    #[serde(rename = "claimPayment")]
    ClaimPayment,
    #[serde(rename = "solicitedClaimAttachment")]
    SolicitedClaimAttachment,
    #[serde(rename = "unsolicitedClaimAttachment")]
    UnsolicitedClaimAttachment,

}

impl std::fmt::Display for TransactionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ClaimStatus => write!(f, "claimStatus"),
            Self::EligibilityCheck => write!(f, "eligibilityCheck"),
            Self::InstitutionalClaimSubmission => write!(f, "institutionalClaimSubmission"),
            Self::ProfessionalClaimSubmission => write!(f, "professionalClaimSubmission"),
            Self::DentalClaimSubmission => write!(f, "dentalClaimSubmission"),
            Self::ClaimPayment => write!(f, "claimPayment"),
            Self::SolicitedClaimAttachment => write!(f, "solicitedClaimAttachment"),
            Self::UnsolicitedClaimAttachment => write!(f, "unsolicitedClaimAttachment"),
        }
    }
}

impl Default for TransactionType {
    fn default() -> TransactionType {
        Self::ClaimStatus
    }
}

