/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// UnauthorizedExceptionResponseContent : The server response when the authorizer failed to authenticate the caller.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnauthorizedExceptionResponseContent {
    /// Error classification code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
}

impl UnauthorizedExceptionResponseContent {
    /// The server response when the authorizer failed to authenticate the caller.
    pub fn new(message: String) -> UnauthorizedExceptionResponseContent {
        UnauthorizedExceptionResponseContent {
            code: None,
            message,
        }
    }
}

