/*
 * Stedi Enrollment
 *
 * The Stedi Enrollment Service manages provider enrollments with healthcare payers. It tracks enrollment status, provider details, and supports batch enrollment processing to ensure providers have the necessary credentials before processing healthcare transactions. 
 *
 * The version of the OpenAPI document: 2024-09-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::enrollment::models;
use serde::{Deserialize, Serialize};

/// ValidationExceptionResponseContent : A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationExceptionResponseContent {
    /// A list of specific failures encountered while validating the input. A member can appear in this list more than once if it failed to satisfy multiple constraints.
    #[serde(rename = "fieldList", skip_serializing_if = "Option::is_none")]
    pub field_list: Option<Vec<models::ValidationExceptionField>>,
    /// A summary of the validation failure.
    #[serde(rename = "message")]
    pub message: String,
}

impl ValidationExceptionResponseContent {
    /// A standard error for input validation failures. This should be thrown by services when a member of the input structure falls outside of the modeled or documented constraints.
    pub fn new(message: String) -> ValidationExceptionResponseContent {
        ValidationExceptionResponseContent {
            field_list: None,
            message,
        }
    }
}

