/*
 * Stedi Payers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::payers::models;
use serde::{Deserialize, Serialize};

/// CoverageType : The types of insurance coverage that a payer can provide. Used to indicate whether a payer supports transactions for medical coverage, dental coverage, vision coverage, or a combination of these.
/// The types of insurance coverage that a payer can provide. Used to indicate whether a payer supports transactions for medical coverage, dental coverage, vision coverage, or a combination of these.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoverageType {
    #[serde(rename = "medical")]
    Medical,
    #[serde(rename = "dental")]
    Dental,
    #[serde(rename = "vision")]
    Vision,

}

impl std::fmt::Display for CoverageType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Medical => write!(f, "medical"),
            Self::Dental => write!(f, "dental"),
            Self::Vision => write!(f, "vision"),
        }
    }
}

impl Default for CoverageType {
    fn default() -> CoverageType {
        Self::Medical
    }
}

