/*
 * Stedi Payers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::payers::models;
use serde::{Deserialize, Serialize};

/// PayerUrls : URLs associated with a payer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayerUrls {
    /// The payer's website URL.
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
}

impl PayerUrls {
    /// URLs associated with a payer.
    pub fn new() -> PayerUrls {
        PayerUrls {
            website: None,
        }
    }
}

