/*
 * Stedi Payers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::payers::models;
use serde::{Deserialize, Serialize};

/// RequestedEffectiveDate : Whether a payer supports specifying a requested effective date for transaction enrollments.
/// Whether a payer supports specifying a requested effective date for transaction enrollments.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestedEffectiveDate {
    #[serde(rename = "SUPPORTED")]
    Supported,
    #[serde(rename = "NOT_SUPPORTED")]
    NotSupported,

}

impl std::fmt::Display for RequestedEffectiveDate {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Supported => write!(f, "SUPPORTED"),
            Self::NotSupported => write!(f, "NOT_SUPPORTED"),
        }
    }
}

impl Default for RequestedEffectiveDate {
    fn default() -> RequestedEffectiveDate {
        Self::Supported
    }
}

