/*
 * Stedi Payers
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::payers::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSupportStats {
    /// Number of matching payers that support 835 Electronic Remittance Advices (ERAs).
    #[serde(rename = "claimPayment")]
    pub claim_payment: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 276/277 real-time claim status.
    #[serde(rename = "claimStatus")]
    pub claim_status: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 270/271 coordination of benefits (COB) checks.
    #[serde(rename = "coordinationOfBenefits")]
    pub coordination_of_benefits: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 837D dental claims.
    #[serde(rename = "dentalClaimSubmission")]
    pub dental_claim_submission: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 270/271 eligibility checks.
    #[serde(rename = "eligibilityCheck")]
    pub eligibility_check: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 837I institutional claims.
    #[serde(rename = "institutionalClaimSubmission")]
    pub institutional_claim_submission: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 837P professional claims.
    #[serde(rename = "professionalClaimSubmission")]
    pub professional_claim_submission: Box<models::TransactionSupportStatsItem>,
    /// Number of matching payers that support 275 unsolicited claim attachments.
    #[serde(rename = "unsolicitedClaimAttachment")]
    pub unsolicited_claim_attachment: Box<models::TransactionSupportStatsItem>,
}

impl TransactionSupportStats {
    pub fn new(claim_payment: models::TransactionSupportStatsItem, claim_status: models::TransactionSupportStatsItem, coordination_of_benefits: models::TransactionSupportStatsItem, dental_claim_submission: models::TransactionSupportStatsItem, eligibility_check: models::TransactionSupportStatsItem, institutional_claim_submission: models::TransactionSupportStatsItem, professional_claim_submission: models::TransactionSupportStatsItem, unsolicited_claim_attachment: models::TransactionSupportStatsItem) -> TransactionSupportStats {
        TransactionSupportStats {
            claim_payment: Box::new(claim_payment),
            claim_status: Box::new(claim_status),
            coordination_of_benefits: Box::new(coordination_of_benefits),
            dental_claim_submission: Box::new(dental_claim_submission),
            eligibility_check: Box::new(eligibility_check),
            institutional_claim_submission: Box::new(institutional_claim_submission),
            professional_claim_submission: Box::new(professional_claim_submission),
            unsolicited_claim_attachment: Box::new(unsolicited_claim_attachment),
        }
    }
}

