/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdditionalInformation {
    /// Additional information that helps explain the claim, such as a special billing situation or extra context. Don't use this to describe unspecified procedure codes.
    #[serde(rename = "additionalInformation")]
    pub additional_information: String,
}

impl AdditionalInformation {
    pub fn new(additional_information: String) -> AdditionalInformation {
        AdditionalInformation {
            additional_information,
        }
    }
}

