/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ClaimStatusReportedBy : The entity that reported a claim status.   - `PAYER`: The payer reported the status, in a 277CA claim acknowledgment or an 835 ERA.   - `CLEARINGHOUSE`: A clearinghouse reported the status, either Stedi or an intermediary clearinghouse between Stedi and the payer.
/// The entity that reported a claim status.   - `PAYER`: The payer reported the status, in a 277CA claim acknowledgment or an 835 ERA.   - `CLEARINGHOUSE`: A clearinghouse reported the status, either Stedi or an intermediary clearinghouse between Stedi and the payer.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClaimStatusReportedBy {
    #[serde(rename = "PAYER")]
    Payer,
    #[serde(rename = "CLEARINGHOUSE")]
    Clearinghouse,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for ClaimStatusReportedBy {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Payer => write!(f, "PAYER"),
            Self::Clearinghouse => write!(f, "CLEARINGHOUSE"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for ClaimStatusReportedBy {
    fn default() -> ClaimStatusReportedBy {
        Self::Payer
    }
}

