/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ContentType : Allowed content types for claim attachments.
/// Allowed content types for claim attachments.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentType {
    #[serde(rename = "application/pdf")]
    ApplicationSlashPdf,
    #[serde(rename = "image/tiff")]
    ImageSlashTiff,
    #[serde(rename = "image/jpeg")]
    ImageSlashJpeg,
    #[serde(rename = "image/jpg")]
    ImageSlashJpg,
    #[serde(rename = "image/png")]
    ImageSlashPng,

}

impl std::fmt::Display for ContentType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApplicationSlashPdf => write!(f, "application/pdf"),
            Self::ImageSlashTiff => write!(f, "image/tiff"),
            Self::ImageSlashJpeg => write!(f, "image/jpeg"),
            Self::ImageSlashJpg => write!(f, "image/jpg"),
            Self::ImageSlashPng => write!(f, "image/png"),
        }
    }
}

impl Default for ContentType {
    fn default() -> ContentType {
        Self::ApplicationSlashPdf
    }
}

