/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// CreateClaimAttachmentFileRequestContent : Request a pre-signed URL to upload a claim attachment file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateClaimAttachmentFileRequestContent {
    /// The MIME type of the attachment file. For example: `image/png` or `application/pdf`.
    #[serde(rename = "contentType")]
    pub content_type: models::ContentType,
}

impl CreateClaimAttachmentFileRequestContent {
    /// Request a pre-signed URL to upload a claim attachment file.
    pub fn new(content_type: models::ContentType) -> CreateClaimAttachmentFileRequestContent {
        CreateClaimAttachmentFileRequestContent {
            content_type,
        }
    }
}

