/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosisDescription {
    /// A description of the diagnosis, usually provided to clarify an unspecified or unlisted procedure code.
    #[serde(rename = "diagnosisDescription")]
    pub diagnosis_description: String,
}

impl DiagnosisDescription {
    pub fn new(diagnosis_description: String) -> DiagnosisDescription {
        DiagnosisDescription {
            diagnosis_description,
        }
    }
}

