/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ForbiddenException : The caller is authenticated but lacks permission for this resource or action.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForbiddenException {
    /// Why the request failed. The wording can change, so branch on the exception type, not this text.
    #[serde(rename = "message")]
    pub message: String,
}

impl ForbiddenException {
    /// The caller is authenticated but lacks permission for this resource or action.
    pub fn new(message: String) -> ForbiddenException {
        ForbiddenException {
            message,
        }
    }
}

