/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionDateRange : A date range. `end` is inclusive. At least one of `start` or `end` is present.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionDateRange {
    /// The end date of the range, inclusive, in `YYYY-MM-DD` format.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    /// The start date of the range, in `YYYY-MM-DD` format.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
}

impl ProfessionalClaimSubmissionDateRange {
    /// A date range. `end` is inclusive. At least one of `start` or `end` is present.
    pub fn new() -> ProfessionalClaimSubmissionDateRange {
        ProfessionalClaimSubmissionDateRange {
            end: None,
            start: None,
        }
    }
}

