/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionPayer : The payer being billed for the claim.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionPayer {
    /// **[CMS-1500 Carrier Block]** The payer's mailing address.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::ProfessionalClaimSubmissionAddress>>,
    /// **[CMS-1500 Carrier Block]** The Stedi payer ID for the payer being billed. Visit the [Payer Network](https://www.stedi.com/healthcare/network) for a complete list.  - You can send requests using the primary payer ID, the Stedi payer ID, or any alias listed in the payer record.  - You must include leading 0 characters. Payer IDs are alphanumeric strings and must be treated as complete strings, not integers. For example, use `00540` for SISCO, not `540`.
    #[serde(rename = "id")]
    pub id: String,
    /// **[CMS-1500 Carrier Block]** The payer's business name, such as `Aetna` or `Cigna`.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::ProfessionalClaimSubmissionQualifiedOrganizationName>>,
    /// **[CMS-1500 Carrier Block]** The ID of the receiver that processes the claim, typically the clearinghouse or payer. Only include when the receiver differs from the payer.
    #[serde(rename = "receiverId", skip_serializing_if = "Option::is_none")]
    pub receiver_id: Option<String>,
}

impl ProfessionalClaimSubmissionPayer {
    /// The payer being billed for the claim.
    pub fn new(id: String) -> ProfessionalClaimSubmissionPayer {
        ProfessionalClaimSubmissionPayer {
            address: None,
            id,
            name: None,
            receiver_id: None,
        }
    }
}

