/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionPatient : The person who received care, when they are someone other than the insured.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionPatient {
    /// **[CMS-1500 Box 5]** The mailing address for the patient's permanent residence.
    #[serde(rename = "address")]
    pub address: Box<models::ProfessionalClaimSubmissionAddress>,
    /// **[CMS-1500 Box 3]** The patient's date of birth. Used to distinguish the patient from other members with similar names.
    #[serde(rename = "dateOfBirth")]
    pub date_of_birth: String,
    /// **[CMS-1500 Box 3]** The patient's sex.
    #[serde(rename = "gender")]
    pub gender: models::ProfessionalClaimSubmissionGenderCode,
    /// **[CMS-1500 Box 2]** The full name of the person who received care.
    #[serde(rename = "name")]
    pub name: Box<models::ProfessionalClaimSubmissionQualifiedPersonName>,
    /// **[CMS-1500 Box 6]** How the patient is related to the insured.
    #[serde(rename = "relationshipToInsured")]
    pub relationship_to_insured: models::ProfessionalClaimSubmissionPatientRelationshipToInsured,
}

impl ProfessionalClaimSubmissionPatient {
    /// The person who received care, when they are someone other than the insured.
    pub fn new(address: models::ProfessionalClaimSubmissionAddress, date_of_birth: String, gender: models::ProfessionalClaimSubmissionGenderCode, name: models::ProfessionalClaimSubmissionQualifiedPersonName, relationship_to_insured: models::ProfessionalClaimSubmissionPatientRelationshipToInsured) -> ProfessionalClaimSubmissionPatient {
        ProfessionalClaimSubmissionPatient {
            address: Box::new(address),
            date_of_birth,
            gender,
            name: Box::new(name),
            relationship_to_insured,
        }
    }
}

