/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured : How the patient is related to the person insured under the other policy.   - `SELF`: The patient is the other insured.   - `SPOUSE`: The patient is the other insured's spouse.   - `CHILD`: The patient is the other insured's child.   - `EMPLOYEE`: The patient is the other insured's employee.   - `LIFE_PARTNER`: The patient is the other insured's life partner.   - `ORGAN_DONOR`: The patient is an organ donor.   - `CADAVER_DONOR`: The patient is a cadaver donor.   - `OTHER_RELATIONSHIP`: The patient has another relationship to the other insured.   - `UNKNOWN`: The relationship is unknown.
/// How the patient is related to the person insured under the other policy.   - `SELF`: The patient is the other insured.   - `SPOUSE`: The patient is the other insured's spouse.   - `CHILD`: The patient is the other insured's child.   - `EMPLOYEE`: The patient is the other insured's employee.   - `LIFE_PARTNER`: The patient is the other insured's life partner.   - `ORGAN_DONOR`: The patient is an organ donor.   - `CADAVER_DONOR`: The patient is a cadaver donor.   - `OTHER_RELATIONSHIP`: The patient has another relationship to the other insured.   - `UNKNOWN`: The relationship is unknown.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured {
    #[serde(rename = "SPOUSE")]
    Spouse,
    #[serde(rename = "SELF")]
    VariantSelf,
    #[serde(rename = "CHILD")]
    Child,
    #[serde(rename = "EMPLOYEE")]
    Employee,
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "ORGAN_DONOR")]
    OrganDonor,
    #[serde(rename = "CADAVER_DONOR")]
    CadaverDonor,
    #[serde(rename = "LIFE_PARTNER")]
    LifePartner,
    #[serde(rename = "OTHER_RELATIONSHIP")]
    OtherRelationship,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Spouse => write!(f, "SPOUSE"),
            Self::VariantSelf => write!(f, "SELF"),
            Self::Child => write!(f, "CHILD"),
            Self::Employee => write!(f, "EMPLOYEE"),
            Self::Unknown => write!(f, "UNKNOWN"),
            Self::OrganDonor => write!(f, "ORGAN_DONOR"),
            Self::CadaverDonor => write!(f, "CADAVER_DONOR"),
            Self::LifePartner => write!(f, "LIFE_PARTNER"),
            Self::OtherRelationship => write!(f, "OTHER_RELATIONSHIP"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured {
    fn default() -> ProfessionalClaimSubmissionOtherInsuredRelationshipToInsured {
        Self::Spouse
    }
}

