/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmission {
    /// An 837P professional claim submission, either the initial submission or a resubmission.
    #[serde(rename = "professionalClaimSubmission")]
    pub professional_claim_submission: Box<models::ClaimSubmissionSummary>,
}

impl ProfessionalClaimSubmission {
    pub fn new(professional_claim_submission: models::ClaimSubmissionSummary) -> ProfessionalClaimSubmission {
        ProfessionalClaimSubmission {
            professional_claim_submission: Box::new(professional_claim_submission),
        }
    }
}

