/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionProviderSignature : Whether the provider has the rendering provider's signature on file.   - `ON_FILE`: The provider has the rendering provider's signature on file.   - `NOT_ON_FILE`: The provider does not have the rendering provider's signature on file.
/// Whether the provider has the rendering provider's signature on file.   - `ON_FILE`: The provider has the rendering provider's signature on file.   - `NOT_ON_FILE`: The provider does not have the rendering provider's signature on file.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProfessionalClaimSubmissionProviderSignature {
    #[serde(rename = "ON_FILE")]
    OnFile,
    #[serde(rename = "NOT_ON_FILE")]
    NotOnFile,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for ProfessionalClaimSubmissionProviderSignature {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::OnFile => write!(f, "ON_FILE"),
            Self::NotOnFile => write!(f, "NOT_ON_FILE"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for ProfessionalClaimSubmissionProviderSignature {
    fn default() -> ProfessionalClaimSubmissionProviderSignature {
        Self::OnFile
    }
}

