/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionOrderingProvider : The provider who ordered the services, tests, or supplies on a service line. This should be an individual, not an organization, and you should supply at least the `lastName` and an identifier, which is typically the `npi`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionOrderingProvider {
    /// **[CMS-1500 Box 17a, 17b]** Identifiers for the ordering provider.
    #[serde(rename = "identifiers", skip_serializing_if = "Option::is_none")]
    pub identifiers: Option<Box<models::ProfessionalClaimSubmissionOrderingProviderIdentifiers>>,
    /// **[CMS-1500 Box 17]** The full name of the ordering provider.
    #[serde(rename = "name")]
    pub name: Box<models::ProfessionalClaimSubmissionQualifiedPersonName>,
}

impl ProfessionalClaimSubmissionOrderingProvider {
    /// The provider who ordered the services, tests, or supplies on a service line. This should be an individual, not an organization, and you should supply at least the `lastName` and an identifier, which is typically the `npi`.
    pub fn new(name: models::ProfessionalClaimSubmissionQualifiedPersonName) -> ProfessionalClaimSubmissionOrderingProvider {
        ProfessionalClaimSubmissionOrderingProvider {
            identifiers: None,
            name: Box::new(name),
        }
    }
}

