/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionClaimNote : **[CMS-1500 Box 19]** A free-text note with additional information about the claim. Provide exactly one note type.
/// **[CMS-1500 Box 19]** A free-text note with additional information about the claim. Provide exactly one note type.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProfessionalClaimSubmissionClaimNote {
    AdditionalInformation(Box<models::AdditionalInformation>),
    CertificationNarrative(Box<models::CertificationNarrative>),
    GoalsRehabilitationOrDischargePlans(Box<models::GoalsRehabilitationOrDischargePlans>),
    DiagnosisDescription(Box<models::DiagnosisDescription>),
    ThirdPartyOrganization(Box<models::ThirdPartyOrganization>),
}

impl Default for ProfessionalClaimSubmissionClaimNote {
    fn default() -> Self {
        Self::AdditionalInformation(Default::default())
    }
}

