/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionPurchasedService : A service the billing provider bought from an outside provider and is billing to the payer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionPurchasedService {
    /// **[CMS-1500 Box 20]** The price the billing provider paid the outside provider for this service.
    #[serde(rename = "chargeAmount")]
    pub charge_amount: String,
    /// The outside provider the billing provider bought this service from.
    #[serde(rename = "provider")]
    pub provider: Box<models::ProfessionalClaimSubmissionPurchasedServiceProvider>,
}

impl ProfessionalClaimSubmissionPurchasedService {
    /// A service the billing provider bought from an outside provider and is billing to the payer.
    pub fn new(charge_amount: String, provider: models::ProfessionalClaimSubmissionPurchasedServiceProvider) -> ProfessionalClaimSubmissionPurchasedService {
        ProfessionalClaimSubmissionPurchasedService {
            charge_amount,
            provider: Box::new(provider),
        }
    }
}

