/*
 * Stedi Healthcare Claims
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::claims::models;
use serde::{Deserialize, Serialize};

/// ProfessionalClaimSubmissionResubmission : Information identifying this claim as a replacement or cancellation of a previously submitted claim.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProfessionalClaimSubmissionResubmission {
    /// Whether this claim replaces or cancels a previously submitted claim.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<models::ProfessionalClaimSubmissionClaimFrequencyCode>,
    /// The Payer Claim Control Number (sometimes called the ICN) of the original claim being replaced or cancelled. Generally required when `code` is set. One exception is Original Medicare, which specifies that you omit this value from resubmissions.
    #[serde(rename = "originalReferenceNumber", skip_serializing_if = "Option::is_none")]
    pub original_reference_number: Option<String>,
}

impl ProfessionalClaimSubmissionResubmission {
    /// Information identifying this claim as a replacement or cancellation of a previously submitted claim.
    pub fn new() -> ProfessionalClaimSubmissionResubmission {
        ProfessionalClaimSubmissionResubmission {
            code: None,
            original_reference_number: None,
        }
    }
}

