/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// AmbulanceCertification : Required when the claim involves ambulance transport services.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmbulanceCertification {
    #[serde(rename = "certificationConditionIndicator")]
    pub certification_condition_indicator: models::AmbulanceCertificationCertificationConditionIndicator,
    #[serde(rename = "conditionCodes")]
    pub condition_codes: Vec<models::AmbulanceCertificationConditionCodesItem>,
}

impl AmbulanceCertification {
    /// Required when the claim involves ambulance transport services.
    pub fn new(certification_condition_indicator: models::AmbulanceCertificationCertificationConditionIndicator, condition_codes: Vec<models::AmbulanceCertificationConditionCodesItem>) -> AmbulanceCertification {
        AmbulanceCertification {
            certification_condition_indicator,
            condition_codes,
        }
    }
}

