/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// AmbulanceTransportInformation : Information about the ambulance service provided to the patient.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmbulanceTransportInformation {
    #[serde(rename = "ambulanceTransportReasonCode")]
    pub ambulance_transport_reason_code: models::AmbulanceTransportReasonCode,
    /// The weight of the patient, in pounds, at the time of transport. Provide this value as a decimal, such as `150.5`
    #[serde(rename = "patientWeightInPounds", skip_serializing_if = "Option::is_none")]
    pub patient_weight_in_pounds: Option<String>,
    /// The reason for the round trip ambulance service.
    #[serde(rename = "roundTripPurposeDescription", skip_serializing_if = "Option::is_none")]
    pub round_trip_purpose_description: Option<String>,
    /// The reason for usage of a stretcher during ambulance service.
    #[serde(rename = "stretcherPurposeDescription", skip_serializing_if = "Option::is_none")]
    pub stretcher_purpose_description: Option<String>,
    /// The number of miles the ambulance traveled to transport the patient. Provide this value as a decimal, such as `20.5`. Note that `0` (zero) is a valid value when ambulance services do not include a charge for mileage.
    #[serde(rename = "transportDistanceInMiles")]
    pub transport_distance_in_miles: String,
}

impl AmbulanceTransportInformation {
    /// Information about the ambulance service provided to the patient.
    pub fn new(ambulance_transport_reason_code: models::AmbulanceTransportReasonCode, transport_distance_in_miles: String) -> AmbulanceTransportInformation {
        AmbulanceTransportInformation {
            ambulance_transport_reason_code,
            patient_weight_in_pounds: None,
            round_trip_purpose_description: None,
            stretcher_purpose_description: None,
            transport_distance_in_miles,
        }
    }
}

