/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// BadRequestException : The server cannot process the request due to an apparent client error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BadRequestException {
    /// Error classification code
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
}

impl BadRequestException {
    /// The server cannot process the request due to an apparent client error.
    pub fn new(message: String) -> BadRequestException {
        BadRequestException {
            code: None,
            message,
        }
    }
}

