/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// CertificationTypeCode : Code indicating the type of certification. Can be set to `I` - Initial, `R` - Renewal, or `S` - Revised.
/// Code indicating the type of certification. Can be set to `I` - Initial, `R` - Renewal, or `S` - Revised.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CertificationTypeCode {
    #[serde(rename = "I")]
    I,
    #[serde(rename = "R")]
    R,
    #[serde(rename = "S")]
    S,

}

impl std::fmt::Display for CertificationTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::I => write!(f, "I"),
            Self::R => write!(f, "R"),
            Self::S => write!(f, "S"),
        }
    }
}

impl Default for CertificationTypeCode {
    fn default() -> CertificationTypeCode {
        Self::I
    }
}

