/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// CertificationConditionCodeAppliesIndicator : Code indicating whether an EPSDT referral was given to the patient. Can be set to `N` - No or `Y` - Yes.
/// Code indicating whether an EPSDT referral was given to the patient. Can be set to `N` - No or `Y` - Yes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CertificationConditionCodeAppliesIndicator {
    #[serde(rename = "N")]
    N,
    #[serde(rename = "Y")]
    Y,

}

impl std::fmt::Display for CertificationConditionCodeAppliesIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::N => write!(f, "N"),
            Self::Y => write!(f, "Y"),
        }
    }
}

impl Default for CertificationConditionCodeAppliesIndicator {
    fn default() -> CertificationConditionCodeAppliesIndicator {
        Self::N
    }
}

