/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimReference : Information about the claim.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimReference {
    /// This shape is deprecated: Currently not used.
    #[serde(rename = "claimType", skip_serializing_if = "Option::is_none")]
    pub claim_type: Option<String>,
    /// An identifier Stedi assigns to the claim.
    #[serde(rename = "correlationId", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    /// A tracking number that Stedi assigns to the claim.
    #[serde(rename = "customerClaimNumber", skip_serializing_if = "Option::is_none")]
    pub customer_claim_number: Option<String>,
    /// The X12 EDI version Stedi used to generate the claim for the payer. This is always `5010`.
    #[serde(rename = "formatVersion", skip_serializing_if = "Option::is_none")]
    pub format_version: Option<String>,
    /// The `patientControlNumber` from the original request, if supplied. This is a unique identifier that you assign to the claim so you can track the claim and correlate it with responses from the payer.
    #[serde(rename = "patientControlNumber", skip_serializing_if = "Option::is_none")]
    pub patient_control_number: Option<String>,
    /// This shape is deprecated: Please use payerId.
    #[serde(rename = "payerID", skip_serializing_if = "Option::is_none")]
    pub payer_id_legacy1: Option<String>,
    /// The payer's ID. This is the same as the `tradingPartnerServiceId`.
    #[serde(rename = "payerId", skip_serializing_if = "Option::is_none")]
    pub payer_id: Option<String>,
    /// A tracking number Stedi assigns to the claim. This is the same as the `correlationId`.
    #[serde(rename = "rhclaimNumber", skip_serializing_if = "Option::is_none")]
    pub rhclaim_number: Option<String>,
    /// Contains a unique identifier for each service line, listed in the order the service lines were included in the claim. You can use these identifiers to correlate payer responses to specific service lines.
    #[serde(rename = "serviceLines", skip_serializing_if = "Option::is_none")]
    pub service_lines: Option<Vec<models::ServiceLineResponseIdentifier>>,
    /// Stedi's ID for the entity that submitted the claim.
    #[serde(rename = "submitterId", skip_serializing_if = "Option::is_none")]
    pub submitter_id: Option<String>,
    /// A timestamp for Stedi's response to the claim submission.
    #[serde(rename = "timeOfResponse", skip_serializing_if = "Option::is_none")]
    pub time_of_response: Option<String>,
}

impl ClaimReference {
    /// Information about the claim.
    pub fn new() -> ClaimReference {
        ClaimReference {
            claim_type: None,
            correlation_id: None,
            customer_claim_number: None,
            format_version: None,
            patient_control_number: None,
            payer_id_legacy1: None,
            payer_id: None,
            rhclaim_number: None,
            service_lines: None,
            submitter_id: None,
            time_of_response: None,
        }
    }
}

