/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimAdjustments : Claim-level adjustments with reason codes and amounts.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimAdjustments {
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount1", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount1: Option<String>,
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount2", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount2: Option<String>,
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount3", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount3: Option<String>,
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount4", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount4: Option<String>,
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount5", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount5: Option<String>,
    /// The amount of the adjustment. A negative amount increases the claim payment and a positive amount decreases the claim payment.
    #[serde(rename = "adjustmentAmount6", skip_serializing_if = "Option::is_none")]
    pub adjustment_amount6: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity1", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity1: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity2", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity2: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity3", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity3: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity4", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity4: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity5", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity5: Option<String>,
    /// The units of service being adjusted. A positive value decreases the covered days and a negative number increases the covered days.
    #[serde(rename = "adjustmentQuantity6", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity6: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason1", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason1: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason2", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason2: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason3", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason3: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason4", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason4: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason5", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason5: Option<String>,
    /// A description identifying the detailed reason the adjustment was made.
    #[serde(rename = "adjustmentReason6", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason6: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode1", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code1: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode2", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code2: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode3", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code3: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode4", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code4: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode5", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code5: Option<String>,
    /// A code identifying the detailed reason the adjustment was made. Visit [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) in the X12 documentation for a complete list.
    #[serde(rename = "adjustmentReasonCode6", skip_serializing_if = "Option::is_none")]
    pub adjustment_reason_code6: Option<String>,
    /// The code identifying the category of adjustment reason codes. Visit [ERA code lists](https://www.stedi.com/docs/healthcare/claims-code-lists#claim-adjustment-group-code) for a complete list and usage notes.
    #[serde(rename = "claimAdjustmentGroupCode", skip_serializing_if = "Option::is_none")]
    pub claim_adjustment_group_code: Option<models::ClaimAdjustmentGroupCode>,
    /// The description of the `claimAdjustmentGroupCode`.
    #[serde(rename = "claimAdjustmentGroupCodeValue", skip_serializing_if = "Option::is_none")]
    pub claim_adjustment_group_code_value: Option<String>,
}

impl ClaimAdjustments {
    /// Claim-level adjustments with reason codes and amounts.
    pub fn new() -> ClaimAdjustments {
        ClaimAdjustments {
            adjustment_amount1: None,
            adjustment_amount2: None,
            adjustment_amount3: None,
            adjustment_amount4: None,
            adjustment_amount5: None,
            adjustment_amount6: None,
            adjustment_quantity1: None,
            adjustment_quantity2: None,
            adjustment_quantity3: None,
            adjustment_quantity4: None,
            adjustment_quantity5: None,
            adjustment_quantity6: None,
            adjustment_reason1: None,
            adjustment_reason2: None,
            adjustment_reason3: None,
            adjustment_reason4: None,
            adjustment_reason5: None,
            adjustment_reason6: None,
            adjustment_reason_code1: None,
            adjustment_reason_code2: None,
            adjustment_reason_code3: None,
            adjustment_reason_code4: None,
            adjustment_reason_code5: None,
            adjustment_reason_code6: None,
            claim_adjustment_group_code: None,
            claim_adjustment_group_code_value: None,
        }
    }
}

