/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimFrequencyCode : Identify the type of claim. Can be set to: `1` - indicates an original claim, `7` - Indicates the new claim is a replacement or correction, `8` - Indicates the claim is void or canceled
/// Identify the type of claim. Can be set to: `1` - indicates an original claim, `7` - Indicates the new claim is a replacement or correction, `8` - Indicates the claim is void or canceled
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClaimFrequencyCode {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "7")]
    Variant7,
    #[serde(rename = "8")]
    Variant8,

}

impl std::fmt::Display for ClaimFrequencyCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1 => write!(f, "1"),
            Self::Variant7 => write!(f, "7"),
            Self::Variant8 => write!(f, "8"),
        }
    }
}

impl Default for ClaimFrequencyCode {
    fn default() -> ClaimFrequencyCode {
        Self::Variant1
    }
}

