/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimInformationRelatedCausesCodeItem : Code identifying an accompanying cause of an illness, injury or an accident. Can be set to `AA` - Auto Accident, `EM` - Employment, or `OA` - Other Accident.
/// Code identifying an accompanying cause of an illness, injury or an accident. Can be set to `AA` - Auto Accident, `EM` - Employment, or `OA` - Other Accident.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClaimInformationRelatedCausesCodeItem {
    #[serde(rename = "AA")]
    Aa,
    #[serde(rename = "EM")]
    Em,
    #[serde(rename = "OA")]
    Oa,

}

impl std::fmt::Display for ClaimInformationRelatedCausesCodeItem {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aa => write!(f, "AA"),
            Self::Em => write!(f, "EM"),
            Self::Oa => write!(f, "OA"),
        }
    }
}

impl Default for ClaimInformationRelatedCausesCodeItem {
    fn default() -> ClaimInformationRelatedCausesCodeItem {
        Self::Aa
    }
}

