/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimsDiagnosisTypeCode : Code indicating the specific industry code list. Can be set to `ABK` - International Classification of Diseases Clinical Modification (ICD-10-CM) Principal Diagnosis or `ABF` - International Classification of Diseases Clinical Modification (ICD-10-CM) Diagnosis.
/// Code indicating the specific industry code list. Can be set to `ABK` - International Classification of Diseases Clinical Modification (ICD-10-CM) Principal Diagnosis or `ABF` - International Classification of Diseases Clinical Modification (ICD-10-CM) Diagnosis.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClaimsDiagnosisTypeCode {
    #[serde(rename = "BK")]
    Bk,
    #[serde(rename = "ABK")]
    Abk,
    #[serde(rename = "BF")]
    Bf,
    #[serde(rename = "ABF")]
    Abf,

}

impl std::fmt::Display for ClaimsDiagnosisTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Bk => write!(f, "BK"),
            Self::Abk => write!(f, "ABK"),
            Self::Bf => write!(f, "BF"),
            Self::Abf => write!(f, "ABF"),
        }
    }
}

impl Default for ClaimsDiagnosisTypeCode {
    fn default() -> ClaimsDiagnosisTypeCode {
        Self::Bk
    }
}

