/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ClaimsWarning : Warnings indicate issues that may cause some payers to reject the claim. Stedi doesn’t reject claims with warnings only - a response with warnings but no errors means Stedi still submitted the claim.  If you receive warnings, we recommend closely monitoring 277CA responses from the payer for rejections. If the claim is rejected, we recommend fixing the issues identified in the warnings before resubmitting.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClaimsWarning {
    /// A machine-readable code indicating the type of problem.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// A human-readable description of the problem.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl ClaimsWarning {
    /// Warnings indicate issues that may cause some payers to reject the claim. Stedi doesn’t reject claims with warnings only - a response with warnings but no errors means Stedi still submitted the claim.  If you receive warnings, we recommend closely monitoring 277CA responses from the payer for rejections. If the claim is rejected, we recommend fixing the issues identified in the warnings before resubmitting.
    pub fn new() -> ClaimsWarning {
        ClaimsWarning {
            code: None,
            description: None,
        }
    }
}

