/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CobMetaData {
    /// The type of data in the request. Stedi uses `production` to identify transactions processed in our live clearinghouse environment.
    #[serde(rename = "applicationMode", skip_serializing_if = "Option::is_none")]
    pub application_mode: Option<String>,
    /// The value provided in the `submitterTransactionIdentifier` property in the original COB request.
    #[serde(rename = "outboundTraceId", skip_serializing_if = "Option::is_none")]
    pub outbound_trace_id: Option<String>,
    /// A unique ID Stedi assigns to the COB request.
    #[serde(rename = "traceId", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

impl CobMetaData {
    pub fn new() -> CobMetaData {
        CobMetaData {
            application_mode: None,
            outbound_trace_id: None,
            trace_id: None,
        }
    }
}

