/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CobPayer {
    /// The payer's name, such as `CIGNA`.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The identifier the payer returns in the response, which may differ from the `tradingPartnerServiceId` you sent. You can use `meta.traceId` to correlate a response to your request.
    #[serde(rename = "payerIdentification", skip_serializing_if = "Option::is_none")]
    pub payer_identification: Option<String>,
}

impl CobPayer {
    pub fn new() -> CobPayer {
        CobPayer {
            name: None,
            payer_identification: None,
        }
    }
}

