/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// CobResponseServiceTypeCode : Code identifying the type of services included in a `benefitsInformation` object.
/// Code identifying the type of services included in a `benefitsInformation` object.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CobResponseServiceTypeCode {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "30")]
    Variant30,
    #[serde(rename = "33")]
    Variant33,
    #[serde(rename = "35")]
    Variant35,
    #[serde(rename = "47")]
    Variant47,
    #[serde(rename = "52")]
    Variant52,
    #[serde(rename = "88")]
    Variant88,
    #[serde(rename = "98")]
    Variant98,
    #[serde(rename = "AL")]
    Al,
    #[serde(rename = "MH")]
    Mh,
    #[serde(rename = "UC")]
    Uc,

}

impl std::fmt::Display for CobResponseServiceTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant1 => write!(f, "1"),
            Self::Variant30 => write!(f, "30"),
            Self::Variant33 => write!(f, "33"),
            Self::Variant35 => write!(f, "35"),
            Self::Variant47 => write!(f, "47"),
            Self::Variant52 => write!(f, "52"),
            Self::Variant88 => write!(f, "88"),
            Self::Variant98 => write!(f, "98"),
            Self::Al => write!(f, "AL"),
            Self::Mh => write!(f, "MH"),
            Self::Uc => write!(f, "UC"),
        }
    }
}

impl Default for CobResponseServiceTypeCode {
    fn default() -> CobResponseServiceTypeCode {
        Self::Variant1
    }
}

