/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ConditionIndicatorDurableMedicalEquipmentCertificationConditionIndicator : Code indicating whether there is a certification. Can be set to `N` - No or `Y` - Yes.
/// Code indicating whether there is a certification. Can be set to `N` - No or `Y` - Yes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConditionIndicatorDurableMedicalEquipmentCertificationConditionIndicator {
    #[serde(rename = "Y")]
    Y,
    #[serde(rename = "N")]
    N,

}

impl std::fmt::Display for ConditionIndicatorDurableMedicalEquipmentCertificationConditionIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Y => write!(f, "Y"),
            Self::N => write!(f, "N"),
        }
    }
}

impl Default for ConditionIndicatorDurableMedicalEquipmentCertificationConditionIndicator {
    fn default() -> ConditionIndicatorDurableMedicalEquipmentCertificationConditionIndicator {
        Self::Y
    }
}

