/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Confidence {
    /// The confidence level for the match.
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<models::ConfidenceLevel>,
    /// A reason for the confidence level. For example, `This record was identified as a low confidence match due to a DOB partial match`.
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl Confidence {
    pub fn new() -> Confidence {
        Confidence {
            level: None,
            reason: None,
        }
    }
}

