/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// CopayStatusCode : Code indicating whether co-payment requirements were met. Can be set to `O` - Copay exempt.
/// Code indicating whether co-payment requirements were met. Can be set to `O` - Copay exempt.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CopayStatusCode {
    #[serde(rename = "0")]
    Variant0,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for CopayStatusCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant0 => write!(f, "0"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for CopayStatusCode {
    fn default() -> CopayStatusCode {
        Self::Variant0
    }
}

