/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateEligibilityCheck429ErrorResponseContent {
    TooManyRequestsException(Box<models::TooManyRequestsException>),
    ThrottlingException(Box<models::ThrottlingException>),
}

impl Default for CreateEligibilityCheck429ErrorResponseContent {
    fn default() -> Self {
        Self::TooManyRequestsException(Default::default())
    }
}

