/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// DentalLineAdjudicationInformation : Includes service line adjudication information for coordination of benefits between the initial payers of a health care claim and all subsequent payers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DentalLineAdjudicationInformation {
    /// The date the other payer adjudicated or paid the claim.
    #[serde(rename = "adjudicationOrPaymentDate")]
    pub adjudication_or_payment_date: String,
    /// The LX assigned number of the service line into which this service line is bundled. It's only used to bundle service lines.
    #[serde(rename = "bundledOrUnbundledLineNumber", skip_serializing_if = "Option::is_none")]
    pub bundled_or_unbundled_line_number: Option<String>,
    /// Required when the payer made line level adjustments which caused the amount paid to differ from the amount originally charged. You can include up to five objects in this array.
    #[serde(rename = "claimAdjustmentInformation", skip_serializing_if = "Option::is_none")]
    pub claim_adjustment_information: Option<Vec<models::ClaimAdjustment>>,
    /// The payer ID for the payer responsible for reimbursement.
    #[serde(rename = "otherPayerPrimaryIdentifier")]
    pub other_payer_primary_identifier: String,
    /// The number of paid units from the remittance advice. expressed as a decimal. When paid units are not present on the remittance advice, use the original billed units. The maximum length for this property is 8 digits excluding the decimal. When a decimal is used, the maximum number of digits allowed to the right of the decimal is three.
    #[serde(rename = "paidServiceUnitCount")]
    pub paid_service_unit_count: String,
    /// The procedure code.
    #[serde(rename = "procedureCode")]
    pub procedure_code: String,
    /// The meaning of the procedure code.
    #[serde(rename = "procedureCodeDescription", skip_serializing_if = "Option::is_none")]
    pub procedure_code_description: Option<String>,
    /// Modifiers that convey special circumstances related to the performance of the service. You can include up to four modifiers in this array.
    #[serde(rename = "procedureModifier", skip_serializing_if = "Option::is_none")]
    pub procedure_modifier: Option<Vec<String>>,
    /// The amount of the service line that the patient is still responsible for, expressed as a decimal.
    #[serde(rename = "remainingPatientLiability", skip_serializing_if = "Option::is_none")]
    pub remaining_patient_liability: Option<String>,
    /// Code identifying the the type of product or service ID. Can be set to `AD` - American Dental Association Codes or `ER` - Jurisdiction Specific Procedure and Supply Codes.
    #[serde(rename = "serviceIdQualifier")]
    pub service_id_qualifier: models::DentalLineAdjudicationInformationServiceIdQualifier,
    /// The amount paid for this service line, expressed as a decimal. Zero (0) is an acceptable value.
    #[serde(rename = "serviceLinePaidAmount")]
    pub service_line_paid_amount: String,
}

impl DentalLineAdjudicationInformation {
    /// Includes service line adjudication information for coordination of benefits between the initial payers of a health care claim and all subsequent payers.
    pub fn new(adjudication_or_payment_date: String, other_payer_primary_identifier: String, paid_service_unit_count: String, procedure_code: String, service_id_qualifier: models::DentalLineAdjudicationInformationServiceIdQualifier, service_line_paid_amount: String) -> DentalLineAdjudicationInformation {
        DentalLineAdjudicationInformation {
            adjudication_or_payment_date,
            bundled_or_unbundled_line_number: None,
            claim_adjustment_information: None,
            other_payer_primary_identifier,
            paid_service_unit_count,
            procedure_code,
            procedure_code_description: None,
            procedure_modifier: None,
            remaining_patient_liability: None,
            service_id_qualifier,
            service_line_paid_amount,
        }
    }
}

