/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DentalClaimsSubmissionResponseContent {
    #[serde(rename = "claimReference", skip_serializing_if = "Option::is_none")]
    pub claim_reference: Option<Box<models::ClaimReference>>,
    /// An identifier for the transaction.
    #[serde(rename = "controlNumber", skip_serializing_if = "Option::is_none")]
    pub control_number: Option<String>,
    /// Currently not used.
    #[serde(rename = "editResponses", skip_serializing_if = "Option::is_none")]
    pub edit_responses: Option<Vec<models::EditResponse>>,
    /// This shape is deprecated: Currently not used.
    #[serde(rename = "editStatus", skip_serializing_if = "Option::is_none")]
    pub edit_status: Option<String>,
    /// Errors resulting from claim edits. You must review and fix these errors before resubmitting.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::ClaimsError>>,
    #[serde(rename = "failure", skip_serializing_if = "Option::is_none")]
    pub failure: Option<Box<models::Failure>>,
    #[serde(rename = "httpStatusCode", skip_serializing_if = "Option::is_none")]
    pub http_status_code: Option<models::HttpStatusCode>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::ResponseMeta>>,
    #[serde(rename = "payer", skip_serializing_if = "Option::is_none")]
    pub payer: Option<Box<models::ClaimsPayer>>,
    /// The status of the claim submission.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// An ID for the payer you identified in the original claim. This value may differ from the `tradingPartnerServiceId` you submitted in the original request because it reflects the payer's internal concept of their ID, not necessarily the ID Stedi uses to route requests to this payer.
    #[serde(rename = "tradingPartnerServiceId", skip_serializing_if = "Option::is_none")]
    pub trading_partner_service_id: Option<String>,
    /// A list of warnings. Currently not used.
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<models::ClaimsWarning>>,
    /// A [277CA claim acknowledgment](https://www.stedi.com/docs/healthcare/claim-responses-overview#277ca-claim-acknowledgment) acceptance or rejection from Stedi in X12 EDI format. It indicates whether the claim has passed Stedi's claim edits.  When the claim fails one or more edits, the 277CA contains `STC` segments with information about each error. These are the same error codes that appear in the `errors` array.  Note that this 277CA only indicates whether Stedi has accepted or rejected the claim submission. You may receive additional 277CA acceptances or rejections as the claim is routed to the payer.
    #[serde(rename = "x12", skip_serializing_if = "Option::is_none")]
    pub x12: Option<String>,
}

impl DentalClaimsSubmissionResponseContent {
    pub fn new() -> DentalClaimsSubmissionResponseContent {
        DentalClaimsSubmissionResponseContent {
            claim_reference: None,
            control_number: None,
            edit_responses: None,
            edit_status: None,
            errors: None,
            failure: None,
            http_status_code: None,
            meta: None,
            payer: None,
            status: None,
            trading_partner_service_id: None,
            warnings: None,
            x12: None,
        }
    }
}

