/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiagnosisRelatedGroupInformation {
    /// The diagnosis related group code.
    #[serde(rename = "drugRelatedGroupCode")]
    pub drug_related_group_code: String,
}

impl DiagnosisRelatedGroupInformation {
    pub fn new(drug_related_group_code: String) -> DiagnosisRelatedGroupInformation {
        DiagnosisRelatedGroupInformation {
            drug_related_group_code,
        }
    }
}

