/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckResponseServiceCodeSystem : Identifies the external code list used to provide the specified procedure or service codes.  Payers may sometimes return other non-compliant values.
/// Identifies the external code list used to provide the specified procedure or service codes.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckResponseServiceCodeSystem {
    #[serde(rename = "STC")]
    Stc,
    #[serde(rename = "CDT")]
    Cdt,
    #[serde(rename = "CPT")]
    Cpt,
    #[serde(rename = "NDC")]
    Ndc,
    #[serde(rename = "HCPCS")]
    Hcpcs,
    #[serde(rename = "ICD-10-PCS")]
    Icd10Pcs,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for EligibilityCheckResponseServiceCodeSystem {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Stc => write!(f, "STC"),
            Self::Cdt => write!(f, "CDT"),
            Self::Cpt => write!(f, "CPT"),
            Self::Ndc => write!(f, "NDC"),
            Self::Hcpcs => write!(f, "HCPCS"),
            Self::Icd10Pcs => write!(f, "ICD-10-PCS"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for EligibilityCheckResponseServiceCodeSystem {
    fn default() -> EligibilityCheckResponseServiceCodeSystem {
        Self::Stc
    }
}

