/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckPatientAttributeDateRanges : Contains the dates associated with patient attributes, as ISO 8601 date ranges. These provide temporal context for patient-specific data and eligibility periods.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckPatientAttributeDateRanges {
    /// Added date. Payers may return this information in the case of retroactive eligibility.
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<Box<models::EligibilityCheckDateRange>>,
    /// The admission date or dates.
    #[serde(rename = "admission", skip_serializing_if = "Option::is_none")]
    pub admission: Option<Box<models::EligibilityCheckDateRange>>,
    /// The certification date.
    #[serde(rename = "certification", skip_serializing_if = "Option::is_none")]
    pub certification: Option<Box<models::EligibilityCheckDateRange>>,
    /// Consolidated Omnibus Budget Reconciliation Act (COBRA) date.
    #[serde(rename = "cobra", skip_serializing_if = "Option::is_none")]
    pub cobra: Option<Box<models::EligibilityCheckDateRange>>,
    /// The date of death.
    #[serde(rename = "dateOfDeath", skip_serializing_if = "Option::is_none")]
    pub date_of_death: Option<Box<models::EligibilityCheckDateRange>>,
    /// The date when the patient information was last updated.
    #[serde(rename = "dateOfLastUpdate", skip_serializing_if = "Option::is_none")]
    pub date_of_last_update: Option<Box<models::EligibilityCheckDateRange>>,
    /// The discharge date.
    #[serde(rename = "discharge", skip_serializing_if = "Option::is_none")]
    pub discharge: Option<Box<models::EligibilityCheckDateRange>>,
    /// The effective date of change.
    #[serde(rename = "effectiveDateOfChange", skip_serializing_if = "Option::is_none")]
    pub effective_date_of_change: Option<Box<models::EligibilityCheckDateRange>>,
    /// Plan eligibility dates.
    #[serde(rename = "eligibility", skip_serializing_if = "Option::is_none")]
    pub eligibility: Option<Box<models::EligibilityCheckDateRange>>,
    /// The enrollment date.
    #[serde(rename = "enrollment", skip_serializing_if = "Option::is_none")]
    pub enrollment: Option<Box<models::EligibilityCheckDateRange>>,
    /// The issue date.
    #[serde(rename = "issue", skip_serializing_if = "Option::is_none")]
    pub issue: Option<Box<models::EligibilityCheckDateRange>>,
    /// Plan effective dates.
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<models::EligibilityCheckDateRange>>,
    /// The policy date.
    #[serde(rename = "policy", skip_serializing_if = "Option::is_none")]
    pub policy: Option<Box<models::EligibilityCheckDateRange>>,
    /// Premium paid to date.
    #[serde(rename = "premiumPaidToDate", skip_serializing_if = "Option::is_none")]
    pub premium_paid_to_date: Option<Box<models::EligibilityCheckDateRange>>,
    /// The service date or dates.
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<Box<models::EligibilityCheckDateRange>>,
    /// The status date.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Box<models::EligibilityCheckDateRange>>,
}

impl EligibilityCheckPatientAttributeDateRanges {
    /// Contains the dates associated with patient attributes, as ISO 8601 date ranges. These provide temporal context for patient-specific data and eligibility periods.
    pub fn new() -> EligibilityCheckPatientAttributeDateRanges {
        EligibilityCheckPatientAttributeDateRanges {
            added: None,
            admission: None,
            certification: None,
            cobra: None,
            date_of_death: None,
            date_of_last_update: None,
            discharge: None,
            effective_date_of_change: None,
            eligibility: None,
            enrollment: None,
            issue: None,
            plan: None,
            policy: None,
            premium_paid_to_date: None,
            service: None,
            status: None,
        }
    }
}

