/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckDependentAdditionalInformation : Additional identifying information about the dependent.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckDependentAdditionalInformation {
    /// The agency claim number, only used when the information source is a Property and Casualty payer.
    #[serde(rename = "agencyClaimNumber", skip_serializing_if = "Option::is_none")]
    pub agency_claim_number: Option<String>,
    /// The class of contract code - used to identify the applicable class of contract for claims processing.
    #[serde(rename = "classOfContractCode", skip_serializing_if = "Option::is_none")]
    pub class_of_contract_code: Option<String>,
    /// The contract number of a contract between the payer and the provider that requested the eligibility check.
    #[serde(rename = "contractNumber", skip_serializing_if = "Option::is_none")]
    pub contract_number: Option<String>,
    /// The eligibility category for the dependent.
    #[serde(rename = "eligibilityCategory", skip_serializing_if = "Option::is_none")]
    pub eligibility_category: Option<String>,
    /// The family unit number.
    #[serde(rename = "familyUnitNumber", skip_serializing_if = "Option::is_none")]
    pub family_unit_number: Option<String>,
    /// The group number and group description.
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<models::EligibilityCheckAdditionalInformationWithName>>,
    /// The group or policy number.
    #[serde(rename = "groupOrPolicyNumber", skip_serializing_if = "Option::is_none")]
    pub group_or_policy_number: Option<String>,
    /// Used when the identification card has a number in addition to the member ID.
    #[serde(rename = "identificationCardSerialNumber", skip_serializing_if = "Option::is_none")]
    pub identification_card_serial_number: Option<String>,
    /// The identity card number. Present when this number differs from the member ID.
    #[serde(rename = "identityCardNumber", skip_serializing_if = "Option::is_none")]
    pub identity_card_number: Option<String>,
    /// The insurance policy number.
    #[serde(rename = "insurancePolicyNumber", skip_serializing_if = "Option::is_none")]
    pub insurance_policy_number: Option<String>,
    /// The issue number.
    #[serde(rename = "issueNumber", skip_serializing_if = "Option::is_none")]
    pub issue_number: Option<String>,
    /// The patient's Medicare Beneficiary Identifier (MBI). If you receive an MBI, we recommend sending a follow-up eligibility check to CMS (payer ID: CMS) for additional benefits data. Visit [Medicare Beneficiary Identifier documentation](https://www.cms.gov/training-education/partner-outreach-resources/new-medicare-card/medical-beneficiary-identifiers-mbis) for more information about the MBI format. This most commonly occurs with patients who are covered by both Medicare and Medicaid.
    #[serde(rename = "mbi", skip_serializing_if = "Option::is_none")]
    pub mbi: Option<String>,
    /// The Medicaid recipient identification number.
    #[serde(rename = "medicaidRecipientId", skip_serializing_if = "Option::is_none")]
    pub medicaid_recipient_id: Option<String>,
    /// The medical record identification number.
    #[serde(rename = "medicalRecordId", skip_serializing_if = "Option::is_none")]
    pub medical_record_id: Option<String>,
    /// The member identification number - only used when checking eligibility with a Workers' Compensation or Property and Casualty insurer.
    #[serde(rename = "memberId", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    /// The patient account number. If you included this value in the original eligibility request, the payer will return the same value here in the response.
    #[serde(rename = "patientAccountNumber", skip_serializing_if = "Option::is_none")]
    pub patient_account_number: Option<String>,
    /// The plan number and plan description.
    #[serde(rename = "plan", skip_serializing_if = "Option::is_none")]
    pub plan: Option<Box<models::EligibilityCheckAdditionalInformationWithName>>,
    /// The plan network identification number and the plan, group, or plan network name.
    #[serde(rename = "planNetwork", skip_serializing_if = "Option::is_none")]
    pub plan_network: Option<Box<models::EligibilityCheckAdditionalInformationWithName>>,
    /// The prior identifier number.
    #[serde(rename = "priorIdentifierNumber", skip_serializing_if = "Option::is_none")]
    pub prior_identifier_number: Option<String>,
    /// The patient's Social Security Number (SSN).
    #[serde(rename = "ssn", skip_serializing_if = "Option::is_none")]
    pub ssn: Option<String>,
}

impl EligibilityCheckDependentAdditionalInformation {
    /// Additional identifying information about the dependent.
    pub fn new() -> EligibilityCheckDependentAdditionalInformation {
        EligibilityCheckDependentAdditionalInformation {
            agency_claim_number: None,
            class_of_contract_code: None,
            contract_number: None,
            eligibility_category: None,
            family_unit_number: None,
            group: None,
            group_or_policy_number: None,
            identification_card_serial_number: None,
            identity_card_number: None,
            insurance_policy_number: None,
            issue_number: None,
            mbi: None,
            medicaid_recipient_id: None,
            medical_record_id: None,
            member_id: None,
            patient_account_number: None,
            plan: None,
            plan_network: None,
            prior_identifier_number: None,
            ssn: None,
        }
    }
}

