/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckPlaceOfService : Identifies a type of healthcare facility where providers may deliver services. Place of service codes are standardized identifiers used across the healthcare industry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckPlaceOfService {
    /// The place of service code identifying the type of facility.  Payers may sometimes return other non-compliant values.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<models::EligibilityCheckPlaceOfServiceCode>,
    /// The human-readable name of the place of service.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl EligibilityCheckPlaceOfService {
    /// Identifies a type of healthcare facility where providers may deliver services. Place of service codes are standardized identifiers used across the healthcare industry.
    pub fn new() -> EligibilityCheckPlaceOfService {
        EligibilityCheckPlaceOfService {
            code: None,
            name: None,
        }
    }
}

