/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckServiceDeliveryLimitPeriod : The time period for a service delivery limit, like per year, per day, or lifetime.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckServiceDeliveryLimitPeriod {
    /// The type of time period `value` counts.  Payers may sometimes return other non-compliant values.
    #[serde(rename = "qualifier", skip_serializing_if = "Option::is_none")]
    pub qualifier: Option<models::EligibilityCheckServiceDeliveryLimitPeriodQualifier>,
    /// The number of periods the limit spans. For example, `12` when the `qualifier` is `MONTH`.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<i32>,
}

impl EligibilityCheckServiceDeliveryLimitPeriod {
    /// The time period for a service delivery limit, like per year, per day, or lifetime.
    pub fn new() -> EligibilityCheckServiceDeliveryLimitPeriod {
        EligibilityCheckServiceDeliveryLimitPeriod {
            qualifier: None,
            value: None,
        }
    }
}

