/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckProvider : Information about the entity that submitted the original eligibility check request. This may be an individual practitioner, a medical group, a hospital, or another type of healthcare provider. This object will always include at least one identifier, such as the provider's [NPI](https://www.stedi.com/docs/healthcare/national-provider-identifier), tax ID, or EIN.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckProvider {
    /// Additional identifying information for the provider.
    #[serde(rename = "additionalInformation", skip_serializing_if = "Option::is_none")]
    pub additional_information: Option<Box<models::EligibilityCheckProviderAdditionalInformation>>,
    /// The address of the entity, such as a provider or organization.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::EligibilityCheckAddress>>,
    /// The Employer Identification Number (EIN), distinct from the Federal Taxpayer Identification Number in `tin`.
    #[serde(rename = "ein", skip_serializing_if = "Option::is_none")]
    pub ein: Option<String>,
    /// The entity's name, as either a person or an organization.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Box<models::EligibilityCheckPersonOrOrganizationName>>,
    /// The provider's [National Provider Identifier (NPI)](https://www.stedi.com/docs/healthcare/national-provider-identifier).
    #[serde(rename = "npi", skip_serializing_if = "Option::is_none")]
    pub npi: Option<String>,
    /// The pharmacy processor number.
    #[serde(rename = "pharmacyProcessorNumber", skip_serializing_if = "Option::is_none")]
    pub pharmacy_processor_number: Option<String>,
    /// Information about the provider's role and taxonomy.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<Box<models::EligibilityCheckEntityProvider>>,
    /// The service provider number. This is an identification number the payer assigns.
    #[serde(rename = "serviceProviderNumber", skip_serializing_if = "Option::is_none")]
    pub service_provider_number: Option<String>,
    /// The Social Security Number (SSN).
    #[serde(rename = "ssn", skip_serializing_if = "Option::is_none")]
    pub ssn: Option<String>,
    /// The Federal Taxpayer Identification Number.
    #[serde(rename = "tin", skip_serializing_if = "Option::is_none")]
    pub tin: Option<String>,
    /// A code identifying the type of provider.  Payers may sometimes return other non-compliant values.
    #[serde(rename = "type")]
    pub r#type: models::EligibilityCheckProviderEntityIdentifierCode,
}

impl EligibilityCheckProvider {
    /// Information about the entity that submitted the original eligibility check request. This may be an individual practitioner, a medical group, a hospital, or another type of healthcare provider. This object will always include at least one identifier, such as the provider's [NPI](https://www.stedi.com/docs/healthcare/national-provider-identifier), tax ID, or EIN.
    pub fn new(r#type: models::EligibilityCheckProviderEntityIdentifierCode) -> EligibilityCheckProvider {
        EligibilityCheckProvider {
            additional_information: None,
            address: None,
            ein: None,
            name: None,
            npi: None,
            pharmacy_processor_number: None,
            provider: None,
            service_provider_number: None,
            ssn: None,
            tin: None,
            r#type,
        }
    }
}

