/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckSubscriberTraceNumber : A trace number the payer assigned to this transaction or echoed back from the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckSubscriberTraceNumber {
    /// The identifier of the organization that assigned the trace number.
    #[serde(rename = "originatingCompanyIdentifier", skip_serializing_if = "Option::is_none")]
    pub originating_company_identifier: Option<String>,
    /// The unique trace number assigned to the transaction.
    #[serde(rename = "referenceIdentification", skip_serializing_if = "Option::is_none")]
    pub reference_identification: Option<String>,
    /// Identifies a subdivision within the organization that assigned the trace number.
    #[serde(rename = "secondaryReferenceIdentification", skip_serializing_if = "Option::is_none")]
    pub secondary_reference_identification: Option<String>,
    /// Whether the payer assigned this trace number to the current transaction (`CURRENT_TRANSACTION`) or is echoing one from the original request (`REFERENCED_TRANSACTION`).  Payers may sometimes return other non-compliant values.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::EligibilityCheckTraceType>,
}

impl EligibilityCheckSubscriberTraceNumber {
    /// A trace number the payer assigned to this transaction or echoed back from the request.
    pub fn new() -> EligibilityCheckSubscriberTraceNumber {
        EligibilityCheckSubscriberTraceNumber {
            originating_company_identifier: None,
            reference_identification: None,
            secondary_reference_identification: None,
            r#type: None,
        }
    }
}

