/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckRequestDependentRelationship : The dependent's relationship to the subscriber.
/// The dependent's relationship to the subscriber.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckRequestDependentRelationship {
    #[serde(rename = "SPOUSE")]
    Spouse,
    #[serde(rename = "CHILD")]
    Child,
    #[serde(rename = "OTHER_ADULT")]
    OtherAdult,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for EligibilityCheckRequestDependentRelationship {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Spouse => write!(f, "SPOUSE"),
            Self::Child => write!(f, "CHILD"),
            Self::OtherAdult => write!(f, "OTHER_ADULT"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for EligibilityCheckRequestDependentRelationship {
    fn default() -> EligibilityCheckRequestDependentRelationship {
        Self::Spouse
    }
}

