/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckProviderAdditionalInformation : Additional identifying information about the provider.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckProviderAdditionalInformation {
    /// The provider's contract number.
    #[serde(rename = "contractNumber", skip_serializing_if = "Option::is_none")]
    pub contract_number: Option<String>,
    /// The provider's electronic device PIN.
    #[serde(rename = "electronicDevicePin", skip_serializing_if = "Option::is_none")]
    pub electronic_device_pin: Option<String>,
    /// The ID number for the provider's facility.
    #[serde(rename = "facilityIdNumber", skip_serializing_if = "Option::is_none")]
    pub facility_id_number: Option<String>,
    /// The provider's facility network identification number.
    #[serde(rename = "facilityNetworkId", skip_serializing_if = "Option::is_none")]
    pub facility_network_id: Option<String>,
    /// The provider's Medicaid provider number.
    #[serde(rename = "medicaidProviderNumber", skip_serializing_if = "Option::is_none")]
    pub medicaid_provider_number: Option<String>,
    /// The provider's Medicare provider number.
    #[serde(rename = "medicareProviderNumber", skip_serializing_if = "Option::is_none")]
    pub medicare_provider_number: Option<String>,
    /// The provider's personal identification number.
    #[serde(rename = "personalIdentificationNumber", skip_serializing_if = "Option::is_none")]
    pub personal_identification_number: Option<String>,
    /// The provider's plan network identification number.
    #[serde(rename = "planNetworkId", skip_serializing_if = "Option::is_none")]
    pub plan_network_id: Option<String>,
    /// The provider's prior identifier number.
    #[serde(rename = "priorIdentifierNumber", skip_serializing_if = "Option::is_none")]
    pub prior_identifier_number: Option<String>,
    /// The provider's state license information.
    #[serde(rename = "stateLicense", skip_serializing_if = "Option::is_none")]
    pub state_license: Option<Box<models::EligibilityCheckStateLicense>>,
    /// The provider's submitter ID.
    #[serde(rename = "submitterId", skip_serializing_if = "Option::is_none")]
    pub submitter_id: Option<String>,
    /// The provider's user ID.
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl EligibilityCheckProviderAdditionalInformation {
    /// Additional identifying information about the provider.
    pub fn new() -> EligibilityCheckProviderAdditionalInformation {
        EligibilityCheckProviderAdditionalInformation {
            contract_number: None,
            electronic_device_pin: None,
            facility_id_number: None,
            facility_network_id: None,
            medicaid_provider_number: None,
            medicare_provider_number: None,
            personal_identification_number: None,
            plan_network_id: None,
            prior_identifier_number: None,
            state_license: None,
            submitter_id: None,
            user_id: None,
        }
    }
}

