/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckServiceDeliveryLimitPattern : The time for routine shipments or deliveries. Visit [Eligibility code lists](https://www.stedi.com/docs/healthcare/eligibility-code-lists#delivery-pattern-time-codes) for a complete list.  Payers may sometimes return other non-compliant values.
/// The time for routine shipments or deliveries. Visit [Eligibility code lists](https://www.stedi.com/docs/healthcare/eligibility-code-lists#delivery-pattern-time-codes) for a complete list.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckServiceDeliveryLimitPattern {
    #[serde(rename = "FIRST_SHIFT")]
    FirstShift,
    #[serde(rename = "SECOND_SHIFT")]
    SecondShift,
    #[serde(rename = "THIRD_SHIFT")]
    ThirdShift,
    #[serde(rename = "AM")]
    Am,
    #[serde(rename = "PM")]
    Pm,
    #[serde(rename = "AS_DIRECTED")]
    AsDirected,
    #[serde(rename = "ANY_SHIFT")]
    AnyShift,
    #[serde(rename = "NONE")]
    None,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for EligibilityCheckServiceDeliveryLimitPattern {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::FirstShift => write!(f, "FIRST_SHIFT"),
            Self::SecondShift => write!(f, "SECOND_SHIFT"),
            Self::ThirdShift => write!(f, "THIRD_SHIFT"),
            Self::Am => write!(f, "AM"),
            Self::Pm => write!(f, "PM"),
            Self::AsDirected => write!(f, "AS_DIRECTED"),
            Self::AnyShift => write!(f, "ANY_SHIFT"),
            Self::None => write!(f, "NONE"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for EligibilityCheckServiceDeliveryLimitPattern {
    fn default() -> EligibilityCheckServiceDeliveryLimitPattern {
        Self::FirstShift
    }
}

