/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckRequestProviderType : The type of provider making the request.
/// The type of provider making the request.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckRequestProviderType {
    #[serde(rename = "PROVIDER")]
    Provider,
    #[serde(rename = "THIRD_PARTY_ADMINISTRATOR")]
    ThirdPartyAdministrator,
    #[serde(rename = "EMPLOYER")]
    Employer,
    #[serde(rename = "HOSPITAL")]
    Hospital,
    #[serde(rename = "FACILITY")]
    Facility,
    #[serde(rename = "GATEWAY_PROVIDER")]
    GatewayProvider,
    #[serde(rename = "PLAN_SPONSOR")]
    PlanSponsor,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for EligibilityCheckRequestProviderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Provider => write!(f, "PROVIDER"),
            Self::ThirdPartyAdministrator => write!(f, "THIRD_PARTY_ADMINISTRATOR"),
            Self::Employer => write!(f, "EMPLOYER"),
            Self::Hospital => write!(f, "HOSPITAL"),
            Self::Facility => write!(f, "FACILITY"),
            Self::GatewayProvider => write!(f, "GATEWAY_PROVIDER"),
            Self::PlanSponsor => write!(f, "PLAN_SPONSOR"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for EligibilityCheckRequestProviderType {
    fn default() -> EligibilityCheckRequestProviderType {
        Self::Provider
    }
}

