/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckDiagnosisCodeSystem : The code system for diagnosis codes. Only supports ICD-10-CM.
/// The code system for diagnosis codes. Only supports ICD-10-CM.
#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckDiagnosisCodeSystem {
    #[serde(rename = "ICD-10-CM")]
    Icd10Cm,
    /// Any value not defined in the spec (payers may return non-compliant values).
    #[serde(untagged)]
    UnknownValue(String),

}

impl std::fmt::Display for EligibilityCheckDiagnosisCodeSystem {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Icd10Cm => write!(f, "ICD-10-CM"),
            Self::UnknownValue(s) => write!(f, "{s}"),
        }
    }
}

impl Default for EligibilityCheckDiagnosisCodeSystem {
    fn default() -> EligibilityCheckDiagnosisCodeSystem {
        Self::Icd10Cm
    }
}

