/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckInvalidEntries : Benefit entries that Stedi marked as invalid. Stedi marks entries when they're missing required data, like a co-insurance benefit without a percentage or a deductible without an amount. Stedi also marks entries when they have unexpected data, like a co-payment with a percentage instead of an amount.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EligibilityCheckInvalidEntries {
    /// Invalid co-insurance entries.
    #[serde(rename = "coInsurance", skip_serializing_if = "Option::is_none")]
    pub co_insurance: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid co-payment entries.
    #[serde(rename = "coPayment", skip_serializing_if = "Option::is_none")]
    pub co_payment: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid cost containment entries.
    #[serde(rename = "costContainment", skip_serializing_if = "Option::is_none")]
    pub cost_containment: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid deductible entries.
    #[serde(rename = "deductible", skip_serializing_if = "Option::is_none")]
    pub deductible: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid limitation entries.
    #[serde(rename = "limitations", skip_serializing_if = "Option::is_none")]
    pub limitations: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid out-of-pocket entries.
    #[serde(rename = "outOfPocket", skip_serializing_if = "Option::is_none")]
    pub out_of_pocket: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
    /// Invalid spend down entries.
    #[serde(rename = "spendDown", skip_serializing_if = "Option::is_none")]
    pub spend_down: Option<Vec<models::EligibilityCheckInvalidBenefit>>,
}

impl EligibilityCheckInvalidEntries {
    /// Benefit entries that Stedi marked as invalid. Stedi marks entries when they're missing required data, like a co-insurance benefit without a percentage or a deductible without an amount. Stedi also marks entries when they have unexpected data, like a co-payment with a percentage instead of an amount.
    pub fn new() -> EligibilityCheckInvalidEntries {
        EligibilityCheckInvalidEntries {
            co_insurance: None,
            co_payment: None,
            cost_containment: None,
            deductible: None,
            limitations: None,
            out_of_pocket: None,
            spend_down: None,
        }
    }
}

