/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// EligibilityCheckSubscriberErrorCode : Payers may sometimes return other non-compliant values.
/// Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EligibilityCheckSubscriberErrorCode {
    #[serde(rename = "15")]
    Variant15,
    #[serde(rename = "33")]
    Variant33,
    #[serde(rename = "35")]
    Variant35,
    #[serde(rename = "42")]
    Variant42,
    #[serde(rename = "43")]
    Variant43,
    #[serde(rename = "45")]
    Variant45,
    #[serde(rename = "47")]
    Variant47,
    #[serde(rename = "48")]
    Variant48,
    #[serde(rename = "49")]
    Variant49,
    #[serde(rename = "51")]
    Variant51,
    #[serde(rename = "52")]
    Variant52,
    #[serde(rename = "53")]
    Variant53,
    #[serde(rename = "54")]
    Variant54,
    #[serde(rename = "55")]
    Variant55,
    #[serde(rename = "56")]
    Variant56,
    #[serde(rename = "57")]
    Variant57,
    #[serde(rename = "58")]
    Variant58,
    #[serde(rename = "60")]
    Variant60,
    #[serde(rename = "61")]
    Variant61,
    #[serde(rename = "62")]
    Variant62,
    #[serde(rename = "63")]
    Variant63,
    #[serde(rename = "69")]
    Variant69,
    #[serde(rename = "70")]
    Variant70,
    #[serde(rename = "71")]
    Variant71,
    #[serde(rename = "72")]
    Variant72,
    #[serde(rename = "73")]
    Variant73,
    #[serde(rename = "74")]
    Variant74,
    #[serde(rename = "75")]
    Variant75,
    #[serde(rename = "76")]
    Variant76,
    #[serde(rename = "78")]
    Variant78,
    #[serde(rename = "98")]
    Variant98,
    #[serde(rename = "AA")]
    Aa,
    #[serde(rename = "AE")]
    Ae,
    #[serde(rename = "AF")]
    Af,
    #[serde(rename = "AG")]
    Ag,
    #[serde(rename = "AO")]
    Ao,
    #[serde(rename = "CI")]
    Ci,
    #[serde(rename = "E8")]
    E8,
    #[serde(rename = "IA")]
    Ia,
    #[serde(rename = "MA")]
    Ma,

}

impl std::fmt::Display for EligibilityCheckSubscriberErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant15 => write!(f, "15"),
            Self::Variant33 => write!(f, "33"),
            Self::Variant35 => write!(f, "35"),
            Self::Variant42 => write!(f, "42"),
            Self::Variant43 => write!(f, "43"),
            Self::Variant45 => write!(f, "45"),
            Self::Variant47 => write!(f, "47"),
            Self::Variant48 => write!(f, "48"),
            Self::Variant49 => write!(f, "49"),
            Self::Variant51 => write!(f, "51"),
            Self::Variant52 => write!(f, "52"),
            Self::Variant53 => write!(f, "53"),
            Self::Variant54 => write!(f, "54"),
            Self::Variant55 => write!(f, "55"),
            Self::Variant56 => write!(f, "56"),
            Self::Variant57 => write!(f, "57"),
            Self::Variant58 => write!(f, "58"),
            Self::Variant60 => write!(f, "60"),
            Self::Variant61 => write!(f, "61"),
            Self::Variant62 => write!(f, "62"),
            Self::Variant63 => write!(f, "63"),
            Self::Variant69 => write!(f, "69"),
            Self::Variant70 => write!(f, "70"),
            Self::Variant71 => write!(f, "71"),
            Self::Variant72 => write!(f, "72"),
            Self::Variant73 => write!(f, "73"),
            Self::Variant74 => write!(f, "74"),
            Self::Variant75 => write!(f, "75"),
            Self::Variant76 => write!(f, "76"),
            Self::Variant78 => write!(f, "78"),
            Self::Variant98 => write!(f, "98"),
            Self::Aa => write!(f, "AA"),
            Self::Ae => write!(f, "AE"),
            Self::Af => write!(f, "AF"),
            Self::Ag => write!(f, "AG"),
            Self::Ao => write!(f, "AO"),
            Self::Ci => write!(f, "CI"),
            Self::E8 => write!(f, "E8"),
            Self::Ia => write!(f, "IA"),
            Self::Ma => write!(f, "MA"),
        }
    }
}

impl Default for EligibilityCheckSubscriberErrorCode {
    fn default() -> EligibilityCheckSubscriberErrorCode {
        Self::Variant15
    }
}

