/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ExternalCauseOfInjuryPresentOnAdmissionIndicator : Indicates whether the external cause of injury was present on admission. Can be set to `N` - No (onset did NOT occur prior to admission to the hospital), `Y` - Yes (onset occurred prior to admission to the hospital), `U` - Unknown, or `W` - Not Applicable.
/// Indicates whether the external cause of injury was present on admission. Can be set to `N` - No (onset did NOT occur prior to admission to the hospital), `Y` - Yes (onset occurred prior to admission to the hospital), `U` - Unknown, or `W` - Not Applicable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExternalCauseOfInjuryPresentOnAdmissionIndicator {
    #[serde(rename = "N")]
    N,
    #[serde(rename = "U")]
    U,
    #[serde(rename = "Y")]
    Y,
    #[serde(rename = "W")]
    W,

}

impl std::fmt::Display for ExternalCauseOfInjuryPresentOnAdmissionIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::N => write!(f, "N"),
            Self::U => write!(f, "U"),
            Self::Y => write!(f, "Y"),
            Self::W => write!(f, "W"),
        }
    }
}

impl Default for ExternalCauseOfInjuryPresentOnAdmissionIndicator {
    fn default() -> ExternalCauseOfInjuryPresentOnAdmissionIndicator {
        Self::N
    }
}

