/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// FormIdentification : Use this object to attach standardized supplemental information to the claim when required by the payer. One example is payer documentation requirements for home health services.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FormIdentification {
    /// A code from the industry code list you identified in `formTypeCode`.
    #[serde(rename = "formIdentifier")]
    pub form_identifier: String,
    #[serde(rename = "formTypeCode")]
    pub form_type_code: models::FormTypeCode,
    /// Use to provide information in response to a coded questionnaire document.
    #[serde(rename = "supportingDocumentation", skip_serializing_if = "Option::is_none")]
    pub supporting_documentation: Option<Vec<models::SupportingDocumentation>>,
}

impl FormIdentification {
    /// Use this object to attach standardized supplemental information to the claim when required by the payer. One example is payer documentation requirements for home health services.
    pub fn new(form_identifier: String, form_type_code: models::FormTypeCode) -> FormIdentification {
        FormIdentification {
            form_identifier,
            form_type_code,
            supporting_documentation: None,
        }
    }
}

