/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// HealthCareCheckRemarkCodes : Standard codes used to communicate informational remarks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthCareCheckRemarkCodes {
    /// Code identifying the specific industry code list containing the `remarkCode`. Can be `HE` - Claim Payment Remark Codes or `RX` - National Council for Prescription Drug Programs Reject/Payment Codes.
    #[serde(rename = "codeListQualifierCode", skip_serializing_if = "Option::is_none")]
    pub code_list_qualifier_code: Option<String>,
    /// The description of the `codeListQualifierCode`. Can be `Claim Payment Remark Codes` or `National Council for Prescription Drug Programs Reject/Payment Codes`.
    #[serde(rename = "codeListQualifierCodeValue", skip_serializing_if = "Option::is_none")]
    pub code_list_qualifier_code_value: Option<String>,
    /// The human readable description of the remark code.
    #[serde(rename = "remark", skip_serializing_if = "Option::is_none")]
    pub remark: Option<String>,
    /// The code identifying the specific remark.  This property can either be a [Remittance Advice Remark Code (RARC)](https://x12.org/codes/remittance-advice-remark-codes) (`codeListQualifierCode` set to `HE`) or a National Council for Prescription Drug Programs Reject/Payment Code (`codeListQualifierCode` set to `RX`).
    #[serde(rename = "remarkCode", skip_serializing_if = "Option::is_none")]
    pub remark_code: Option<String>,
}

impl HealthCareCheckRemarkCodes {
    /// Standard codes used to communicate informational remarks.
    pub fn new() -> HealthCareCheckRemarkCodes {
        HealthCareCheckRemarkCodes {
            code_list_qualifier_code: None,
            code_list_qualifier_code_value: None,
            remark: None,
            remark_code: None,
        }
    }
}

