/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// HealthCareClaimStatusCategoryCode : Code indicating the status category of the `statusCode` property. Visit [277CA code lists](https://www.stedi.com/docs/healthcare/claims-code-lists#claim-status-category-code) for a complete list.
/// Code indicating the status category of the `statusCode` property. Visit [277CA code lists](https://www.stedi.com/docs/healthcare/claims-code-lists#claim-status-category-code) for a complete list.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthCareClaimStatusCategoryCode {
    #[serde(rename = "A0")]
    A0,
    #[serde(rename = "A1")]
    A1,
    #[serde(rename = "A2")]
    A2,
    #[serde(rename = "A3")]
    A3,
    #[serde(rename = "A4")]
    A4,
    #[serde(rename = "A5")]
    A5,
    #[serde(rename = "A6")]
    A6,
    #[serde(rename = "A7")]
    A7,
    #[serde(rename = "A8")]
    A8,
    #[serde(rename = "DR01")]
    Dr01,
    #[serde(rename = "DR02")]
    Dr02,
    #[serde(rename = "DR03")]
    Dr03,
    #[serde(rename = "DR04")]
    Dr04,
    #[serde(rename = "DR05")]
    Dr05,
    #[serde(rename = "DR06")]
    Dr06,
    #[serde(rename = "DR07")]
    Dr07,
    #[serde(rename = "DR08")]
    Dr08,
    #[serde(rename = "P0")]
    P0,
    #[serde(rename = "P1")]
    P1,
    #[serde(rename = "P2")]
    P2,
    #[serde(rename = "P3")]
    P3,
    #[serde(rename = "P4")]
    P4,
    #[serde(rename = "P5")]
    P5,
    #[serde(rename = "F0")]
    F0,
    #[serde(rename = "F1")]
    F1,
    #[serde(rename = "F2")]
    F2,
    #[serde(rename = "F3")]
    F3,
    #[serde(rename = "F3F")]
    F3F,
    #[serde(rename = "F3N")]
    F3N,
    #[serde(rename = "F4")]
    F4,
    #[serde(rename = "R0")]
    R0,
    #[serde(rename = "R1")]
    R1,
    #[serde(rename = "R3")]
    R3,
    #[serde(rename = "R4")]
    R4,
    #[serde(rename = "R5")]
    R5,
    #[serde(rename = "R6")]
    R6,
    #[serde(rename = "R7")]
    R7,
    #[serde(rename = "R8")]
    R8,
    #[serde(rename = "R9")]
    R9,
    #[serde(rename = "R10")]
    R10,
    #[serde(rename = "R11")]
    R11,
    #[serde(rename = "R12")]
    R12,
    #[serde(rename = "R13")]
    R13,
    #[serde(rename = "R14")]
    R14,
    #[serde(rename = "R15")]
    R15,
    #[serde(rename = "R16")]
    R16,
    #[serde(rename = "R17")]
    R17,
    #[serde(rename = "E0")]
    E0,
    #[serde(rename = "E1")]
    E1,
    #[serde(rename = "E2")]
    E2,
    #[serde(rename = "E3")]
    E3,
    #[serde(rename = "E4")]
    E4,
    #[serde(rename = "D0")]
    D0,

}

impl std::fmt::Display for HealthCareClaimStatusCategoryCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::A0 => write!(f, "A0"),
            Self::A1 => write!(f, "A1"),
            Self::A2 => write!(f, "A2"),
            Self::A3 => write!(f, "A3"),
            Self::A4 => write!(f, "A4"),
            Self::A5 => write!(f, "A5"),
            Self::A6 => write!(f, "A6"),
            Self::A7 => write!(f, "A7"),
            Self::A8 => write!(f, "A8"),
            Self::Dr01 => write!(f, "DR01"),
            Self::Dr02 => write!(f, "DR02"),
            Self::Dr03 => write!(f, "DR03"),
            Self::Dr04 => write!(f, "DR04"),
            Self::Dr05 => write!(f, "DR05"),
            Self::Dr06 => write!(f, "DR06"),
            Self::Dr07 => write!(f, "DR07"),
            Self::Dr08 => write!(f, "DR08"),
            Self::P0 => write!(f, "P0"),
            Self::P1 => write!(f, "P1"),
            Self::P2 => write!(f, "P2"),
            Self::P3 => write!(f, "P3"),
            Self::P4 => write!(f, "P4"),
            Self::P5 => write!(f, "P5"),
            Self::F0 => write!(f, "F0"),
            Self::F1 => write!(f, "F1"),
            Self::F2 => write!(f, "F2"),
            Self::F3 => write!(f, "F3"),
            Self::F3F => write!(f, "F3F"),
            Self::F3N => write!(f, "F3N"),
            Self::F4 => write!(f, "F4"),
            Self::R0 => write!(f, "R0"),
            Self::R1 => write!(f, "R1"),
            Self::R3 => write!(f, "R3"),
            Self::R4 => write!(f, "R4"),
            Self::R5 => write!(f, "R5"),
            Self::R6 => write!(f, "R6"),
            Self::R7 => write!(f, "R7"),
            Self::R8 => write!(f, "R8"),
            Self::R9 => write!(f, "R9"),
            Self::R10 => write!(f, "R10"),
            Self::R11 => write!(f, "R11"),
            Self::R12 => write!(f, "R12"),
            Self::R13 => write!(f, "R13"),
            Self::R14 => write!(f, "R14"),
            Self::R15 => write!(f, "R15"),
            Self::R16 => write!(f, "R16"),
            Self::R17 => write!(f, "R17"),
            Self::E0 => write!(f, "E0"),
            Self::E1 => write!(f, "E1"),
            Self::E2 => write!(f, "E2"),
            Self::E3 => write!(f, "E3"),
            Self::E4 => write!(f, "E4"),
            Self::D0 => write!(f, "D0"),
        }
    }
}

impl Default for HealthCareClaimStatusCategoryCode {
    fn default() -> HealthCareClaimStatusCategoryCode {
        Self::A0
    }
}

