/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// InstitutionalClaimDateInformation : Dates and times related to the claim. For example, when the patient was discharged from the hospital.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalClaimDateInformation {
    /// When the patient was admitted to the hospital or facility. This property is **required** on inpatient claims. Can be expressed as a date and time (YYYYMMDDHHMM) or a single date (YYYYMMDD).
    #[serde(rename = "admissionDateAndHour", skip_serializing_if = "Option::is_none")]
    pub admission_date_and_hour: Option<String>,
    /// The time the patient was discharged from the hospital or facility. This property is **required** on final inpatient claims. Can be expressed as a time in format HHMM.
    #[serde(rename = "dischargeHour", skip_serializing_if = "Option::is_none")]
    pub discharge_hour: Option<String>,
    /// The date the repricer received the claim. Required when a repricer is passing the claim onto the payer.
    #[serde(rename = "repricerReceivedDate", skip_serializing_if = "Option::is_none")]
    pub repricer_received_date: Option<String>,
    /// The beginning date of the statement.
    #[serde(rename = "statementBeginDate")]
    pub statement_begin_date: String,
    /// The ending date of the statement.
    #[serde(rename = "statementEndDate")]
    pub statement_end_date: String,
}

impl InstitutionalClaimDateInformation {
    /// Dates and times related to the claim. For example, when the patient was discharged from the hospital.
    pub fn new(statement_begin_date: String, statement_end_date: String) -> InstitutionalClaimDateInformation {
        InstitutionalClaimDateInformation {
            admission_date_and_hour: None,
            discharge_hour: None,
            repricer_received_date: None,
            statement_begin_date,
            statement_end_date,
        }
    }
}

