/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalDrugIdentification {
    /// The sequence number assigned to the drug or biologic. Required when the provided medication involves the compounding of two or more drugs being reported and there is no prescription number. The link sequence number is a provider-assigned number unique to this claim. Its purpose is to enable the receiver to piece together the components of the compound. Note that you can set either this property _or_ `pharmacyPrescriptionNumber`, but not both.
    #[serde(rename = "linkSequenceNumber", skip_serializing_if = "Option::is_none")]
    pub link_sequence_number: Option<String>,
    #[serde(rename = "measurementUnitCode")]
    pub measurement_unit_code: models::InstitutionalMeasurementUnitCode,
    /// The National Drug Code (NDC) number for the drug or biologic. This is a unique number that identifies the drug or biologic, including the labeler code, product code, and package code. The NDC number must be formatted as 5-4-2, with hyphens separating the three parts. For example, 12345-6789-01.
    #[serde(rename = "nationalDrugCode")]
    pub national_drug_code: String,
    /// The number of units of the drug or biologic, formtted as a decimal.
    #[serde(rename = "nationalDrugUnitCount")]
    pub national_drug_unit_count: String,
    /// The prescription number assigned by the pharmacy. Required when dispensing of the drug has been done with an assigned prescription number. In cases where a compound drug is being billed, the components of the compound will all have the same prescription number. Payers receiving the claim can relate all the components by matching the prescription number. Note that you can set either this property _or_ `linkSequenceNumber`, but not both.
    #[serde(rename = "pharmacyPrescriptionNumber", skip_serializing_if = "Option::is_none")]
    pub pharmacy_prescription_number: Option<String>,
}

impl InstitutionalDrugIdentification {
    pub fn new(measurement_unit_code: models::InstitutionalMeasurementUnitCode, national_drug_code: String, national_drug_unit_count: String) -> InstitutionalDrugIdentification {
        InstitutionalDrugIdentification {
            link_sequence_number: None,
            measurement_unit_code,
            national_drug_code,
            national_drug_unit_count,
            pharmacy_prescription_number: None,
        }
    }
}

