/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalClaimsRawX12SubmissionRequestContent {
    #[serde(rename = "x12")]
    pub x12: String,
}

impl InstitutionalClaimsRawX12SubmissionRequestContent {
    pub fn new(x12: String) -> InstitutionalClaimsRawX12SubmissionRequestContent {
        InstitutionalClaimsRawX12SubmissionRequestContent {
            x12,
        }
    }
}

