/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// InstitutionalOtherInsuredIdentifierTypeCode : Code identifying the type of identifier used for the other insured. Can be set to `II` - Standard Unique Health Identifier for each Individual in the United States or `MI` - Member Identification Number. Note that `II` is deprecated and should not be used in new claims.
/// Code identifying the type of identifier used for the other insured. Can be set to `II` - Standard Unique Health Identifier for each Individual in the United States or `MI` - Member Identification Number. Note that `II` is deprecated and should not be used in new claims.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstitutionalOtherInsuredIdentifierTypeCode {
    #[serde(rename = "II")]
    Ii,
    #[serde(rename = "MI")]
    Mi,

}

impl std::fmt::Display for InstitutionalOtherInsuredIdentifierTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ii => write!(f, "II"),
            Self::Mi => write!(f, "MI"),
        }
    }
}

impl Default for InstitutionalOtherInsuredIdentifierTypeCode {
    fn default() -> InstitutionalOtherInsuredIdentifierTypeCode {
        Self::Ii
    }
}

