/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalClaimAdjustmentDetails {
    /// The dollar amount of the adjustment, expressed as a decimal.
    #[serde(rename = "adjustmentAmount")]
    pub adjustment_amount: String,
    /// The units of service being adjusted, expressed as a decimal.
    #[serde(rename = "adjustmentQuantity", skip_serializing_if = "Option::is_none")]
    pub adjustment_quantity: Option<String>,
    /// Code identifying the detailed reason the adjustment was made. Visit the X12 [Claim Adjustment Reason Codes](https://x12.org/codes/claim-adjustment-reason-codes) for a complete list.
    #[serde(rename = "adjustmentReasonCode")]
    pub adjustment_reason_code: String,
}

impl InstitutionalClaimAdjustmentDetails {
    pub fn new(adjustment_amount: String, adjustment_reason_code: String) -> InstitutionalClaimAdjustmentDetails {
        InstitutionalClaimAdjustmentDetails {
            adjustment_amount,
            adjustment_quantity: None,
            adjustment_reason_code,
        }
    }
}

