/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// InstitutionalServiceFacilityLocation : The service facility location. Required when the location of healthcare services is different from the billing provider's address. - When an organization's healthcare provider's [NPI](https://www.stedi.com/docs/healthcare/national-provider-identifier) is provided to identify the service location, the organization healthcare provider must be external to the entity identified as the billing provider (for example, a reference lab). - The service location can't be a component or subpart of the billing provider entity. Only include this object when the service location is **different** from the billing provider's address. If you include this object when the address is the same, Stedi omits all of the service facility location information from the claim submission, including the name and any identifiers. - Sometimes the billing provider is an actual physician group that is located at the same address as a hospital, but is in fact a separate entity. In this case, you can differentiate the service facility location by including the specific suite or building number of the physician group. This ensures that the service facility location is different from the billing provider's address and is reported accurately.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalServiceFacilityLocation {
    /// The location where services were rendered.    If this was in an area where there are no street addresses, enter a description of where the service was rendered. For example, 'crossroad of State Road 34 and 45' or 'Exit near Mile marker 265 on Interstate 80'.
    #[serde(rename = "address")]
    pub address: Box<models::InstitutionalAddress>,
    /// The organization [National Provider Identifier (NPI)](https://www.stedi.com/docs/healthcare/national-provider-identifier) assigned to the service facility location. Required when the service location to be identified has an NPI and is not a component or subpart of the billing provider.
    #[serde(rename = "identificationCode", skip_serializing_if = "Option::is_none")]
    pub identification_code: Option<String>,
    /// The business name of the laboratory or facility.
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    #[serde(rename = "secondaryIdentificationQualifierCode", skip_serializing_if = "Option::is_none")]
    pub secondary_identification_qualifier_code: Option<models::ServiceFacilityLocationSecondaryIdentificationQualifierCode>,
    /// The identifier specified in `secondaryIdentifierQualifierCode`.  You can only include one secondary identifier for the service facility.
    #[serde(rename = "secondaryIdentifier", skip_serializing_if = "Option::is_none")]
    pub secondary_identifier: Option<String>,
}

impl InstitutionalServiceFacilityLocation {
    /// The service facility location. Required when the location of healthcare services is different from the billing provider's address. - When an organization's healthcare provider's [NPI](https://www.stedi.com/docs/healthcare/national-provider-identifier) is provided to identify the service location, the organization healthcare provider must be external to the entity identified as the billing provider (for example, a reference lab). - The service location can't be a component or subpart of the billing provider entity. Only include this object when the service location is **different** from the billing provider's address. If you include this object when the address is the same, Stedi omits all of the service facility location information from the claim submission, including the name and any identifiers. - Sometimes the billing provider is an actual physician group that is located at the same address as a hospital, but is in fact a separate entity. In this case, you can differentiate the service facility location by including the specific suite or building number of the physician group. This ensures that the service facility location is different from the billing provider's address and is reported accurately.
    pub fn new(address: models::InstitutionalAddress, organization_name: String) -> InstitutionalServiceFacilityLocation {
        InstitutionalServiceFacilityLocation {
            address: Box::new(address),
            identification_code: None,
            organization_name,
            secondary_identification_qualifier_code: None,
            secondary_identifier: None,
        }
    }
}

