/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// InstitutionalServiceLineReferringProvider : Information about the provider who referred the patient for care. - Include this object only when the referring provider is different than the provider listed in the `attending` object. - This should be an individual, not an organization, and you should supply at least the provider's `lastName` and an identifier, which is typically the `npi`.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalServiceLineReferringProvider {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::InstitutionalAddress>>,
    #[serde(rename = "commercialNumber", skip_serializing_if = "Option::is_none")]
    pub commercial_number: Option<String>,
    #[serde(rename = "contactInformation", skip_serializing_if = "Option::is_none")]
    pub contact_information: Option<Box<models::InstitutionalContactInformation>>,
    #[serde(rename = "employerId", skip_serializing_if = "Option::is_none")]
    pub employer_id: Option<String>,
    /// The provider's first name.
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The provider's last name.
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "locationNumber", skip_serializing_if = "Option::is_none")]
    pub location_number: Option<String>,
    /// The provider's middle name or initial.
    #[serde(rename = "middleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    /// The individual [National Provider Identifier (NPI)](https://www.stedi.com/docs/healthcare/national-provider-identifier) assigned to the provider.
    #[serde(rename = "npi", skip_serializing_if = "Option::is_none")]
    pub npi: Option<String>,
    /// The provider's business name.
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    /// This field is now automatically populated and it only remains for backwards compatibility.
    #[serde(rename = "providerType", skip_serializing_if = "Option::is_none")]
    pub provider_type: Option<models::ReferringProviderType>,
    #[serde(rename = "providerUpinNumber", skip_serializing_if = "Option::is_none")]
    pub provider_upin_number: Option<String>,
    /// Additional identifiers for the provider. You can set `qualifier` to `2U` - Payer Identification Number.
    #[serde(rename = "referenceIdentification", skip_serializing_if = "Option::is_none")]
    pub reference_identification: Option<Vec<models::InstitutionalReferenceIdentification>>,
    /// The type of identifier used in `secondaryIdentifier`. Can be set to `0B` - State License Number, `1G` - Provider UPIN Number, or `G2` - Provider Commercial Number. Note that UPIN is deprecated and should not be used.
    #[serde(rename = "secondaryIdentificationQualifierCode", skip_serializing_if = "Option::is_none")]
    pub secondary_identification_qualifier_code: Option<models::ServiceLineReferringProviderIdentificationQualifierCode>,
    /// The identifier specified in `secondaryIdentifierQualifierCode`.  You can only include one secondary identifier for the provider.
    #[serde(rename = "secondaryIdentifier", skip_serializing_if = "Option::is_none")]
    pub secondary_identifier: Option<String>,
    #[serde(rename = "stateLicenseNumber", skip_serializing_if = "Option::is_none")]
    pub state_license_number: Option<String>,
    /// The provider's suffix, such as Jr. or Sr.
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    #[serde(rename = "taxonomyCode", skip_serializing_if = "Option::is_none")]
    pub taxonomy_code: Option<String>,
}

impl InstitutionalServiceLineReferringProvider {
    /// Information about the provider who referred the patient for care. - Include this object only when the referring provider is different than the provider listed in the `attending` object. - This should be an individual, not an organization, and you should supply at least the provider's `lastName` and an identifier, which is typically the `npi`.
    pub fn new() -> InstitutionalServiceLineReferringProvider {
        InstitutionalServiceLineReferringProvider {
            address: None,
            commercial_number: None,
            contact_information: None,
            employer_id: None,
            first_name: None,
            last_name: None,
            location_number: None,
            middle_name: None,
            npi: None,
            organization_name: None,
            provider_type: None,
            provider_upin_number: None,
            reference_identification: None,
            secondary_identification_qualifier_code: None,
            secondary_identifier: None,
            state_license_number: None,
            suffix: None,
            taxonomy_code: None,
        }
    }
}

