/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstitutionalClaimInformationBenefitsAssignmentCertificationIndicator {
    #[serde(rename = "N")]
    N,
    #[serde(rename = "W")]
    W,
    #[serde(rename = "Y")]
    Y,

}

impl std::fmt::Display for InstitutionalClaimInformationBenefitsAssignmentCertificationIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::N => write!(f, "N"),
            Self::W => write!(f, "W"),
            Self::Y => write!(f, "Y"),
        }
    }
}

impl Default for InstitutionalClaimInformationBenefitsAssignmentCertificationIndicator {
    fn default() -> InstitutionalClaimInformationBenefitsAssignmentCertificationIndicator {
        Self::N
    }
}

