/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// InsuranceDiscoveryMetadata : Metadata about the response. Stedi uses this data for tracking and troubleshooting.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsuranceDiscoveryMetadata {
    /// The type of data in the request. This is always `production`.  Payers may sometimes return other non-compliant values.
    #[serde(rename = "applicationMode", skip_serializing_if = "Option::is_none")]
    pub application_mode: Option<models::ApplicationModes>,
    /// The unique ID Stedi assigns to this request.
    #[serde(rename = "traceId", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

impl InsuranceDiscoveryMetadata {
    /// Metadata about the response. Stedi uses this data for tracking and troubleshooting.
    pub fn new() -> InsuranceDiscoveryMetadata {
        InsuranceDiscoveryMetadata {
            application_mode: None,
            trace_id: None,
        }
    }
}

