/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinePricingInformation {
    #[serde(rename = "apgAmount", skip_serializing_if = "Option::is_none")]
    pub apg_amount: Option<String>,
    #[serde(rename = "apgCode", skip_serializing_if = "Option::is_none")]
    pub apg_code: Option<String>,
    #[serde(rename = "exceptionCode", skip_serializing_if = "Option::is_none")]
    pub exception_code: Option<models::InstitutionalClaimsExceptionCode>,
    #[serde(rename = "flatRateAmount", skip_serializing_if = "Option::is_none")]
    pub flat_rate_amount: Option<String>,
    #[serde(rename = "measurementUnitCode", skip_serializing_if = "Option::is_none")]
    pub measurement_unit_code: Option<models::InstitutionalMeasurementUnit>,
    #[serde(rename = "policyComplianceCode", skip_serializing_if = "Option::is_none")]
    pub policy_compliance_code: Option<models::PolicyComplianceCode>,
    #[serde(rename = "pricingMethodologyCode")]
    pub pricing_methodology_code: models::PricingMethodologyCode,
    #[serde(rename = "rejectReasonCode", skip_serializing_if = "Option::is_none")]
    pub reject_reason_code: Option<models::RejectReasonCode>,
    #[serde(rename = "repricedAllowedAmount")]
    pub repriced_allowed_amount: String,
    #[serde(rename = "repricedApprovedHCPCSCode", skip_serializing_if = "Option::is_none")]
    pub repriced_approved_hcpcs_code: Option<String>,
    #[serde(rename = "repricedApprovedServiceUnitCount", skip_serializing_if = "Option::is_none")]
    pub repriced_approved_service_unit_count: Option<String>,
    #[serde(rename = "repricedOrganizationIdentifier", skip_serializing_if = "Option::is_none")]
    pub repriced_organization_identifier: Option<String>,
    #[serde(rename = "repricedSavingAmount", skip_serializing_if = "Option::is_none")]
    pub repriced_saving_amount: Option<String>,
    #[serde(rename = "serviceIdQualifier", skip_serializing_if = "Option::is_none")]
    pub service_id_qualifier: Option<models::InstitutionalProcedureIdentifier>,
}

impl LinePricingInformation {
    pub fn new(pricing_methodology_code: models::PricingMethodologyCode, repriced_allowed_amount: String) -> LinePricingInformation {
        LinePricingInformation {
            apg_amount: None,
            apg_code: None,
            exception_code: None,
            flat_rate_amount: None,
            measurement_unit_code: None,
            policy_compliance_code: None,
            pricing_methodology_code,
            reject_reason_code: None,
            repriced_allowed_amount,
            repriced_approved_hcpcs_code: None,
            repriced_approved_service_unit_count: None,
            repriced_organization_identifier: None,
            repriced_saving_amount: None,
            service_id_qualifier: None,
        }
    }
}

