/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// MeasurementReferenceIdentificationCode : Code identifying the type of measurement. Can be set to `OG` - Original or `TR` - Test Results.
/// Code identifying the type of measurement. Can be set to `OG` - Original or `TR` - Test Results.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MeasurementReferenceIdentificationCode {
    #[serde(rename = "OG")]
    Og,
    #[serde(rename = "TR")]
    Tr,

}

impl std::fmt::Display for MeasurementReferenceIdentificationCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Og => write!(f, "OG"),
            Self::Tr => write!(f, "TR"),
        }
    }
}

impl Default for MeasurementReferenceIdentificationCode {
    fn default() -> MeasurementReferenceIdentificationCode {
        Self::Og
    }
}

