/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// MissingParameter : Returned when a required parameter is missing from the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MissingParameter {
    /// The error code `MISSING_PARAMETER`.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Additional details about the missing parameter error.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
    /// A message indicating which parameter is missing.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl MissingParameter {
    /// Returned when a required parameter is missing from the request.
    pub fn new() -> MissingParameter {
        MissingParameter {
            code: None,
            details: None,
            message: None,
        }
    }
}

