/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// Ordering : Deprecated; please use `claimInformation.serviceLines[].orderingProvider` instead.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ordering {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::ClaimsAddress>>,
    #[serde(rename = "claimOfficeNumber", skip_serializing_if = "Option::is_none")]
    pub claim_office_number: Option<String>,
    #[serde(rename = "commercialNumber", skip_serializing_if = "Option::is_none")]
    pub commercial_number: Option<String>,
    #[serde(rename = "contactInformation", skip_serializing_if = "Option::is_none")]
    pub contact_information: Option<Box<models::ClaimsContactInformation>>,
    #[serde(rename = "employerId", skip_serializing_if = "Option::is_none")]
    pub employer_id: Option<String>,
    #[serde(rename = "employerIdentificationNumber", skip_serializing_if = "Option::is_none")]
    pub employer_identification_number: Option<String>,
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "locationNumber", skip_serializing_if = "Option::is_none")]
    pub location_number: Option<String>,
    #[serde(rename = "middleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    #[serde(rename = "naic", skip_serializing_if = "Option::is_none")]
    pub naic: Option<String>,
    #[serde(rename = "npi", skip_serializing_if = "Option::is_none")]
    pub npi: Option<String>,
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    #[serde(rename = "payerIdentificationNumber", skip_serializing_if = "Option::is_none")]
    pub payer_identification_number: Option<String>,
    /// This field is now automatically populated and it only remains for backwards compatibility.
    #[serde(rename = "providerType", skip_serializing_if = "Option::is_none")]
    pub provider_type: Option<String>,
    #[serde(rename = "providerUpinNumber", skip_serializing_if = "Option::is_none")]
    pub provider_upin_number: Option<String>,
    /// Social Security Number without spaces or punctuation (9 digits)
    #[serde(rename = "ssn", skip_serializing_if = "Option::is_none")]
    pub ssn: Option<String>,
    #[serde(rename = "stateLicenseNumber", skip_serializing_if = "Option::is_none")]
    pub state_license_number: Option<String>,
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    #[serde(rename = "taxonomyCode", skip_serializing_if = "Option::is_none")]
    pub taxonomy_code: Option<String>,
}

impl Ordering {
    /// Deprecated; please use `claimInformation.serviceLines[].orderingProvider` instead.
    pub fn new() -> Ordering {
        Ordering {
            address: None,
            claim_office_number: None,
            commercial_number: None,
            contact_information: None,
            employer_id: None,
            employer_identification_number: None,
            first_name: None,
            last_name: None,
            location_number: None,
            middle_name: None,
            naic: None,
            npi: None,
            organization_name: None,
            payer_identification_number: None,
            provider_type: None,
            provider_upin_number: None,
            ssn: None,
            state_license_number: None,
            suffix: None,
            taxonomy_code: None,
        }
    }
}

