/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization1 {
    /// An organization's business name.
    #[serde(rename = "organization")]
    pub organization: String,
}

impl Organization1 {
    pub fn new(organization: String) -> Organization1 {
        Organization1 {
            organization,
        }
    }
}

