/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OtherDiagnosisInformationPresentOnAdmissionIndicator {
    #[serde(rename = "N")]
    N,
    #[serde(rename = "Y")]
    Y,
    #[serde(rename = "U")]
    U,
    #[serde(rename = "W")]
    W,

}

impl std::fmt::Display for OtherDiagnosisInformationPresentOnAdmissionIndicator {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::N => write!(f, "N"),
            Self::Y => write!(f, "Y"),
            Self::U => write!(f, "U"),
            Self::W => write!(f, "W"),
        }
    }
}

impl Default for OtherDiagnosisInformationPresentOnAdmissionIndicator {
    fn default() -> OtherDiagnosisInformationPresentOnAdmissionIndicator {
        Self::N
    }
}

