/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// PayToPlan : Use for subrogation payment requests. If you include this information, you must also set the `claimInformation.otherSubscriberInformation.payerPaidAmount` to the amount the payer (for example, Medicaid) actually paid.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayToPlan {
    /// The address of the pay-to-plan organization.
    #[serde(rename = "address")]
    pub address: Box<models::ClaimsAddress>,
    /// The last name of the individual, or the business name of the pay-to-plan organization.
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    /// The identifier you specified in `primaryIdentifierTypeCode`.
    #[serde(rename = "primaryIdentifier")]
    pub primary_identifier: String,
    #[serde(rename = "primaryIdentifierTypeCode")]
    pub primary_identifier_type_code: models::PrimaryIdentifierTypeCode,
    /// The secondary identifier you specified in `secondaryIdentifierTypeCode`.
    #[serde(rename = "secondaryIdentifier", skip_serializing_if = "Option::is_none")]
    pub secondary_identifier: Option<String>,
    #[serde(rename = "secondaryIdentifierTypeCode", skip_serializing_if = "Option::is_none")]
    pub secondary_identifier_type_code: Option<models::SecondaryIdentifierTypeCode>,
    /// The Employer Identification Number (EIN). This must be a string of exactly nine numbers with no separators.
    #[serde(rename = "taxIdentificationNumber")]
    pub tax_identification_number: String,
}

impl PayToPlan {
    /// Use for subrogation payment requests. If you include this information, you must also set the `claimInformation.otherSubscriberInformation.payerPaidAmount` to the amount the payer (for example, Medicaid) actually paid.
    pub fn new(address: models::ClaimsAddress, organization_name: String, primary_identifier: String, primary_identifier_type_code: models::PrimaryIdentifierTypeCode, tax_identification_number: String) -> PayToPlan {
        PayToPlan {
            address: Box::new(address),
            organization_name,
            primary_identifier,
            primary_identifier_type_code,
            secondary_identifier: None,
            secondary_identifier_type_code: None,
            tax_identification_number,
        }
    }
}

