/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// PayToPlanName : Use for subrogation payment requests. If you include this information, you must also set the `claimInformation.otherSubscriberInformation.payerPaidAmount` to the amount the payer (for example, Medicaid) actually paid.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PayToPlanName {
    /// Specify the location of the named party.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::InstitutionalAddress>>,
    /// The Claim Office Number.
    #[serde(rename = "claimOfficeNumber", skip_serializing_if = "Option::is_none")]
    pub claim_office_number: Option<String>,
    /// The identification code specified by the `identificationCodeQualifier`.
    #[serde(rename = "identificationCode")]
    pub identification_code: String,
    #[serde(rename = "identificationCodeQualifier")]
    pub identification_code_qualifier: models::PayToPlanNameIdentificationCodeQualifier,
    /// The National Association of Insurance Commisioners (NAIC) code. This is the five-digit identifier assigned to each insurance company.
    #[serde(rename = "naic", skip_serializing_if = "Option::is_none")]
    pub naic: Option<String>,
    /// The business name of the organization to which the payment should be made.
    #[serde(rename = "organizationName")]
    pub organization_name: String,
    /// The payer identification number. Only include this information when the `identificationCodeQualifier` is set to `XV` - Centers for Medicare and Medicaid Services PlanID.
    #[serde(rename = "payerIdentificationNumber", skip_serializing_if = "Option::is_none")]
    pub payer_identification_number: Option<String>,
    /// The payer tax identification number (TIN). This is a unique number assigned to the payer by the IRS.
    #[serde(rename = "taxId")]
    pub tax_id: String,
}

impl PayToPlanName {
    /// Use for subrogation payment requests. If you include this information, you must also set the `claimInformation.otherSubscriberInformation.payerPaidAmount` to the amount the payer (for example, Medicaid) actually paid.
    pub fn new(identification_code: String, identification_code_qualifier: models::PayToPlanNameIdentificationCodeQualifier, organization_name: String, tax_id: String) -> PayToPlanName {
        PayToPlanName {
            address: None,
            claim_office_number: None,
            identification_code,
            identification_code_qualifier,
            naic: None,
            organization_name,
            payer_identification_number: None,
            tax_id,
        }
    }
}

