/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// PaymentInfoInpatientAdjudication : Information about the adjudication of inpatient claims.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInfoInpatientAdjudication {
    /// The Diagnosis Related Group (DRG) amount.
    #[serde(rename = "claimDRGAmount", skip_serializing_if = "Option::is_none")]
    pub claim_drg_amount: Option<String>,
    /// The Disproportionate Share amount.
    #[serde(rename = "claimDisproportionateShareAmount", skip_serializing_if = "Option::is_none")]
    pub claim_disproportionate_share_amount: Option<String>,
    /// The indirect teaching amount.
    #[serde(rename = "claimIndirectTeachingAmount", skip_serializing_if = "Option::is_none")]
    pub claim_indirect_teaching_amount: Option<String>,
    /// The Medicare Secondary Payer (MSP) pass-through amount.
    #[serde(rename = "claimMSPPassThroughAmount", skip_serializing_if = "Option::is_none")]
    pub claim_msp_pass_through_amount: Option<String>,
    /// The total Prospective Payment System (PPS) capital amount.
    #[serde(rename = "claimPPSCapitalAmount", skip_serializing_if = "Option::is_none")]
    pub claim_pps_capital_amount: Option<String>,
    /// The Prospective Payment System (PPS) Capital Outlier amount.
    #[serde(rename = "claimPPSCapitalOutlierAmount", skip_serializing_if = "Option::is_none")]
    pub claim_pps_capital_outlier_amount: Option<String>,
    /// The [Claim Payment Remark Code](https://x12.org/codes/remittance-advice-remark-codes).
    #[serde(rename = "claimPaymentRemarkCode1", skip_serializing_if = "Option::is_none")]
    pub claim_payment_remark_code1: Option<String>,
    /// A [Claim Payment Remark Code](https://x12.org/codes/remittance-advice-remark-codes).
    #[serde(rename = "claimPaymentRemarkCode2", skip_serializing_if = "Option::is_none")]
    pub claim_payment_remark_code2: Option<String>,
    /// A [Claim Payment Remark Code](https://x12.org/codes/remittance-advice-remark-codes).
    #[serde(rename = "claimPaymentRemarkCode3", skip_serializing_if = "Option::is_none")]
    pub claim_payment_remark_code3: Option<String>,
    /// A [Claim Payment Remark Code](https://x12.org/codes/remittance-advice-remark-codes).
    #[serde(rename = "claimPaymentRemarkCode4", skip_serializing_if = "Option::is_none")]
    pub claim_payment_remark_code4: Option<String>,
    /// A [Claim Payment Remark Code](https://x12.org/codes/remittance-advice-remark-codes).
    #[serde(rename = "claimPaymentRemarkCode5", skip_serializing_if = "Option::is_none")]
    pub claim_payment_remark_code5: Option<String>,
    /// The number of cost report days.
    #[serde(rename = "costReportDayCount", skip_serializing_if = "Option::is_none")]
    pub cost_report_day_count: Option<String>,
    /// The number of days or visits covered by the health plan.
    #[serde(rename = "coveredDaysOrVisitsCount", skip_serializing_if = "Option::is_none")]
    pub covered_days_or_visits_count: Option<String>,
    /// The number of psychiatric days for the patient's lifetime.
    #[serde(rename = "lifetimePsychiatricDaysCount", skip_serializing_if = "Option::is_none")]
    pub lifetime_psychiatric_days_count: Option<String>,
    /// The professional component amount billed but not payable.
    #[serde(rename = "nonPayableProfessionalComponentAmount", skip_serializing_if = "Option::is_none")]
    pub non_payable_professional_component_amount: Option<String>,
    /// The old capital amount.
    #[serde(rename = "oldCapitalAmount", skip_serializing_if = "Option::is_none")]
    pub old_capital_amount: Option<String>,
    /// The Prospective Payment System (PPS) capital, disproportionate share, hospital Diagnosis Related Group (DRG) amount.
    #[serde(rename = "ppsCapitalDSHDRGAmount", skip_serializing_if = "Option::is_none")]
    pub pps_capital_dshdrg_amount: Option<String>,
    /// The capital exception amount.
    #[serde(rename = "ppsCapitalExceptionAmount", skip_serializing_if = "Option::is_none")]
    pub pps_capital_exception_amount: Option<String>,
    /// The Prospective Payment System (PPS) capital, federal specific portion, Diagnosis Related Group (DRG) amount.
    #[serde(rename = "ppsCapitalFSPDRGAmount", skip_serializing_if = "Option::is_none")]
    pub pps_capital_fspdrg_amount: Option<String>,
    /// The Prospective Payment System (PPS) capital, hospital specific portion, Diagnosis Related Group (DRG), amount.
    #[serde(rename = "ppsCapitalHSPDRGAmount", skip_serializing_if = "Option::is_none")]
    pub pps_capital_hspdrg_amount: Option<String>,
    /// The Prospective Payment System (PPS) capital indirect medical education claim amount.
    #[serde(rename = "ppsCapitalIMEAmount", skip_serializing_if = "Option::is_none")]
    pub pps_capital_ime_amount: Option<String>,
    /// The federal specific Diagnosis Related Group (DRG) amount.
    #[serde(rename = "ppsOperatingFederalSpecificDRGAmount", skip_serializing_if = "Option::is_none")]
    pub pps_operating_federal_specific_drg_amount: Option<String>,
    /// The hospital specific Diagnosis Related Group (DRG) Amount.
    #[serde(rename = "ppsOperatingHospitalSpecificDRGAmount", skip_serializing_if = "Option::is_none")]
    pub pps_operating_hospital_specific_drg_amount: Option<String>,
    /// The Prospective Payment System (PPS) Operating Outlier amount, expressed as a decimal.
    #[serde(rename = "ppsOperatingOutlierAmount", skip_serializing_if = "Option::is_none")]
    pub pps_operating_outlier_amount: Option<String>,
}

impl PaymentInfoInpatientAdjudication {
    /// Information about the adjudication of inpatient claims.
    pub fn new() -> PaymentInfoInpatientAdjudication {
        PaymentInfoInpatientAdjudication {
            claim_drg_amount: None,
            claim_disproportionate_share_amount: None,
            claim_indirect_teaching_amount: None,
            claim_msp_pass_through_amount: None,
            claim_pps_capital_amount: None,
            claim_pps_capital_outlier_amount: None,
            claim_payment_remark_code1: None,
            claim_payment_remark_code2: None,
            claim_payment_remark_code3: None,
            claim_payment_remark_code4: None,
            claim_payment_remark_code5: None,
            cost_report_day_count: None,
            covered_days_or_visits_count: None,
            lifetime_psychiatric_days_count: None,
            non_payable_professional_component_amount: None,
            old_capital_amount: None,
            pps_capital_dshdrg_amount: None,
            pps_capital_exception_amount: None,
            pps_capital_fspdrg_amount: None,
            pps_capital_hspdrg_amount: None,
            pps_capital_ime_amount: None,
            pps_operating_federal_specific_drg_amount: None,
            pps_operating_hospital_specific_drg_amount: None,
            pps_operating_outlier_amount: None,
        }
    }
}

