/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Person1 {
    /// The name of a provider who is a person.
    #[serde(rename = "person")]
    pub person: Box<models::EligibilityCheckRequestProviderPersonName>,
}

impl Person1 {
    pub fn new(person: models::EligibilityCheckRequestProviderPersonName) -> Person1 {
        Person1 {
            person: Box::new(person),
        }
    }
}

