/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrincipalProcedureInformation {
    /// The principal procedure code for the patient. It must be a valid code from the appropriate coding system. **Don't** submit the decimal for ICD codes; the decimal is implied.
    #[serde(rename = "principalProcedureCode")]
    pub principal_procedure_code: String,
    /// The date when the procedure was performed.
    #[serde(rename = "principalProcedureDate", skip_serializing_if = "Option::is_none")]
    pub principal_procedure_date: Option<String>,
    #[serde(rename = "qualifierCode")]
    pub qualifier_code: models::PrincipalProcedureInformationQualifierCode,
}

impl PrincipalProcedureInformation {
    pub fn new(principal_procedure_code: String, qualifier_code: models::PrincipalProcedureInformationQualifierCode) -> PrincipalProcedureInformation {
        PrincipalProcedureInformation {
            principal_procedure_code,
            principal_procedure_date: None,
            qualifier_code,
        }
    }
}

