/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ProviderEntityIdentifierCodeValue : Human-readable descriptions for provider entity identifier codes
/// Human-readable descriptions for provider entity identifier codes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderEntityIdentifierCodeValue {
    #[serde(rename = "Employer")]
    Employer,
    #[serde(rename = "Receiver")]
    Receiver,
    #[serde(rename = "Submitter")]
    Submitter,
    #[serde(rename = "Clearinghouse")]
    Clearinghouse,
    #[serde(rename = "Payer")]
    Payer,

}

impl std::fmt::Display for ProviderEntityIdentifierCodeValue {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Employer => write!(f, "Employer"),
            Self::Receiver => write!(f, "Receiver"),
            Self::Submitter => write!(f, "Submitter"),
            Self::Clearinghouse => write!(f, "Clearinghouse"),
            Self::Payer => write!(f, "Payer"),
        }
    }
}

impl Default for ProviderEntityIdentifierCodeValue {
    fn default() -> ProviderEntityIdentifierCodeValue {
        Self::Employer
    }
}

