/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ProviderType : Identify the type of provider.
/// Identify the type of provider.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderType {
    #[serde(rename = "payer")]
    Payer,
    #[serde(rename = "third-party administrator")]
    ThirdPartyAdministrator,
    #[serde(rename = "employer")]
    Employer,
    #[serde(rename = "hospital")]
    Hospital,
    #[serde(rename = "facility")]
    Facility,
    #[serde(rename = "gateway provider")]
    GatewayProvider,
    #[serde(rename = "plan sponsor")]
    PlanSponsor,
    #[serde(rename = "provider")]
    Provider,

}

impl std::fmt::Display for ProviderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Payer => write!(f, "payer"),
            Self::ThirdPartyAdministrator => write!(f, "third-party administrator"),
            Self::Employer => write!(f, "employer"),
            Self::Hospital => write!(f, "hospital"),
            Self::Facility => write!(f, "facility"),
            Self::GatewayProvider => write!(f, "gateway provider"),
            Self::PlanSponsor => write!(f, "plan sponsor"),
            Self::Provider => write!(f, "provider"),
        }
    }
}

impl Default for ProviderType {
    fn default() -> ProviderType {
        Self::Payer
    }
}

