/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// Rendering : Information about the person or company (laboratory or other facility) who rendered the care. Use this object for all types of rendering providers including laboratories. When a substitute provider (locum tenens) was used, enter that provider's information here. - Use when the provider applies to the entire claim or to at least one service line. For example, if a claim had two service lines with two different rendering providers, you would include the provider for the first service line here and leave the `claimInformation.serviceLines[].renderingProvider` object for that service line blank. Then, you would specify the second provider in the appropriate service line's `claimInformation.serviceLines[].renderingProvider` object. - You can omit this object when the rendering provider is the same as the billing provider. In that case, you would include the provider's information in the `billing` object and leave this object blank.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rendering {
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<Box<models::ClaimsAddress>>,
    /// The provider's commercial number.
    #[serde(rename = "commercialNumber", skip_serializing_if = "Option::is_none")]
    pub commercial_number: Option<String>,
    #[serde(rename = "contactInformation", skip_serializing_if = "Option::is_none")]
    pub contact_information: Option<Box<models::ClaimsContactInformation>>,
    /// The provider's first name, if the provider is an individual.
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The provider's last name, if the provider is an individual. You must include either the `lastName` or `organizationName` property in this object.
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// The provider's location number.
    #[serde(rename = "locationNumber", skip_serializing_if = "Option::is_none")]
    pub location_number: Option<String>,
    /// The provider's middle name or initial, if the provider is an individual.
    #[serde(rename = "middleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    /// The [National Provider Identifier (NPI)](https://www.stedi.com/docs/healthcare/national-provider-identifier) assigned to the provider.
    #[serde(rename = "npi", skip_serializing_if = "Option::is_none")]
    pub npi: Option<String>,
    /// The provider's business name, if the provider is an organization. You must include either the `lastName` or `organizationName` property in this object.
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    /// This field is now automatically populated and it only remains for backwards compatibility.
    #[serde(rename = "providerType", skip_serializing_if = "Option::is_none")]
    pub provider_type: Option<String>,
    /// Deprecated; do not use.
    #[serde(rename = "providerUpinNumber", skip_serializing_if = "Option::is_none")]
    pub provider_upin_number: Option<String>,
    /// The provider's state license number. This is assigned directly by a payer in order to identify the provider in their system. This is not commonly used.
    #[serde(rename = "stateLicenseNumber", skip_serializing_if = "Option::is_none")]
    pub state_license_number: Option<String>,
    /// The provider's name suffix, such as Jr. or III.
    #[serde(rename = "suffix", skip_serializing_if = "Option::is_none")]
    pub suffix: Option<String>,
    /// Code from the National Uniform Claims Committee [Health Care Provider Taxonomy Code Set](https://taxonomy.nucc.org/). This identifies the provider's type and/or area of specialty.
    #[serde(rename = "taxonomyCode", skip_serializing_if = "Option::is_none")]
    pub taxonomy_code: Option<String>,
}

impl Rendering {
    /// Information about the person or company (laboratory or other facility) who rendered the care. Use this object for all types of rendering providers including laboratories. When a substitute provider (locum tenens) was used, enter that provider's information here. - Use when the provider applies to the entire claim or to at least one service line. For example, if a claim had two service lines with two different rendering providers, you would include the provider for the first service line here and leave the `claimInformation.serviceLines[].renderingProvider` object for that service line blank. Then, you would specify the second provider in the appropriate service line's `claimInformation.serviceLines[].renderingProvider` object. - You can omit this object when the rendering provider is the same as the billing provider. In that case, you would include the provider's information in the `billing` object and leave this object blank.
    pub fn new() -> Rendering {
        Rendering {
            address: None,
            commercial_number: None,
            contact_information: None,
            first_name: None,
            last_name: None,
            location_number: None,
            middle_name: None,
            npi: None,
            organization_name: None,
            provider_type: None,
            provider_upin_number: None,
            state_license_number: None,
            suffix: None,
            taxonomy_code: None,
        }
    }
}

