/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// RenderingProviderType : Defines the rendering provider type.
/// Defines the rendering provider type.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RenderingProviderType {
    #[serde(rename = "RenderingProvider")]
    RenderingProvider,

}

impl std::fmt::Display for RenderingProviderType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RenderingProvider => write!(f, "RenderingProvider"),
        }
    }
}

impl Default for RenderingProviderType {
    fn default() -> RenderingProviderType {
        Self::RenderingProvider
    }
}

