/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportsClaims {
    /// Status information for the claim. This object includes the `referencedTransactionTraceNumber` you can use to correlate the 277CA with the original claim.
    #[serde(rename = "claimStatus", skip_serializing_if = "Option::is_none")]
    pub claim_status: Option<Box<models::ClaimsClaimStatus>>,
    /// Information about specific services within a claim. This object is only included in the 277CA when the claim is rejected because of errors with the service line information provided.
    #[serde(rename = "serviceLines", skip_serializing_if = "Option::is_none")]
    pub service_lines: Option<Vec<models::ClaimAcknowledgmentServiceLines>>,
}

impl ReportsClaims {
    pub fn new() -> ReportsClaims {
        ReportsClaims {
            claim_status: None,
            service_lines: None,
        }
    }
}

