/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// ResponseEligibilityServiceType : The name of a Service Type Code listed in the `serviceTypeCodes` array. Visit [Service Type Codes](https://www.stedi.com/docs/healthcare/send-eligibility-checks#service-type-codes) for a complete list of codes and their names.  The word physician in service type codes refers to any healthcare provider, including physician assistants, nurse practitioners, and other types of healthcare professionals.  Payers may sometimes return other non-compliant values.
/// The name of a Service Type Code listed in the `serviceTypeCodes` array. Visit [Service Type Codes](https://www.stedi.com/docs/healthcare/send-eligibility-checks#service-type-codes) for a complete list of codes and their names.  The word physician in service type codes refers to any healthcare provider, including physician assistants, nurse practitioners, and other types of healthcare professionals.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseEligibilityServiceType {
    #[serde(rename = "Medical Care")]
    MedicalCare,
    #[serde(rename = "Surgical")]
    Surgical,
    #[serde(rename = "Consultation")]
    Consultation,
    #[serde(rename = "Diagnostic X-Ray")]
    DiagnosticXRay,
    #[serde(rename = "Diagnostic Lab")]
    DiagnosticLab,
    #[serde(rename = "Radiation Therapy")]
    RadiationTherapy,
    #[serde(rename = "Anesthesia")]
    Anesthesia,
    #[serde(rename = "Surgical Assistance")]
    SurgicalAssistance,
    #[serde(rename = "Other Medical")]
    OtherMedical,
    #[serde(rename = "Blood Charges")]
    BloodCharges,
    #[serde(rename = "Used Durable Medical Equipment")]
    UsedDurableMedicalEquipment,
    #[serde(rename = "Durable Medical Equipment Purchase")]
    DurableMedicalEquipmentPurchase,
    #[serde(rename = "Ambulatory Service Center Facility")]
    AmbulatoryServiceCenterFacility,
    #[serde(rename = "Renal Supplies in the Home")]
    RenalSuppliesInTheHome,
    #[serde(rename = "Alternate Method Dialysis")]
    AlternateMethodDialysis,
    #[serde(rename = "Chronic Renal Disease (CRD) Equipment")]
    ChronicRenalDiseaseLeftParenthesisCrdRightParenthesisEquipment,
    #[serde(rename = "Pre-Admission Testing")]
    PreAdmissionTesting,
    #[serde(rename = "Durable Medical Equipment Rental")]
    DurableMedicalEquipmentRental,
    #[serde(rename = "Pneumonia Vaccine")]
    PneumoniaVaccine,
    #[serde(rename = "Second Surgical Opinion")]
    SecondSurgicalOpinion,
    #[serde(rename = "Third Surgical Opinion")]
    ThirdSurgicalOpinion,
    #[serde(rename = "Social Work")]
    SocialWork,
    #[serde(rename = "Diagnostic Dental")]
    DiagnosticDental,
    #[serde(rename = "Periodontics")]
    Periodontics,
    #[serde(rename = "Restorative")]
    Restorative,
    #[serde(rename = "Endodontics")]
    Endodontics,
    #[serde(rename = "Maxillofacial Prosthetics")]
    MaxillofacialProsthetics,
    #[serde(rename = "Adjunctive Dental Services")]
    AdjunctiveDentalServices,
    #[serde(rename = "Health Benefit Plan Coverage")]
    HealthBenefitPlanCoverage,
    #[serde(rename = "Plan Waiting Period")]
    PlanWaitingPeriod,
    #[serde(rename = "Chiropractic")]
    Chiropractic,
    #[serde(rename = "Chiropractic Office Visits")]
    ChiropracticOfficeVisits,
    #[serde(rename = "Dental Care")]
    DentalCare,
    #[serde(rename = "Dental Crowns")]
    DentalCrowns,
    #[serde(rename = "Dental Accident")]
    DentalAccident,
    #[serde(rename = "Orthodontics")]
    Orthodontics,
    #[serde(rename = "Prosthodontics")]
    Prosthodontics,
    #[serde(rename = "Oral Surgery")]
    OralSurgery,
    #[serde(rename = "Routine (Preventive) Dental")]
    RoutineLeftParenthesisPreventiveRightParenthesisDental,
    #[serde(rename = "Home Health Care")]
    HomeHealthCare,
    #[serde(rename = "Home Health Prescriptions")]
    HomeHealthPrescriptions,
    #[serde(rename = "Home Health Visits")]
    HomeHealthVisits,
    #[serde(rename = "Hospice")]
    Hospice,
    #[serde(rename = "Respite Care")]
    RespiteCare,
    #[serde(rename = "Hospital")]
    Hospital,
    #[serde(rename = "Hospital - Inpatient")]
    HospitalInpatient,
    #[serde(rename = "Hospital - Room and Board")]
    HospitalRoomAndBoard,
    #[serde(rename = "Hospital - Outpatient")]
    HospitalOutpatient,
    #[serde(rename = "Hospital - Emergency Accident")]
    HospitalEmergencyAccident,
    #[serde(rename = "Hospital - Emergency Medical")]
    HospitalEmergencyMedical,
    #[serde(rename = "Hospital - Ambulatory Surgical")]
    HospitalAmbulatorySurgical,
    #[serde(rename = "Long Term Care")]
    LongTermCare,
    #[serde(rename = "Major Medical")]
    MajorMedical,
    #[serde(rename = "Medically Related Transportation")]
    MedicallyRelatedTransportation,
    #[serde(rename = "Air Transportation")]
    AirTransportation,
    #[serde(rename = "Cabulance")]
    Cabulance,
    #[serde(rename = "Licensed Ambulance")]
    LicensedAmbulance,
    #[serde(rename = "General Benefits")]
    GeneralBenefits,
    #[serde(rename = "In-vitro Fertilization")]
    InVitroFertilization,
    #[serde(rename = "MRI/CAT Scan")]
    MriSlashCatScan,
    #[serde(rename = "Donor Procedures")]
    DonorProcedures,
    #[serde(rename = "Acupuncture")]
    Acupuncture,
    #[serde(rename = "Newborn Care")]
    NewbornCare,
    #[serde(rename = "Pathology")]
    Pathology,
    #[serde(rename = "Smoking Cessation")]
    SmokingCessation,
    #[serde(rename = "Well Baby Care")]
    WellBabyCare,
    #[serde(rename = "Maternity")]
    Maternity,
    #[serde(rename = "Transplants")]
    Transplants,
    #[serde(rename = "Audiology Exam")]
    AudiologyExam,
    #[serde(rename = "Inhalation Therapy")]
    InhalationTherapy,
    #[serde(rename = "Diagnostic Medical")]
    DiagnosticMedical,
    #[serde(rename = "Private Duty Nursing")]
    PrivateDutyNursing,
    #[serde(rename = "Prosthetic Device")]
    ProstheticDevice,
    #[serde(rename = "Dialysis")]
    Dialysis,
    #[serde(rename = "Otological Exam")]
    OtologicalExam,
    #[serde(rename = "Chemotherapy")]
    Chemotherapy,
    #[serde(rename = "Allergy Testing")]
    AllergyTesting,
    #[serde(rename = "Immunizations")]
    Immunizations,
    #[serde(rename = "Routine Physical")]
    RoutinePhysical,
    #[serde(rename = "Family Planning")]
    FamilyPlanning,
    #[serde(rename = "Infertility")]
    Infertility,
    #[serde(rename = "Abortion")]
    Abortion,
    #[serde(rename = "AIDS")]
    Aids,
    #[serde(rename = "Emergency Services")]
    EmergencyServices,
    #[serde(rename = "Cancer")]
    Cancer,
    #[serde(rename = "Pharmacy")]
    Pharmacy,
    #[serde(rename = "Free Standing Prescription Drug")]
    FreeStandingPrescriptionDrug,
    #[serde(rename = "Mail Order Prescription Drug")]
    MailOrderPrescriptionDrug,
    #[serde(rename = "Brand Name Prescription Drug")]
    BrandNamePrescriptionDrug,
    #[serde(rename = "Generic Prescription Drug")]
    GenericPrescriptionDrug,
    #[serde(rename = "Podiatry")]
    Podiatry,
    #[serde(rename = "Podiatry - Office Visits")]
    PodiatryOfficeVisits,
    #[serde(rename = "Podiatry - Nursing Home Visits")]
    PodiatryNursingHomeVisits,
    #[serde(rename = "Professional (Physician)")]
    ProfessionalLeftParenthesisPhysicianRightParenthesis,
    #[serde(rename = "Anesthesiologist")]
    Anesthesiologist,
    #[serde(rename = "Professional (Physician) Visit - Office")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitOffice,
    #[serde(rename = "Professional (Physician) Visit - Inpatient")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitInpatient,
    #[serde(rename = "Professional (Physician) Visit - Outpatient")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitOutpatient,
    #[serde(rename = "Professional (Physician) Visit - Nursing Home")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitNursingHome,
    #[serde(rename = "Professional (Physician) Visit - Skilled Nursing Facility")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitSkilledNursingFacility,
    #[serde(rename = "Professional (Physician) Visit - Home")]
    ProfessionalLeftParenthesisPhysicianRightParenthesisVisitHome,
    #[serde(rename = "Psychiatric")]
    Psychiatric,
    #[serde(rename = "Psychiatric - Room and Board")]
    PsychiatricRoomAndBoard,
    #[serde(rename = "Psychotherapy")]
    Psychotherapy,
    #[serde(rename = "Psychiatric - Inpatient")]
    PsychiatricInpatient,
    #[serde(rename = "Psychiatric - Outpatient")]
    PsychiatricOutpatient,
    #[serde(rename = "Rehabilitation")]
    Rehabilitation,
    #[serde(rename = "Rehabilitation - Room and Board")]
    RehabilitationRoomAndBoard,
    #[serde(rename = "Rehabilitation - Inpatient")]
    RehabilitationInpatient,
    #[serde(rename = "Rehabilitation - Outpatient")]
    RehabilitationOutpatient,
    #[serde(rename = "Occupational Therapy")]
    OccupationalTherapy,
    #[serde(rename = "Physical Medicine")]
    PhysicalMedicine,
    #[serde(rename = "Speech Therapy")]
    SpeechTherapy,
    #[serde(rename = "Skilled Nursing Care")]
    SkilledNursingCare,
    #[serde(rename = "Skilled Nursing Care - Room and Board")]
    SkilledNursingCareRoomAndBoard,
    #[serde(rename = "Substance Abuse")]
    SubstanceAbuse,
    #[serde(rename = "Alcoholism")]
    Alcoholism,
    #[serde(rename = "Drug Addiction")]
    DrugAddiction,
    #[serde(rename = "Vision (Optometry)")]
    VisionLeftParenthesisOptometryRightParenthesis,
    #[serde(rename = "Frames")]
    Frames,
    #[serde(rename = "Routine Exam")]
    RoutineExam,
    #[serde(rename = "Lenses")]
    Lenses,
    #[serde(rename = "Nonmedically Necessary Physical")]
    NonmedicallyNecessaryPhysical,
    #[serde(rename = "Experimental Drug Therapy")]
    ExperimentalDrugTherapy,
    #[serde(rename = "Burn Care")]
    BurnCare,
    #[serde(rename = "Brand Name Prescription Drug - Formulary")]
    BrandNamePrescriptionDrugFormulary,
    #[serde(rename = "Brand Name Prescription Drug - Non-Formulary")]
    BrandNamePrescriptionDrugNonFormulary,
    #[serde(rename = "Independent Medical Evaluation")]
    IndependentMedicalEvaluation,
    #[serde(rename = "Partial Hospitalization (Psychiatric)")]
    PartialHospitalizationLeftParenthesisPsychiatricRightParenthesis,
    #[serde(rename = "Day Care (Psychiatric)")]
    DayCareLeftParenthesisPsychiatricRightParenthesis,
    #[serde(rename = "Cognitive Therapy")]
    CognitiveTherapy,
    #[serde(rename = "Massage Therapy")]
    MassageTherapy,
    #[serde(rename = "Pulmonary Rehabilitation")]
    PulmonaryRehabilitation,
    #[serde(rename = "Cardiac Rehabilitation")]
    CardiacRehabilitation,
    #[serde(rename = "Pediatric")]
    Pediatric,
    #[serde(rename = "Nursery")]
    Nursery,
    #[serde(rename = "Skin")]
    Skin,
    #[serde(rename = "Orthopedic")]
    Orthopedic,
    #[serde(rename = "Cardiac")]
    Cardiac,
    #[serde(rename = "Lymphatic")]
    Lymphatic,
    #[serde(rename = "Gastrointestinal")]
    Gastrointestinal,
    #[serde(rename = "Endocrine")]
    Endocrine,
    #[serde(rename = "Neurology")]
    Neurology,
    #[serde(rename = "Eye")]
    Eye,
    #[serde(rename = "Invasive Procedures")]
    InvasiveProcedures,
    #[serde(rename = "Gynecological")]
    Gynecological,
    #[serde(rename = "Obstetrical")]
    Obstetrical,
    #[serde(rename = "Obstetrical/Gynecological")]
    ObstetricalSlashGynecological,
    #[serde(rename = "Mail Order Prescription Drug: Brand Name")]
    MailOrderPrescriptionDrugColonBrandName,
    #[serde(rename = "Mail Order Prescription Drug: Generic")]
    MailOrderPrescriptionDrugColonGeneric,
    #[serde(rename = "Physician Visit - Office: Sick")]
    PhysicianVisitOfficeColonSick,
    #[serde(rename = "Physician Visit - Office: Well")]
    PhysicianVisitOfficeColonWell,
    #[serde(rename = "Coronary Care")]
    CoronaryCare,
    #[serde(rename = "Private Duty Nursing - Inpatient")]
    PrivateDutyNursingInpatient,
    #[serde(rename = "Private Duty Nursing - Home")]
    PrivateDutyNursingHome,
    #[serde(rename = "Surgical Benefits - Professional (Physician)")]
    SurgicalBenefitsProfessionalLeftParenthesisPhysicianRightParenthesis,
    #[serde(rename = "Surgical Benefits - Facility")]
    SurgicalBenefitsFacility,
    #[serde(rename = "Mental Health Provider - Inpatient")]
    MentalHealthProviderInpatient,
    #[serde(rename = "Mental Health Provider - Outpatient")]
    MentalHealthProviderOutpatient,
    #[serde(rename = "Mental Health Facility - Inpatient")]
    MentalHealthFacilityInpatient,
    #[serde(rename = "Mental Health Facility - Outpatient")]
    MentalHealthFacilityOutpatient,
    #[serde(rename = "Substance Abuse Facility - Inpatient")]
    SubstanceAbuseFacilityInpatient,
    #[serde(rename = "Substance Abuse Facility - Outpatient")]
    SubstanceAbuseFacilityOutpatient,
    #[serde(rename = "Screening X-ray")]
    ScreeningXRay,
    #[serde(rename = "Screening laboratory")]
    ScreeningLaboratory,
    #[serde(rename = "Mammogram, High Risk Patient")]
    MammogramCommaHighRiskPatient,
    #[serde(rename = "Mammogram, Low Risk Patient")]
    MammogramCommaLowRiskPatient,
    #[serde(rename = "Flu Vaccination")]
    FluVaccination,
    #[serde(rename = "Eyewear and Eyewear Accessories")]
    EyewearAndEyewearAccessories,
    #[serde(rename = "Case Management")]
    CaseManagement,
    #[serde(rename = "Dermatology")]
    Dermatology,
    #[serde(rename = "Durable Medical Equipment")]
    DurableMedicalEquipment,
    #[serde(rename = "Diabetic Supplies")]
    DiabeticSupplies,
    #[serde(rename = "Generic Prescription Drug - Formulary")]
    GenericPrescriptionDrugFormulary,
    #[serde(rename = "Generic Prescription Drug - Non-Formulary")]
    GenericPrescriptionDrugNonFormulary,
    #[serde(rename = "Allergy")]
    Allergy,
    #[serde(rename = "Intensive Care")]
    IntensiveCare,
    #[serde(rename = "Mental Health")]
    MentalHealth,
    #[serde(rename = "Neonatal Intensive Care")]
    NeonatalIntensiveCare,
    #[serde(rename = "Oncology")]
    Oncology,
    #[serde(rename = "Physical Therapy")]
    PhysicalTherapy,
    #[serde(rename = "Pulmonary")]
    Pulmonary,
    #[serde(rename = "Renal")]
    Renal,
    #[serde(rename = "Residential Psychiatric Treatment")]
    ResidentialPsychiatricTreatment,
    #[serde(rename = "Transitional Care")]
    TransitionalCare,
    #[serde(rename = "Transitional Nursery Care")]
    TransitionalNurseryCare,
    #[serde(rename = "Urgent Care")]
    UrgentCare,
    #[serde(rename = "Diagnostic Imaging")]
    DiagnosticImaging,
    #[serde(rename = "Fixed Prosthodontics")]
    FixedProsthodontics,
    #[serde(rename = "Removable Prosthodontics")]
    RemovableProsthodontics,
    #[serde(rename = "Intraoral Images - Complete Series")]
    IntraoralImagesCompleteSeries,
    #[serde(rename = "Oral Evaluation")]
    OralEvaluation,
    #[serde(rename = "Dental Prophylaxis")]
    DentalProphylaxis,
    #[serde(rename = "Panoramic Images")]
    PanoramicImages,
    #[serde(rename = "Sealants")]
    Sealants,
    #[serde(rename = "Fluoride Treatments")]
    FluorideTreatments,
    #[serde(rename = "Dental Implants")]
    DentalImplants,
    #[serde(rename = "Temporomandibular Joint Dysfunction")]
    TemporomandibularJointDysfunction,
    #[serde(rename = "Prescription Fluoride Toothpaste")]
    PrescriptionFluorideToothpaste,
    #[serde(rename = "Antimicrobial Rinse")]
    AntimicrobialRinse,
    #[serde(rename = "Major Oral Surgery")]
    MajorOralSurgery,
    #[serde(rename = "Orthognathics")]
    Orthognathics,
    #[serde(rename = "Amalgam Restorations")]
    AmalgamRestorations,
    #[serde(rename = "Posterior Composite Restorations")]
    PosteriorCompositeRestorations,
    #[serde(rename = "Simple Extraction")]
    SimpleExtraction,
    #[serde(rename = "Bridges")]
    Bridges,
    #[serde(rename = "Bitewing X-Rays")]
    BitewingXRays,
    #[serde(rename = "Occlusal & Extraoral X-Rays")]
    OcclusalAmpersandExtraoralXRays,
    #[serde(rename = "Periapical X-Ray")]
    PeriapicalXRay,
    #[serde(rename = "Full Mouth X-Rays")]
    FullMouthXRays,
    #[serde(rename = "Space Maintenance")]
    SpaceMaintenance,
    #[serde(rename = "Occlusal Adjustments")]
    OcclusalAdjustments,
    #[serde(rename = "Restorative - Major")]
    RestorativeMajor,
    #[serde(rename = "Restorative - Routine")]
    RestorativeRoutine,
    #[serde(rename = "Additional Diagnostic and Preventive")]
    AdditionalDiagnosticAndPreventive,
    #[serde(rename = "Surgical Periodontics")]
    SurgicalPeriodontics,
    #[serde(rename = "Non-Surgical Periodontics")]
    NonSurgicalPeriodontics,
    #[serde(rename = "Repair Crown")]
    RepairCrown,
    #[serde(rename = "Recement Crown")]
    RecementCrown,
    #[serde(rename = "Basic")]
    Basic,
    #[serde(rename = "Denture Adjust, Rebase, Reline, Repair")]
    DentureAdjustCommaRebaseCommaRelineCommaRepair,
    #[serde(rename = "Restorative - Other")]
    RestorativeOther,
    #[serde(rename = "Root Planing & Scaling")]
    RootPlaningAmpersandScaling,
    #[serde(rename = "Simple Restorations")]
    SimpleRestorations,
    #[serde(rename = "Stainless Crowns")]
    StainlessCrowns,
    #[serde(rename = "Crowns")]
    Crowns,
    #[serde(rename = "Harmful Habits Appliance")]
    HarmfulHabitsAppliance,
    #[serde(rename = "Buildups / Post and Core")]
    BuildupsSlashPostAndCore,
    #[serde(rename = "Inlay / Onlay")]
    InlaySlashOnlay,
    #[serde(rename = "Amalgam / Composite Restorations")]
    AmalgamSlashCompositeRestorations,
    #[serde(rename = "Dentures")]
    Dentures,
    #[serde(rename = "Dentures - Repair")]
    DenturesRepair,
    #[serde(rename = "Dentures - Reline")]
    DenturesReline,
    #[serde(rename = "Dentures - Rebase")]
    DenturesRebase,
    #[serde(rename = "Full Mouth / Panoramic X-Rays")]
    FullMouthSlashPanoramicXRays,
    #[serde(rename = "Composites")]
    Composites,
    #[serde(rename = "Stainless Steel, Resin, Acrylic Crowns")]
    StainlessSteelCommaResinCommaAcrylicCrowns,
    #[serde(rename = "Root Canal / Retreatment")]
    RootCanalSlashRetreatment,
    #[serde(rename = "Dentures - Adjustments")]
    DenturesAdjustments,
    #[serde(rename = "Dentures - Reline / Rebase")]
    DenturesRelineSlashRebase,
    #[serde(rename = "Tissue Conditioning")]
    TissueConditioning,
    #[serde(rename = "Cosmetic")]
    Cosmetic,
    #[serde(rename = "Emergency Care")]
    EmergencyCare,

}

impl std::fmt::Display for ResponseEligibilityServiceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::MedicalCare => write!(f, "Medical Care"),
            Self::Surgical => write!(f, "Surgical"),
            Self::Consultation => write!(f, "Consultation"),
            Self::DiagnosticXRay => write!(f, "Diagnostic X-Ray"),
            Self::DiagnosticLab => write!(f, "Diagnostic Lab"),
            Self::RadiationTherapy => write!(f, "Radiation Therapy"),
            Self::Anesthesia => write!(f, "Anesthesia"),
            Self::SurgicalAssistance => write!(f, "Surgical Assistance"),
            Self::OtherMedical => write!(f, "Other Medical"),
            Self::BloodCharges => write!(f, "Blood Charges"),
            Self::UsedDurableMedicalEquipment => write!(f, "Used Durable Medical Equipment"),
            Self::DurableMedicalEquipmentPurchase => write!(f, "Durable Medical Equipment Purchase"),
            Self::AmbulatoryServiceCenterFacility => write!(f, "Ambulatory Service Center Facility"),
            Self::RenalSuppliesInTheHome => write!(f, "Renal Supplies in the Home"),
            Self::AlternateMethodDialysis => write!(f, "Alternate Method Dialysis"),
            Self::ChronicRenalDiseaseLeftParenthesisCrdRightParenthesisEquipment => write!(f, "Chronic Renal Disease (CRD) Equipment"),
            Self::PreAdmissionTesting => write!(f, "Pre-Admission Testing"),
            Self::DurableMedicalEquipmentRental => write!(f, "Durable Medical Equipment Rental"),
            Self::PneumoniaVaccine => write!(f, "Pneumonia Vaccine"),
            Self::SecondSurgicalOpinion => write!(f, "Second Surgical Opinion"),
            Self::ThirdSurgicalOpinion => write!(f, "Third Surgical Opinion"),
            Self::SocialWork => write!(f, "Social Work"),
            Self::DiagnosticDental => write!(f, "Diagnostic Dental"),
            Self::Periodontics => write!(f, "Periodontics"),
            Self::Restorative => write!(f, "Restorative"),
            Self::Endodontics => write!(f, "Endodontics"),
            Self::MaxillofacialProsthetics => write!(f, "Maxillofacial Prosthetics"),
            Self::AdjunctiveDentalServices => write!(f, "Adjunctive Dental Services"),
            Self::HealthBenefitPlanCoverage => write!(f, "Health Benefit Plan Coverage"),
            Self::PlanWaitingPeriod => write!(f, "Plan Waiting Period"),
            Self::Chiropractic => write!(f, "Chiropractic"),
            Self::ChiropracticOfficeVisits => write!(f, "Chiropractic Office Visits"),
            Self::DentalCare => write!(f, "Dental Care"),
            Self::DentalCrowns => write!(f, "Dental Crowns"),
            Self::DentalAccident => write!(f, "Dental Accident"),
            Self::Orthodontics => write!(f, "Orthodontics"),
            Self::Prosthodontics => write!(f, "Prosthodontics"),
            Self::OralSurgery => write!(f, "Oral Surgery"),
            Self::RoutineLeftParenthesisPreventiveRightParenthesisDental => write!(f, "Routine (Preventive) Dental"),
            Self::HomeHealthCare => write!(f, "Home Health Care"),
            Self::HomeHealthPrescriptions => write!(f, "Home Health Prescriptions"),
            Self::HomeHealthVisits => write!(f, "Home Health Visits"),
            Self::Hospice => write!(f, "Hospice"),
            Self::RespiteCare => write!(f, "Respite Care"),
            Self::Hospital => write!(f, "Hospital"),
            Self::HospitalInpatient => write!(f, "Hospital - Inpatient"),
            Self::HospitalRoomAndBoard => write!(f, "Hospital - Room and Board"),
            Self::HospitalOutpatient => write!(f, "Hospital - Outpatient"),
            Self::HospitalEmergencyAccident => write!(f, "Hospital - Emergency Accident"),
            Self::HospitalEmergencyMedical => write!(f, "Hospital - Emergency Medical"),
            Self::HospitalAmbulatorySurgical => write!(f, "Hospital - Ambulatory Surgical"),
            Self::LongTermCare => write!(f, "Long Term Care"),
            Self::MajorMedical => write!(f, "Major Medical"),
            Self::MedicallyRelatedTransportation => write!(f, "Medically Related Transportation"),
            Self::AirTransportation => write!(f, "Air Transportation"),
            Self::Cabulance => write!(f, "Cabulance"),
            Self::LicensedAmbulance => write!(f, "Licensed Ambulance"),
            Self::GeneralBenefits => write!(f, "General Benefits"),
            Self::InVitroFertilization => write!(f, "In-vitro Fertilization"),
            Self::MriSlashCatScan => write!(f, "MRI/CAT Scan"),
            Self::DonorProcedures => write!(f, "Donor Procedures"),
            Self::Acupuncture => write!(f, "Acupuncture"),
            Self::NewbornCare => write!(f, "Newborn Care"),
            Self::Pathology => write!(f, "Pathology"),
            Self::SmokingCessation => write!(f, "Smoking Cessation"),
            Self::WellBabyCare => write!(f, "Well Baby Care"),
            Self::Maternity => write!(f, "Maternity"),
            Self::Transplants => write!(f, "Transplants"),
            Self::AudiologyExam => write!(f, "Audiology Exam"),
            Self::InhalationTherapy => write!(f, "Inhalation Therapy"),
            Self::DiagnosticMedical => write!(f, "Diagnostic Medical"),
            Self::PrivateDutyNursing => write!(f, "Private Duty Nursing"),
            Self::ProstheticDevice => write!(f, "Prosthetic Device"),
            Self::Dialysis => write!(f, "Dialysis"),
            Self::OtologicalExam => write!(f, "Otological Exam"),
            Self::Chemotherapy => write!(f, "Chemotherapy"),
            Self::AllergyTesting => write!(f, "Allergy Testing"),
            Self::Immunizations => write!(f, "Immunizations"),
            Self::RoutinePhysical => write!(f, "Routine Physical"),
            Self::FamilyPlanning => write!(f, "Family Planning"),
            Self::Infertility => write!(f, "Infertility"),
            Self::Abortion => write!(f, "Abortion"),
            Self::Aids => write!(f, "AIDS"),
            Self::EmergencyServices => write!(f, "Emergency Services"),
            Self::Cancer => write!(f, "Cancer"),
            Self::Pharmacy => write!(f, "Pharmacy"),
            Self::FreeStandingPrescriptionDrug => write!(f, "Free Standing Prescription Drug"),
            Self::MailOrderPrescriptionDrug => write!(f, "Mail Order Prescription Drug"),
            Self::BrandNamePrescriptionDrug => write!(f, "Brand Name Prescription Drug"),
            Self::GenericPrescriptionDrug => write!(f, "Generic Prescription Drug"),
            Self::Podiatry => write!(f, "Podiatry"),
            Self::PodiatryOfficeVisits => write!(f, "Podiatry - Office Visits"),
            Self::PodiatryNursingHomeVisits => write!(f, "Podiatry - Nursing Home Visits"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesis => write!(f, "Professional (Physician)"),
            Self::Anesthesiologist => write!(f, "Anesthesiologist"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitOffice => write!(f, "Professional (Physician) Visit - Office"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitInpatient => write!(f, "Professional (Physician) Visit - Inpatient"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitOutpatient => write!(f, "Professional (Physician) Visit - Outpatient"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitNursingHome => write!(f, "Professional (Physician) Visit - Nursing Home"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitSkilledNursingFacility => write!(f, "Professional (Physician) Visit - Skilled Nursing Facility"),
            Self::ProfessionalLeftParenthesisPhysicianRightParenthesisVisitHome => write!(f, "Professional (Physician) Visit - Home"),
            Self::Psychiatric => write!(f, "Psychiatric"),
            Self::PsychiatricRoomAndBoard => write!(f, "Psychiatric - Room and Board"),
            Self::Psychotherapy => write!(f, "Psychotherapy"),
            Self::PsychiatricInpatient => write!(f, "Psychiatric - Inpatient"),
            Self::PsychiatricOutpatient => write!(f, "Psychiatric - Outpatient"),
            Self::Rehabilitation => write!(f, "Rehabilitation"),
            Self::RehabilitationRoomAndBoard => write!(f, "Rehabilitation - Room and Board"),
            Self::RehabilitationInpatient => write!(f, "Rehabilitation - Inpatient"),
            Self::RehabilitationOutpatient => write!(f, "Rehabilitation - Outpatient"),
            Self::OccupationalTherapy => write!(f, "Occupational Therapy"),
            Self::PhysicalMedicine => write!(f, "Physical Medicine"),
            Self::SpeechTherapy => write!(f, "Speech Therapy"),
            Self::SkilledNursingCare => write!(f, "Skilled Nursing Care"),
            Self::SkilledNursingCareRoomAndBoard => write!(f, "Skilled Nursing Care - Room and Board"),
            Self::SubstanceAbuse => write!(f, "Substance Abuse"),
            Self::Alcoholism => write!(f, "Alcoholism"),
            Self::DrugAddiction => write!(f, "Drug Addiction"),
            Self::VisionLeftParenthesisOptometryRightParenthesis => write!(f, "Vision (Optometry)"),
            Self::Frames => write!(f, "Frames"),
            Self::RoutineExam => write!(f, "Routine Exam"),
            Self::Lenses => write!(f, "Lenses"),
            Self::NonmedicallyNecessaryPhysical => write!(f, "Nonmedically Necessary Physical"),
            Self::ExperimentalDrugTherapy => write!(f, "Experimental Drug Therapy"),
            Self::BurnCare => write!(f, "Burn Care"),
            Self::BrandNamePrescriptionDrugFormulary => write!(f, "Brand Name Prescription Drug - Formulary"),
            Self::BrandNamePrescriptionDrugNonFormulary => write!(f, "Brand Name Prescription Drug - Non-Formulary"),
            Self::IndependentMedicalEvaluation => write!(f, "Independent Medical Evaluation"),
            Self::PartialHospitalizationLeftParenthesisPsychiatricRightParenthesis => write!(f, "Partial Hospitalization (Psychiatric)"),
            Self::DayCareLeftParenthesisPsychiatricRightParenthesis => write!(f, "Day Care (Psychiatric)"),
            Self::CognitiveTherapy => write!(f, "Cognitive Therapy"),
            Self::MassageTherapy => write!(f, "Massage Therapy"),
            Self::PulmonaryRehabilitation => write!(f, "Pulmonary Rehabilitation"),
            Self::CardiacRehabilitation => write!(f, "Cardiac Rehabilitation"),
            Self::Pediatric => write!(f, "Pediatric"),
            Self::Nursery => write!(f, "Nursery"),
            Self::Skin => write!(f, "Skin"),
            Self::Orthopedic => write!(f, "Orthopedic"),
            Self::Cardiac => write!(f, "Cardiac"),
            Self::Lymphatic => write!(f, "Lymphatic"),
            Self::Gastrointestinal => write!(f, "Gastrointestinal"),
            Self::Endocrine => write!(f, "Endocrine"),
            Self::Neurology => write!(f, "Neurology"),
            Self::Eye => write!(f, "Eye"),
            Self::InvasiveProcedures => write!(f, "Invasive Procedures"),
            Self::Gynecological => write!(f, "Gynecological"),
            Self::Obstetrical => write!(f, "Obstetrical"),
            Self::ObstetricalSlashGynecological => write!(f, "Obstetrical/Gynecological"),
            Self::MailOrderPrescriptionDrugColonBrandName => write!(f, "Mail Order Prescription Drug: Brand Name"),
            Self::MailOrderPrescriptionDrugColonGeneric => write!(f, "Mail Order Prescription Drug: Generic"),
            Self::PhysicianVisitOfficeColonSick => write!(f, "Physician Visit - Office: Sick"),
            Self::PhysicianVisitOfficeColonWell => write!(f, "Physician Visit - Office: Well"),
            Self::CoronaryCare => write!(f, "Coronary Care"),
            Self::PrivateDutyNursingInpatient => write!(f, "Private Duty Nursing - Inpatient"),
            Self::PrivateDutyNursingHome => write!(f, "Private Duty Nursing - Home"),
            Self::SurgicalBenefitsProfessionalLeftParenthesisPhysicianRightParenthesis => write!(f, "Surgical Benefits - Professional (Physician)"),
            Self::SurgicalBenefitsFacility => write!(f, "Surgical Benefits - Facility"),
            Self::MentalHealthProviderInpatient => write!(f, "Mental Health Provider - Inpatient"),
            Self::MentalHealthProviderOutpatient => write!(f, "Mental Health Provider - Outpatient"),
            Self::MentalHealthFacilityInpatient => write!(f, "Mental Health Facility - Inpatient"),
            Self::MentalHealthFacilityOutpatient => write!(f, "Mental Health Facility - Outpatient"),
            Self::SubstanceAbuseFacilityInpatient => write!(f, "Substance Abuse Facility - Inpatient"),
            Self::SubstanceAbuseFacilityOutpatient => write!(f, "Substance Abuse Facility - Outpatient"),
            Self::ScreeningXRay => write!(f, "Screening X-ray"),
            Self::ScreeningLaboratory => write!(f, "Screening laboratory"),
            Self::MammogramCommaHighRiskPatient => write!(f, "Mammogram, High Risk Patient"),
            Self::MammogramCommaLowRiskPatient => write!(f, "Mammogram, Low Risk Patient"),
            Self::FluVaccination => write!(f, "Flu Vaccination"),
            Self::EyewearAndEyewearAccessories => write!(f, "Eyewear and Eyewear Accessories"),
            Self::CaseManagement => write!(f, "Case Management"),
            Self::Dermatology => write!(f, "Dermatology"),
            Self::DurableMedicalEquipment => write!(f, "Durable Medical Equipment"),
            Self::DiabeticSupplies => write!(f, "Diabetic Supplies"),
            Self::GenericPrescriptionDrugFormulary => write!(f, "Generic Prescription Drug - Formulary"),
            Self::GenericPrescriptionDrugNonFormulary => write!(f, "Generic Prescription Drug - Non-Formulary"),
            Self::Allergy => write!(f, "Allergy"),
            Self::IntensiveCare => write!(f, "Intensive Care"),
            Self::MentalHealth => write!(f, "Mental Health"),
            Self::NeonatalIntensiveCare => write!(f, "Neonatal Intensive Care"),
            Self::Oncology => write!(f, "Oncology"),
            Self::PhysicalTherapy => write!(f, "Physical Therapy"),
            Self::Pulmonary => write!(f, "Pulmonary"),
            Self::Renal => write!(f, "Renal"),
            Self::ResidentialPsychiatricTreatment => write!(f, "Residential Psychiatric Treatment"),
            Self::TransitionalCare => write!(f, "Transitional Care"),
            Self::TransitionalNurseryCare => write!(f, "Transitional Nursery Care"),
            Self::UrgentCare => write!(f, "Urgent Care"),
            Self::DiagnosticImaging => write!(f, "Diagnostic Imaging"),
            Self::FixedProsthodontics => write!(f, "Fixed Prosthodontics"),
            Self::RemovableProsthodontics => write!(f, "Removable Prosthodontics"),
            Self::IntraoralImagesCompleteSeries => write!(f, "Intraoral Images - Complete Series"),
            Self::OralEvaluation => write!(f, "Oral Evaluation"),
            Self::DentalProphylaxis => write!(f, "Dental Prophylaxis"),
            Self::PanoramicImages => write!(f, "Panoramic Images"),
            Self::Sealants => write!(f, "Sealants"),
            Self::FluorideTreatments => write!(f, "Fluoride Treatments"),
            Self::DentalImplants => write!(f, "Dental Implants"),
            Self::TemporomandibularJointDysfunction => write!(f, "Temporomandibular Joint Dysfunction"),
            Self::PrescriptionFluorideToothpaste => write!(f, "Prescription Fluoride Toothpaste"),
            Self::AntimicrobialRinse => write!(f, "Antimicrobial Rinse"),
            Self::MajorOralSurgery => write!(f, "Major Oral Surgery"),
            Self::Orthognathics => write!(f, "Orthognathics"),
            Self::AmalgamRestorations => write!(f, "Amalgam Restorations"),
            Self::PosteriorCompositeRestorations => write!(f, "Posterior Composite Restorations"),
            Self::SimpleExtraction => write!(f, "Simple Extraction"),
            Self::Bridges => write!(f, "Bridges"),
            Self::BitewingXRays => write!(f, "Bitewing X-Rays"),
            Self::OcclusalAmpersandExtraoralXRays => write!(f, "Occlusal & Extraoral X-Rays"),
            Self::PeriapicalXRay => write!(f, "Periapical X-Ray"),
            Self::FullMouthXRays => write!(f, "Full Mouth X-Rays"),
            Self::SpaceMaintenance => write!(f, "Space Maintenance"),
            Self::OcclusalAdjustments => write!(f, "Occlusal Adjustments"),
            Self::RestorativeMajor => write!(f, "Restorative - Major"),
            Self::RestorativeRoutine => write!(f, "Restorative - Routine"),
            Self::AdditionalDiagnosticAndPreventive => write!(f, "Additional Diagnostic and Preventive"),
            Self::SurgicalPeriodontics => write!(f, "Surgical Periodontics"),
            Self::NonSurgicalPeriodontics => write!(f, "Non-Surgical Periodontics"),
            Self::RepairCrown => write!(f, "Repair Crown"),
            Self::RecementCrown => write!(f, "Recement Crown"),
            Self::Basic => write!(f, "Basic"),
            Self::DentureAdjustCommaRebaseCommaRelineCommaRepair => write!(f, "Denture Adjust, Rebase, Reline, Repair"),
            Self::RestorativeOther => write!(f, "Restorative - Other"),
            Self::RootPlaningAmpersandScaling => write!(f, "Root Planing & Scaling"),
            Self::SimpleRestorations => write!(f, "Simple Restorations"),
            Self::StainlessCrowns => write!(f, "Stainless Crowns"),
            Self::Crowns => write!(f, "Crowns"),
            Self::HarmfulHabitsAppliance => write!(f, "Harmful Habits Appliance"),
            Self::BuildupsSlashPostAndCore => write!(f, "Buildups / Post and Core"),
            Self::InlaySlashOnlay => write!(f, "Inlay / Onlay"),
            Self::AmalgamSlashCompositeRestorations => write!(f, "Amalgam / Composite Restorations"),
            Self::Dentures => write!(f, "Dentures"),
            Self::DenturesRepair => write!(f, "Dentures - Repair"),
            Self::DenturesReline => write!(f, "Dentures - Reline"),
            Self::DenturesRebase => write!(f, "Dentures - Rebase"),
            Self::FullMouthSlashPanoramicXRays => write!(f, "Full Mouth / Panoramic X-Rays"),
            Self::Composites => write!(f, "Composites"),
            Self::StainlessSteelCommaResinCommaAcrylicCrowns => write!(f, "Stainless Steel, Resin, Acrylic Crowns"),
            Self::RootCanalSlashRetreatment => write!(f, "Root Canal / Retreatment"),
            Self::DenturesAdjustments => write!(f, "Dentures - Adjustments"),
            Self::DenturesRelineSlashRebase => write!(f, "Dentures - Reline / Rebase"),
            Self::TissueConditioning => write!(f, "Tissue Conditioning"),
            Self::Cosmetic => write!(f, "Cosmetic"),
            Self::EmergencyCare => write!(f, "Emergency Care"),
        }
    }
}

impl Default for ResponseEligibilityServiceType {
    fn default() -> ResponseEligibilityServiceType {
        Self::MedicalCare
    }
}

