/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// SecondaryIdentifierTypeCode : Code identifying the type of secondary identifier. Can be set to `2U` - Payer Identification Number, `FY` - Claim Office Number, or `NF` - National Association of Insurance Commissioners. You should only set this to `2U` when you set the `primaryIdentifierTypeCode` to `XV`.
/// Code identifying the type of secondary identifier. Can be set to `2U` - Payer Identification Number, `FY` - Claim Office Number, or `NF` - National Association of Insurance Commissioners. You should only set this to `2U` when you set the `primaryIdentifierTypeCode` to `XV`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecondaryIdentifierTypeCode {
    #[serde(rename = "2U")]
    Variant2U,
    #[serde(rename = "FY")]
    Fy,
    #[serde(rename = "NF")]
    Nf,

}

impl std::fmt::Display for SecondaryIdentifierTypeCode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Variant2U => write!(f, "2U"),
            Self::Fy => write!(f, "FY"),
            Self::Nf => write!(f, "NF"),
        }
    }
}

impl Default for SecondaryIdentifierTypeCode {
    fn default() -> SecondaryIdentifierTypeCode {
        Self::Variant2U
    }
}

