/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceLineRenderingProviderSecondaryIdentifierItem {
    /// The identifier. The format and length of this value depends on the `qualifier` you set.
    #[serde(rename = "identifier")]
    pub identifier: String,
    /// The identifier for the other payer who provided this reference number. This is only required when the reference number is provided by the non-destination payer. The value must match the `claimInformation.otherSubscriberInformation[].otherPayerName.otherPayerIdentifier` property.
    #[serde(rename = "otherIdentifier", skip_serializing_if = "Option::is_none")]
    pub other_identifier: Option<String>,
    /// Set to `0B` - State License Number, `1G` - Provider UPIN Number, `G2` - Provider Commercial Number, or `LU` - Location Number. Note that UPIN is deprecated and shouldn't be used for new claims.
    #[serde(rename = "qualifier")]
    pub qualifier: String,
}

impl ServiceLineRenderingProviderSecondaryIdentifierItem {
    pub fn new(identifier: String, qualifier: String) -> ServiceLineRenderingProviderSecondaryIdentifierItem {
        ServiceLineRenderingProviderSecondaryIdentifierItem {
            identifier,
            other_identifier: None,
            qualifier,
        }
    }
}

