/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// Status : Information about the status, required action, and paid information of a service line.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Status {
    /// The date the service line was placed in this status by the payer's adjudication process.  This value is returned in ISO 8601 date format (YYYY-MM-DD). For example: 2026-03-04.
    #[serde(rename = "effectiveDate", skip_serializing_if = "Option::is_none")]
    pub effective_date: Option<String>,
    /// The description of the `entityCode`. For example, `Public Health Service Facility`.
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<models::Entity>,
    /// The code identifying the organizational entity, physical location, property, or individual associated with the `statusCode`. For example, `4H` - Emergency Department.  Visit [Claims code lists](https://www.stedi.com/docs/healthcare/claims-code-lists#entity-identifiers) for a complete list.
    #[serde(rename = "entityCode", skip_serializing_if = "Option::is_none")]
    pub entity_code: Option<models::EntityCode>,
    /// The category code for the status. Visit [Claim Status Category Codes](https://x12.org/codes/claim-status-category-codes) in the official X12 documentation for a complete list.
    #[serde(rename = "statusCategoryCode", skip_serializing_if = "Option::is_none")]
    pub status_category_code: Option<String>,
    /// The description of the `statusCategoryCode`.
    #[serde(rename = "statusCategoryCodeValue", skip_serializing_if = "Option::is_none")]
    pub status_category_code_value: Option<String>,
    /// The status code used to identify the status of an entire service line. This is either a [Health Care Claim Status Code](https://x12.org/codes/claim-status-codes) or a National Council for Prescription Drug Programs Reject/Payment Code, when the status is related to pharmacy claims.
    #[serde(rename = "statusCode", skip_serializing_if = "Option::is_none")]
    pub status_code: Option<String>,
    /// The description of the `statusCode`.
    #[serde(rename = "statusCodeValue", skip_serializing_if = "Option::is_none")]
    pub status_code_value: Option<String>,
}

impl Status {
    /// Information about the status, required action, and paid information of a service line.
    pub fn new() -> Status {
        Status {
            effective_date: None,
            entity: None,
            entity_code: None,
            status_category_code: None,
            status_category_code_value: None,
            status_code: None,
            status_code_value: None,
        }
    }
}

