/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// Submitter : The entity submitting the healthcare claim. This can be either an individual or an organization, such as a doctor, hospital, or insurance company. You must submit at least `organizationName` or `lastName` properties and the `contactInformation` object. If you don't supply the `submitterIdentification` property, Stedi uses the value from `billing.npi` in the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Submitter {
    /// Contact information for the person or office handling administrative communications regarding the claim. You can include a maximum of two objects in this array.
    #[serde(rename = "contactInformation")]
    pub contact_information: Box<models::ClaimsContactInformation>,
    /// The first name of the individual submitting the claim.
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// The last name of the individual submitting the claim.
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// The middle name or initial of the individual submitting the claim.
    #[serde(rename = "middleName", skip_serializing_if = "Option::is_none")]
    pub middle_name: Option<String>,
    /// The business name of the organization submitting the claim.
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    /// The submitter's Electronic Transmitter Identification Number (ETIN), as assigned by the payer. For some payers, this may be the same as the submitter's NPI or TIN, but it can also be another unique identifier. Payers can refer to this identifier as the Provider Number, Submitter ID, Submitter Identifier, Submitter Primary Number, Sender Code, Certified Contracted Provider ID, and other names.   If you don't provide this property, Stedi uses the billing provider's NPI from `billing.npi` property.
    #[serde(rename = "submitterIdentification", skip_serializing_if = "Option::is_none")]
    pub submitter_identification: Option<String>,
}

impl Submitter {
    /// The entity submitting the healthcare claim. This can be either an individual or an organization, such as a doctor, hospital, or insurance company. You must submit at least `organizationName` or `lastName` properties and the `contactInformation` object. If you don't supply the `submitterIdentification` property, Stedi uses the value from `billing.npi` in the request.
    pub fn new(contact_information: models::ClaimsContactInformation) -> Submitter {
        Submitter {
            contact_information: Box::new(contact_information),
            first_name: None,
            last_name: None,
            middle_name: None,
            organization_name: None,
            submitter_identification: None,
        }
    }
}

