/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// TechnicalContactMethod : Contact method details for technical support.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TechnicalContactMethod {
    /// The contact email address.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The contact fax number.
    #[serde(rename = "fax", skip_serializing_if = "Option::is_none")]
    pub fax: Option<String>,
    /// The contact telephone number including the area code. Phone numbers are formatted as AAABBBCCCC, where AAA represents the area code, BBB represents the telephone number prefix, and CCCC represents the telephone number. Phone numbers are provided without separators, such as dashes or parentheses. For example, `5551123345` for `555-112-3345`.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// The contact telephone extension, if applicable.
    #[serde(rename = "phoneExtension", skip_serializing_if = "Option::is_none")]
    pub phone_extension: Option<String>,
    /// A web address to contact the person or entity. The URL is typically provided without the scheme and separator. For example, `stedi.com`.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl TechnicalContactMethod {
    /// Contact method details for technical support.
    pub fn new() -> TechnicalContactMethod {
        TechnicalContactMethod {
            email: None,
            fax: None,
            phone: None,
            phone_extension: None,
            url: None,
        }
    }
}

