/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToothStatus {
    /// The tooth number according to the American Dental Association tooth designation system.
    #[serde(rename = "toothNumber")]
    pub tooth_number: String,
    #[serde(rename = "toothStatusCode")]
    pub tooth_status_code: models::ToothStatusCode,
}

impl ToothStatus {
    pub fn new(tooth_number: String, tooth_status_code: models::ToothStatusCode) -> ToothStatus {
        ToothStatus {
            tooth_number,
            tooth_status_code,
        }
    }
}

