/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionSupportStatsItem {
    /// Number of matching payers that require [transaction enrollment](https://www.stedi.com/docs/healthcare/transaction-enrollment) for this transaction type.
    #[serde(rename = "enrollmentRequired")]
    pub enrollment_required: i32,
    /// Number of matching payers that don't support this transaction type.
    #[serde(rename = "notSupported")]
    pub not_supported: i32,
    /// Number of matching payers that support this transaction type.
    #[serde(rename = "supported")]
    pub supported: i32,
}

impl TransactionSupportStatsItem {
    pub fn new(enrollment_required: i32, not_supported: i32, supported: i32) -> TransactionSupportStatsItem {
        TransactionSupportStatsItem {
            enrollment_required,
            not_supported,
            supported,
        }
    }
}

