/*
 * Stedi Healthcare
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2024-04-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::healthcare::models;
use serde::{Deserialize, Serialize};

/// UnitForMeasurement : The name of the `unitForMeasurementQualifierCode`. For example, `Days`.  Payers may sometimes return other non-compliant values.
/// The name of the `unitForMeasurementQualifierCode`. For example, `Days`.  Payers may sometimes return other non-compliant values.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UnitForMeasurement {
    #[serde(rename = "Days")]
    Days,
    #[serde(rename = "Months")]
    Months,
    #[serde(rename = "Visits")]
    Visits,
    #[serde(rename = "Week")]
    Week,
    #[serde(rename = "Years")]
    Years,

}

impl std::fmt::Display for UnitForMeasurement {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Days => write!(f, "Days"),
            Self::Months => write!(f, "Months"),
            Self::Visits => write!(f, "Visits"),
            Self::Week => write!(f, "Week"),
            Self::Years => write!(f, "Years"),
        }
    }
}

impl Default for UnitForMeasurement {
    fn default() -> UnitForMeasurement {
        Self::Days
    }
}

