/*
 * Stedi Event Destinations
 *
 * The Stedi Events Service manages event destinations and event delivery. It supports destination CRUD operations, secret management for signature verification, event creation and management, and delivery tracking with resend capabilities. 
 *
 * The version of the OpenAPI document: 2026-02-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::event_destinations::models;
use serde::{Deserialize, Serialize};

/// EventStatus : The current status of an event.
/// The current status of an event.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "DELIVERED")]
    Delivered,
    #[serde(rename = "FAILED")]
    Failed,

}

impl std::fmt::Display for EventStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "PENDING"),
            Self::Delivered => write!(f, "DELIVERED"),
            Self::Failed => write!(f, "FAILED"),
        }
    }
}

impl Default for EventStatus {
    fn default() -> EventStatus {
        Self::Pending
    }
}

