/*
 * Stedi Event Destinations
 *
 * The Stedi Events Service manages event destinations and event delivery. It supports destination CRUD operations, secret management for signature verification, event creation and management, and delivery tracking with resend capabilities. 
 *
 * The version of the OpenAPI document: 2026-02-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::event_destinations::models;
use serde::{Deserialize, Serialize};

/// TooManyRequestsExceptionResponseContent : The caller has exceeded a rate limit. Retry with backoff.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TooManyRequestsExceptionResponseContent {
    /// Why the request failed. The wording can change, so branch on the exception type, not this text.
    #[serde(rename = "message")]
    pub message: String,
}

impl TooManyRequestsExceptionResponseContent {
    /// The caller has exceeded a rate limit. Retry with backoff.
    pub fn new(message: String) -> TooManyRequestsExceptionResponseContent {
        TooManyRequestsExceptionResponseContent {
            message,
        }
    }
}

