/*
 * Stedi Event Destinations
 *
 * The Stedi Events Service manages event destinations and event delivery. It supports destination CRUD operations, secret management for signature verification, event creation and management, and delivery tracking with resend capabilities. 
 *
 * The version of the OpenAPI document: 2026-02-01
 * Contact: healthcare@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::event_destinations::models;
use serde::{Deserialize, Serialize};

/// UpdateEventDestinationRequestContent : Input for updating a destination.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEventDestinationRequestContent {
    /// Maximum concurrent deliveries for this destination. If not set, Stedi applies your account default (typically 5). Stedi rejects requests exceeding your account maximum (typically 20) with a `400` error. Contact Stedi to change your limits.
    #[serde(rename = "concurrencyLimit", skip_serializing_if = "Option::is_none")]
    pub concurrency_limit: Option<f64>,
    /// A description of the destination's purpose, such as \"Receives transaction enrollment task notifications.\"
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The URL where you want Stedi to deliver payloads through HTTP `POST`.
    #[serde(rename = "destinationUrl", skip_serializing_if = "Option::is_none")]
    pub destination_url: Option<String>,
    /// The event types you want Stedi to send to this destination. Visit [event types](https://www.stedi.com/docs/healthcare/event-destinations-event-types) for a complete list.
    #[serde(rename = "eventTypes", skip_serializing_if = "Option::is_none")]
    pub event_types: Option<Vec<String>>,
    /// A human-readable name for the destination. Stedi displays this name in the portal.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The destination's status. Set to `ENABLED` to receive event deliveries or `DISABLED` to pause them.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::EventDestinationsDestinationInputStatus>,
}

impl UpdateEventDestinationRequestContent {
    /// Input for updating a destination.
    pub fn new() -> UpdateEventDestinationRequestContent {
        UpdateEventDestinationRequestContent {
            concurrency_limit: None,
            description: None,
            destination_url: None,
            event_types: None,
            name: None,
            status: None,
        }
    }
}

