/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// ArtifactUsage : The type of data the artifact contains. For example, an input artifact represents the original data Stedi received before processing, while an output artifact represents the processed data.  For example, for an inbound 835 ERA from a payer, the input artifact would be the original X12 EDI, and the output artifact would be the JSON representation of the ERA.
/// The type of data the artifact contains. For example, an input artifact represents the original data Stedi received before processing, while an output artifact represents the processed data.  For example, for an inbound 835 ERA from a payer, the input artifact would be the original X12 EDI, and the output artifact would be the JSON representation of the ERA.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArtifactUsage {
    #[serde(rename = "attachment")]
    Attachment,
    #[serde(rename = "input")]
    Input,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "output")]
    Output,

}

impl std::fmt::Display for ArtifactUsage {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Attachment => write!(f, "attachment"),
            Self::Input => write!(f, "input"),
            Self::Metadata => write!(f, "metadata"),
            Self::Output => write!(f, "output"),
        }
    }
}

impl Default for ArtifactUsage {
    fn default() -> ArtifactUsage {
        Self::Attachment
    }
}

