/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// CoreCharacterSet : When generating EDI, the character set determines the set of characters allowed in the EDI message. Characters outside of the specified set (after applying any repairs specified in RepairOptions) will result in an error.
/// When generating EDI, the character set determines the set of characters allowed in the EDI message. Characters outside of the specified set (after applying any repairs specified in RepairOptions) will result in an error.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CoreCharacterSet {
    #[serde(rename = "Basic")]
    Basic,
    #[serde(rename = "Extended")]
    Extended,
    #[serde(rename = "ExtendedHipaa")]
    ExtendedHipaa,

}

impl std::fmt::Display for CoreCharacterSet {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Basic => write!(f, "Basic"),
            Self::Extended => write!(f, "Extended"),
            Self::ExtendedHipaa => write!(f, "ExtendedHipaa"),
        }
    }
}

impl Default for CoreCharacterSet {
    fn default() -> CoreCharacterSet {
        Self::Basic
    }
}

