/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryReportStatus {
    #[serde(rename = "FAILED")]
    Failed,
    #[serde(rename = "DELIVERED")]
    Delivered,

}

impl std::fmt::Display for DeliveryReportStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Failed => write!(f, "FAILED"),
            Self::Delivered => write!(f, "DELIVERED"),
        }
    }
}

impl Default for DeliveryReportStatus {
    fn default() -> DeliveryReportStatus {
        Self::Failed
    }
}

