/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// GatewayTimeoutExceptionResponseContent : The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayTimeoutExceptionResponseContent {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
}

impl GatewayTimeoutExceptionResponseContent {
    /// The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.
    pub fn new(message: String) -> GatewayTimeoutExceptionResponseContent {
        GatewayTimeoutExceptionResponseContent {
            message,
            code: None,
        }
    }
}

