/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// Mark : The location in the document where the problem occurred. May be a single index or a range.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mark {
    #[serde(rename = "start")]
    pub start: Box<models::Index>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<Box<models::Index>>,
}

impl Mark {
    /// The location in the document where the problem occurred. May be a single index or a range.
    pub fn new(start: models::Index) -> Mark {
        Mark {
            start: Box::new(start),
            end: None,
        }
    }
}

