/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// TransactionFragmentsSummary : Details about fragments included in the transaction, if applicable. Fragments break large transactions into smaller parts for easier processing and management.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionFragmentsSummary {
    /// The JSON schema key name for the segment in the Stedi guide used to split the transaction into fragments. For example, in an 834 Health Care Benefit Enrollment and Maintenance, this would be `member_level_detail_INS_loop`.
    #[serde(rename = "keyName")]
    pub key_name: String,
    /// The total number of fragments in the transaction.
    #[serde(rename = "fragmentCount")]
    pub fragment_count: f64,
    /// The maximum size of each fragment in kilobytes (KB). Stedi uses this to automatically split large inbound transactions into fragments.
    #[serde(rename = "batchSize")]
    pub batch_size: f64,
}

impl TransactionFragmentsSummary {
    /// Details about fragments included in the transaction, if applicable. Fragments break large transactions into smaller parts for easier processing and management.
    pub fn new(key_name: String, fragment_count: f64, batch_size: f64) -> TransactionFragmentsSummary {
        TransactionFragmentsSummary {
            key_name,
            fragment_count,
            batch_size,
        }
    }
}

