/*
 * Core
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: core@stedi.com
 * Generated by: https://openapi-generator.tech
 */

use crate::core::models;
use serde::{Deserialize, Serialize};

/// X12TransactionMetadataTransaction : Data from the Transaction Set Header of the X12 EDI file.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct X12TransactionMetadataTransaction {
    /// The Transaction Set Control Number ([`ST02`](https://www.stedi.com/edi/x12/segment/ST#ST-02)).
    #[serde(rename = "controlNumber")]
    pub control_number: String,
    /// The Transaction Set Identifier Code ([`ST01`](https://www.stedi.com/edi/x12/segment/ST#ST-01)), which indicates the type of transaction. For example, `837` for an 837 Healthcare Claim.
    #[serde(rename = "transactionSetIdentifier")]
    pub transaction_set_identifier: String,
}

impl X12TransactionMetadataTransaction {
    /// Data from the Transaction Set Header of the X12 EDI file.
    pub fn new(control_number: String, transaction_set_identifier: String) -> X12TransactionMetadataTransaction {
        X12TransactionMetadataTransaction {
            control_number,
            transaction_set_identifier,
        }
    }
}

